/*
 * GoogleMapsPlatformLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.googleapis.www.apis;

import com.googleapis.www.ApiHelper;
import com.googleapis.www.Server;
import com.googleapis.www.exceptions.ApiException;
import com.googleapis.www.http.request.HttpMethod;
import com.googleapis.www.http.response.ApiResponse;
import com.googleapis.www.models.MapsApiElevationJsonResponse;
import io.apimatic.core.ApiCall;
import io.apimatic.core.GlobalConfiguration;
import io.apimatic.coreinterfaces.http.request.ResponseClassType;
import java.io.IOException;
import java.util.List;
import java.util.concurrent.CompletableFuture;
import java.util.concurrent.CompletionException;

/**
 * This class lists all the endpoints of the groups.
 */
public final class ElevationApi extends BaseApi {

    /**
     * Initializes the controller.
     * @param globalConfig    Configurations added in client.
     */
    public ElevationApi(GlobalConfiguration globalConfig) {
        super(globalConfig);
    }

    /**
     * The Elevation API provides a simple interface to query locations on the earth for elevation
     * data. Additionally, you may request sampled elevation data along paths, allowing you to
     * calculate elevation changes along routes. With the Elevation API, you can develop hiking and
     * biking applications, positioning applications, or low resolution surveying applications.
     * Elevation data is available for all locations on the surface of the earth, including depth
     * locations on the ocean floor (which return negative values). In those cases where Google does
     * not possess exact elevation measurements at the precise location you request, the service
     * interpolates and returns an averaged value using the four nearest locations. Elevation values
     * are expressed relative to local mean sea level (LMSL). Requests to the Elevation API utilize
     * different parameters based on whether the request is for discrete locations or for an ordered
     * path. For discrete locations, requests for elevation return data on the specific locations
     * passed in the request; for paths, elevation requests are instead sampled along the given
     * path.
     * @param  locations  Optional parameter: Positional requests are indicated through use of the
     *         locations parameter, indicating elevation requests for the specific locations passed
     *         as latitude/longitude values. The locations parameter may take the following
     *         arguments: - A single coordinate: `locations=40.714728,-73.998672` - An array of
     *         coordinates separated using the pipe ('|') character: ```
     *         locations=40.714728,-73.998672|-34.397,150.644 ``` - A set of encoded coordinates
     *         using the [Encoded Polyline
     *         Algorithm](https://developers.google.com/maps/documentation/utilities/polylinealgorithm):
     *         ``` locations=enc:gfo}EtohhU ``` Latitude and longitude coordinate strings are
     *         defined using numerals within a comma-separated text string. For example,
     *         "40.714728,-73.998672" is a valid locations value. Latitude and longitude values must
     *         correspond to a valid location on the face of the earth. Latitudes can take any value
     *         between -90 and 90 while longitude values can take any value between -180 and 180. If
     *         you specify an invalid latitude or longitude value, your request will be rejected as
     *         a bad request. You may pass any number of multiple coordinates within an array or
     *         encoded polyline, while still constructing a valid URL. Note that when passing
     *         multiple coordinates, the accuracy of any returned data may be of lower resolution
     *         than when requesting data for a single coordinate.
     * @param  path  Optional parameter: An array of comma separated `latitude,longitude` strings.
     * @param  samples  Optional parameter: Required if path parameter is set.
     * @return    Returns the MapsApiElevationJsonResponse wrapped in ApiResponse response from the API call
     * @throws    ApiException    Represents error response from the server.
     * @throws    IOException    Signals that an I/O exception of some sort has occurred.
     */
    public ApiResponse<MapsApiElevationJsonResponse> elevation(
            final List<String> locations,
            final List<String> path,
            final Double samples) throws ApiException, IOException {
        return prepareElevationRequest(locations, path, samples).execute();
    }

    /**
     * The Elevation API provides a simple interface to query locations on the earth for elevation
     * data. Additionally, you may request sampled elevation data along paths, allowing you to
     * calculate elevation changes along routes. With the Elevation API, you can develop hiking and
     * biking applications, positioning applications, or low resolution surveying applications.
     * Elevation data is available for all locations on the surface of the earth, including depth
     * locations on the ocean floor (which return negative values). In those cases where Google does
     * not possess exact elevation measurements at the precise location you request, the service
     * interpolates and returns an averaged value using the four nearest locations. Elevation values
     * are expressed relative to local mean sea level (LMSL). Requests to the Elevation API utilize
     * different parameters based on whether the request is for discrete locations or for an ordered
     * path. For discrete locations, requests for elevation return data on the specific locations
     * passed in the request; for paths, elevation requests are instead sampled along the given
     * path.
     * @param  locations  Optional parameter: Positional requests are indicated through use of the
     *         locations parameter, indicating elevation requests for the specific locations passed
     *         as latitude/longitude values. The locations parameter may take the following
     *         arguments: - A single coordinate: `locations=40.714728,-73.998672` - An array of
     *         coordinates separated using the pipe ('|') character: ```
     *         locations=40.714728,-73.998672|-34.397,150.644 ``` - A set of encoded coordinates
     *         using the [Encoded Polyline
     *         Algorithm](https://developers.google.com/maps/documentation/utilities/polylinealgorithm):
     *         ``` locations=enc:gfo}EtohhU ``` Latitude and longitude coordinate strings are
     *         defined using numerals within a comma-separated text string. For example,
     *         "40.714728,-73.998672" is a valid locations value. Latitude and longitude values must
     *         correspond to a valid location on the face of the earth. Latitudes can take any value
     *         between -90 and 90 while longitude values can take any value between -180 and 180. If
     *         you specify an invalid latitude or longitude value, your request will be rejected as
     *         a bad request. You may pass any number of multiple coordinates within an array or
     *         encoded polyline, while still constructing a valid URL. Note that when passing
     *         multiple coordinates, the accuracy of any returned data may be of lower resolution
     *         than when requesting data for a single coordinate.
     * @param  path  Optional parameter: An array of comma separated `latitude,longitude` strings.
     * @param  samples  Optional parameter: Required if path parameter is set.
     * @return    Returns the MapsApiElevationJsonResponse wrapped in ApiResponse response from the API call
     */
    public CompletableFuture<ApiResponse<MapsApiElevationJsonResponse>> elevationAsync(
            final List<String> locations,
            final List<String> path,
            final Double samples) {
        try {
            return prepareElevationRequest(locations, path, samples).executeAsync();
        } catch (Exception e) {
            throw new CompletionException(e);
        }
    }

    /**
     * Builds the ApiCall object for elevation.
     */
    private ApiCall<ApiResponse<MapsApiElevationJsonResponse>, ApiException> prepareElevationRequest(
            final List<String> locations,
            final List<String> path,
            final Double samples) {
        return new ApiCall.Builder<ApiResponse<MapsApiElevationJsonResponse>, ApiException>()
                .globalConfig(getGlobalConfiguration())
                .requestBuilder(requestBuilder -> requestBuilder
                        .server(Server.ENUM_DEFAULT.value())
                        .path("/maps/api/elevation/json")
                        .queryParam(param -> param.key("locations")
                                .value(locations).isRequired(false))
                        .queryParam(param -> param.key("path")
                                .value(path).isRequired(false))
                        .queryParam(param -> param.key("samples")
                                .value(samples).isRequired(false))
                        .headerParam(param -> param.key("accept").value("application/json"))
                        .withAuth(auth -> auth
                                .add("ApiKeyAuth"))
                        .httpMethod(HttpMethod.GET))
                .responseHandler(responseHandler -> responseHandler
                        .responseClassType(ResponseClassType.API_RESPONSE)
                        .apiResponseDeserializer(
                                response -> ApiHelper.deserialize(response, MapsApiElevationJsonResponse.class))
                        .nullify404(false)
                        .globalErrorCase(GLOBAL_ERROR_CASES))
                .build();
    }
}