/*
 * GoogleMapsPlatformLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.googleapis.www.models;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.AdditionalProperties;
import io.apimatic.core.utilities.ConversionHelper;
import java.util.Map;

/**
 * This is a model class for DirectionsTransitDetails type.
 */
public class DirectionsTransitDetails {
    private DirectionsTransitStop arrivalStop;
    private TimeZoneTextValueObject arrivalTime;
    private DirectionsTransitStop departureStop;
    private TimeZoneTextValueObject departureTime;
    private String headsign;
    private Integer headway;
    private DirectionsTransitLine line;
    private Integer numStops;
    private String tripShortName;
    private AdditionalProperties<Object> additionalProperties = 
            new AdditionalProperties<Object>(this.getClass());

    /**
     * Default constructor.
     */
    public DirectionsTransitDetails() {
    }

    /**
     * Initialization constructor.
     * @param  arrivalStop  DirectionsTransitStop value for arrivalStop.
     * @param  arrivalTime  TimeZoneTextValueObject value for arrivalTime.
     * @param  departureStop  DirectionsTransitStop value for departureStop.
     * @param  departureTime  TimeZoneTextValueObject value for departureTime.
     * @param  headsign  String value for headsign.
     * @param  headway  Integer value for headway.
     * @param  line  DirectionsTransitLine value for line.
     * @param  numStops  Integer value for numStops.
     * @param  tripShortName  String value for tripShortName.
     */
    public DirectionsTransitDetails(
            DirectionsTransitStop arrivalStop,
            TimeZoneTextValueObject arrivalTime,
            DirectionsTransitStop departureStop,
            TimeZoneTextValueObject departureTime,
            String headsign,
            Integer headway,
            DirectionsTransitLine line,
            Integer numStops,
            String tripShortName) {
        this.arrivalStop = arrivalStop;
        this.arrivalTime = arrivalTime;
        this.departureStop = departureStop;
        this.departureTime = departureTime;
        this.headsign = headsign;
        this.headway = headway;
        this.line = line;
        this.numStops = numStops;
        this.tripShortName = tripShortName;
    }

    /**
     * Getter for ArrivalStop.
     * @return Returns the DirectionsTransitStop
     */
    @JsonGetter("arrival_stop")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public DirectionsTransitStop getArrivalStop() {
        return arrivalStop;
    }

    /**
     * Setter for ArrivalStop.
     * @param arrivalStop Value for DirectionsTransitStop
     */
    @JsonSetter("arrival_stop")
    public void setArrivalStop(DirectionsTransitStop arrivalStop) {
        this.arrivalStop = arrivalStop;
    }

    /**
     * Getter for ArrivalTime.
     * An object containing Unix time, a time zone, and its formatted text representation.
     * @return Returns the TimeZoneTextValueObject
     */
    @JsonGetter("arrival_time")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public TimeZoneTextValueObject getArrivalTime() {
        return arrivalTime;
    }

    /**
     * Setter for ArrivalTime.
     * An object containing Unix time, a time zone, and its formatted text representation.
     * @param arrivalTime Value for TimeZoneTextValueObject
     */
    @JsonSetter("arrival_time")
    public void setArrivalTime(TimeZoneTextValueObject arrivalTime) {
        this.arrivalTime = arrivalTime;
    }

    /**
     * Getter for DepartureStop.
     * @return Returns the DirectionsTransitStop
     */
    @JsonGetter("departure_stop")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public DirectionsTransitStop getDepartureStop() {
        return departureStop;
    }

    /**
     * Setter for DepartureStop.
     * @param departureStop Value for DirectionsTransitStop
     */
    @JsonSetter("departure_stop")
    public void setDepartureStop(DirectionsTransitStop departureStop) {
        this.departureStop = departureStop;
    }

    /**
     * Getter for DepartureTime.
     * An object containing Unix time, a time zone, and its formatted text representation.
     * @return Returns the TimeZoneTextValueObject
     */
    @JsonGetter("departure_time")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public TimeZoneTextValueObject getDepartureTime() {
        return departureTime;
    }

    /**
     * Setter for DepartureTime.
     * An object containing Unix time, a time zone, and its formatted text representation.
     * @param departureTime Value for TimeZoneTextValueObject
     */
    @JsonSetter("departure_time")
    public void setDepartureTime(TimeZoneTextValueObject departureTime) {
        this.departureTime = departureTime;
    }

    /**
     * Getter for Headsign.
     * Specifies the direction in which to travel on this line, as it is marked on the vehicle or at
     * the departure stop. This will often be the terminus station.
     * @return Returns the String
     */
    @JsonGetter("headsign")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getHeadsign() {
        return headsign;
    }

    /**
     * Setter for Headsign.
     * Specifies the direction in which to travel on this line, as it is marked on the vehicle or at
     * the departure stop. This will often be the terminus station.
     * @param headsign Value for String
     */
    @JsonSetter("headsign")
    public void setHeadsign(String headsign) {
        this.headsign = headsign;
    }

    /**
     * Getter for Headway.
     * Specifies the expected number of seconds between departures from the same stop at this time.
     * For example, with a `headway` value of 600, you would expect a ten minute wait if you should
     * miss your bus.
     * @return Returns the Integer
     */
    @JsonGetter("headway")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Integer getHeadway() {
        return headway;
    }

    /**
     * Setter for Headway.
     * Specifies the expected number of seconds between departures from the same stop at this time.
     * For example, with a `headway` value of 600, you would expect a ten minute wait if you should
     * miss your bus.
     * @param headway Value for Integer
     */
    @JsonSetter("headway")
    public void setHeadway(Integer headway) {
        this.headway = headway;
    }

    /**
     * Getter for Line.
     * @return Returns the DirectionsTransitLine
     */
    @JsonGetter("line")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public DirectionsTransitLine getLine() {
        return line;
    }

    /**
     * Setter for Line.
     * @param line Value for DirectionsTransitLine
     */
    @JsonSetter("line")
    public void setLine(DirectionsTransitLine line) {
        this.line = line;
    }

    /**
     * Getter for NumStops.
     * The number of stops from the departure to the arrival stop. This includes the arrival stop,
     * but not the departure stop. For example, if your directions involve leaving from Stop A,
     * passing through stops B and C, and arriving at stop D, `num_stops` will return 3.
     * @return Returns the Integer
     */
    @JsonGetter("num_stops")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Integer getNumStops() {
        return numStops;
    }

    /**
     * Setter for NumStops.
     * The number of stops from the departure to the arrival stop. This includes the arrival stop,
     * but not the departure stop. For example, if your directions involve leaving from Stop A,
     * passing through stops B and C, and arriving at stop D, `num_stops` will return 3.
     * @param numStops Value for Integer
     */
    @JsonSetter("num_stops")
    public void setNumStops(Integer numStops) {
        this.numStops = numStops;
    }

    /**
     * Getter for TripShortName.
     * The text that appears in schedules and sign boards to identify a transit trip to passengers.
     * The text should uniquely identify a trip within a service day. For example, "538" is the
     * `trip_short_name` of the Amtrak train that leaves San Jose, CA at 15:10 on weekdays to
     * Sacramento, CA.
     * @return Returns the String
     */
    @JsonGetter("trip_short_name")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getTripShortName() {
        return tripShortName;
    }

    /**
     * Setter for TripShortName.
     * The text that appears in schedules and sign boards to identify a transit trip to passengers.
     * The text should uniquely identify a trip within a service day. For example, "538" is the
     * `trip_short_name` of the Amtrak train that leaves San Jose, CA at 15:10 on weekdays to
     * Sacramento, CA.
     * @param tripShortName Value for String
     */
    @JsonSetter("trip_short_name")
    public void setTripShortName(String tripShortName) {
        this.tripShortName = tripShortName;
    }

    /**
     * Hidden method for the serialization of additional properties.
     * @return The map of additionally set properties.
     */
    @JsonAnyGetter
    private Map<String, Object> getAdditionalProperties() {
        return additionalProperties.getAdditionalProperties();
    }

    /**
     * Hidden method for the de-serialization of additional properties.
     * @param name The name of the additional property.
     * @param value The Object value of the additional property.
     */
    @JsonAnySetter
    private void setAdditionalProperties(String name, Object value) {
        additionalProperties.setAdditionalProperty(name,
                ConversionHelper.convertToSimpleType(value,
                        x -> x),
                true);
    }

    /**
     * Getter for the value of additional properties based on provided property name.
     * @param name The name of the additional property.
     * @return Either the Object property value or null if not exist.
     */
    
    public Object getAdditionalProperty(String name) {
        return additionalProperties.getAdditionalProperty(name);
    }

    /**
     * Converts this DirectionsTransitDetails into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "DirectionsTransitDetails [" + "arrivalStop=" + arrivalStop + ", arrivalTime="
                + arrivalTime + ", departureStop=" + departureStop + ", departureTime="
                + departureTime + ", headsign=" + headsign + ", headway=" + headway + ", line="
                + line + ", numStops=" + numStops + ", tripShortName=" + tripShortName
                + ", additionalProperties=" + additionalProperties + "]";
    }

    /**
     * Builds a new {@link DirectionsTransitDetails.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link DirectionsTransitDetails.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .arrivalStop(getArrivalStop())
                .arrivalTime(getArrivalTime())
                .departureStop(getDepartureStop())
                .departureTime(getDepartureTime())
                .headsign(getHeadsign())
                .headway(getHeadway())
                .line(getLine())
                .numStops(getNumStops())
                .tripShortName(getTripShortName());
        builder.additionalProperties = additionalProperties;
        return builder;
    }

    /**
     * Class to build instances of {@link DirectionsTransitDetails}.
     */
    public static class Builder {
        private DirectionsTransitStop arrivalStop;
        private TimeZoneTextValueObject arrivalTime;
        private DirectionsTransitStop departureStop;
        private TimeZoneTextValueObject departureTime;
        private String headsign;
        private Integer headway;
        private DirectionsTransitLine line;
        private Integer numStops;
        private String tripShortName;
        private AdditionalProperties<Object> additionalProperties =
                new AdditionalProperties<Object>();



        /**
         * Setter for arrivalStop.
         * @param  arrivalStop  DirectionsTransitStop value for arrivalStop.
         * @return Builder
         */
        public Builder arrivalStop(DirectionsTransitStop arrivalStop) {
            this.arrivalStop = arrivalStop;
            return this;
        }

        /**
         * Setter for arrivalTime.
         * @param  arrivalTime  TimeZoneTextValueObject value for arrivalTime.
         * @return Builder
         */
        public Builder arrivalTime(TimeZoneTextValueObject arrivalTime) {
            this.arrivalTime = arrivalTime;
            return this;
        }

        /**
         * Setter for departureStop.
         * @param  departureStop  DirectionsTransitStop value for departureStop.
         * @return Builder
         */
        public Builder departureStop(DirectionsTransitStop departureStop) {
            this.departureStop = departureStop;
            return this;
        }

        /**
         * Setter for departureTime.
         * @param  departureTime  TimeZoneTextValueObject value for departureTime.
         * @return Builder
         */
        public Builder departureTime(TimeZoneTextValueObject departureTime) {
            this.departureTime = departureTime;
            return this;
        }

        /**
         * Setter for headsign.
         * @param  headsign  String value for headsign.
         * @return Builder
         */
        public Builder headsign(String headsign) {
            this.headsign = headsign;
            return this;
        }

        /**
         * Setter for headway.
         * @param  headway  Integer value for headway.
         * @return Builder
         */
        public Builder headway(Integer headway) {
            this.headway = headway;
            return this;
        }

        /**
         * Setter for line.
         * @param  line  DirectionsTransitLine value for line.
         * @return Builder
         */
        public Builder line(DirectionsTransitLine line) {
            this.line = line;
            return this;
        }

        /**
         * Setter for numStops.
         * @param  numStops  Integer value for numStops.
         * @return Builder
         */
        public Builder numStops(Integer numStops) {
            this.numStops = numStops;
            return this;
        }

        /**
         * Setter for tripShortName.
         * @param  tripShortName  String value for tripShortName.
         * @return Builder
         */
        public Builder tripShortName(String tripShortName) {
            this.tripShortName = tripShortName;
            return this;
        }

        /**
         * Setter for additional property that are not in model fields.
         * @param name The name of the additional property.
         * @param value The Object value of the additional property.
         * @return Builder.
         */
        public Builder additionalProperty(String name, Object value) {
            this.additionalProperties.setAdditionalProperty(name, value);
            return this;
        }

        /**
         * Builds a new {@link DirectionsTransitDetails} object using the set fields.
         * @return {@link DirectionsTransitDetails}
         */
        public DirectionsTransitDetails build() {
            DirectionsTransitDetails model =
                    new DirectionsTransitDetails(arrivalStop, arrivalTime, departureStop,
                            departureTime, headsign, headway, line, numStops, tripShortName);
            model.additionalProperties = additionalProperties;
            return model;
        }
    }
}
