/*
 * GoogleMapsPlatformLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.googleapis.www.models;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.AdditionalProperties;
import io.apimatic.core.utilities.ConversionHelper;
import java.util.List;
import java.util.Map;

/**
 * This is a model class for DirectionsRoute type.
 */
public class DirectionsRoute {
    private List<DirectionsLeg> legs;
    private Bounds bounds;
    private String copyrights;
    private String summary;
    private List<Integer> waypointOrder;
    private List<String> warnings;
    private DirectionsPolyline overviewPolyline;
    private Fare fare;
    private AdditionalProperties<Object> additionalProperties = 
            new AdditionalProperties<Object>(this.getClass());

    /**
     * Default constructor.
     */
    public DirectionsRoute() {
    }

    /**
     * Initialization constructor.
     * @param  legs  List of DirectionsLeg value for legs.
     * @param  bounds  Bounds value for bounds.
     * @param  copyrights  String value for copyrights.
     * @param  summary  String value for summary.
     * @param  waypointOrder  List of Integer value for waypointOrder.
     * @param  warnings  List of String value for warnings.
     * @param  overviewPolyline  DirectionsPolyline value for overviewPolyline.
     * @param  fare  Fare value for fare.
     */
    public DirectionsRoute(
            List<DirectionsLeg> legs,
            Bounds bounds,
            String copyrights,
            String summary,
            List<Integer> waypointOrder,
            List<String> warnings,
            DirectionsPolyline overviewPolyline,
            Fare fare) {
        this.legs = legs;
        this.bounds = bounds;
        this.copyrights = copyrights;
        this.summary = summary;
        this.waypointOrder = waypointOrder;
        this.warnings = warnings;
        this.overviewPolyline = overviewPolyline;
        this.fare = fare;
    }

    /**
     * Getter for Legs.
     * An array which contains information about a leg of the route, between two locations within
     * the given route. A separate leg will be present for each waypoint or destination specified.
     * (A route with no waypoints will contain exactly one leg within the legs array.) Each leg
     * consists of a series of steps.
     * @return Returns the List of DirectionsLeg
     */
    @JsonGetter("legs")
    public List<DirectionsLeg> getLegs() {
        return legs;
    }

    /**
     * Setter for Legs.
     * An array which contains information about a leg of the route, between two locations within
     * the given route. A separate leg will be present for each waypoint or destination specified.
     * (A route with no waypoints will contain exactly one leg within the legs array.) Each leg
     * consists of a series of steps.
     * @param legs Value for List of DirectionsLeg
     */
    @JsonSetter("legs")
    public void setLegs(List<DirectionsLeg> legs) {
        this.legs = legs;
    }

    /**
     * Getter for Bounds.
     * A rectangle in geographical coordinates from points at the southwest and northeast corners.
     * @return Returns the Bounds
     */
    @JsonGetter("bounds")
    public Bounds getBounds() {
        return bounds;
    }

    /**
     * Setter for Bounds.
     * A rectangle in geographical coordinates from points at the southwest and northeast corners.
     * @param bounds Value for Bounds
     */
    @JsonSetter("bounds")
    public void setBounds(Bounds bounds) {
        this.bounds = bounds;
    }

    /**
     * Getter for Copyrights.
     * Contains the copyright notices to be displayed for this route. You must handle and display
     * this information yourself. This content is meant to be read as-is. Do not programmatically
     * parse this display-only content.
     * @return Returns the String
     */
    @JsonGetter("copyrights")
    public String getCopyrights() {
        return copyrights;
    }

    /**
     * Setter for Copyrights.
     * Contains the copyright notices to be displayed for this route. You must handle and display
     * this information yourself. This content is meant to be read as-is. Do not programmatically
     * parse this display-only content.
     * @param copyrights Value for String
     */
    @JsonSetter("copyrights")
    public void setCopyrights(String copyrights) {
        this.copyrights = copyrights;
    }

    /**
     * Getter for Summary.
     * Contains a short textual description for the route, suitable for naming and disambiguating
     * the route from alternatives.
     * @return Returns the String
     */
    @JsonGetter("summary")
    public String getSummary() {
        return summary;
    }

    /**
     * Setter for Summary.
     * Contains a short textual description for the route, suitable for naming and disambiguating
     * the route from alternatives.
     * @param summary Value for String
     */
    @JsonSetter("summary")
    public void setSummary(String summary) {
        this.summary = summary;
    }

    /**
     * Getter for WaypointOrder.
     * An array indicating the order of any waypoints in the calculated route. This waypoints may be
     * reordered if the request was passed optimize:true within its waypoints parameter.
     * @return Returns the List of Integer
     */
    @JsonGetter("waypoint_order")
    public List<Integer> getWaypointOrder() {
        return waypointOrder;
    }

    /**
     * Setter for WaypointOrder.
     * An array indicating the order of any waypoints in the calculated route. This waypoints may be
     * reordered if the request was passed optimize:true within its waypoints parameter.
     * @param waypointOrder Value for List of Integer
     */
    @JsonSetter("waypoint_order")
    public void setWaypointOrder(List<Integer> waypointOrder) {
        this.waypointOrder = waypointOrder;
    }

    /**
     * Getter for Warnings.
     * Contains an array of warnings to be displayed when showing these directions. You must handle
     * and display these warnings yourself.
     * @return Returns the List of String
     */
    @JsonGetter("warnings")
    public List<String> getWarnings() {
        return warnings;
    }

    /**
     * Setter for Warnings.
     * Contains an array of warnings to be displayed when showing these directions. You must handle
     * and display these warnings yourself.
     * @param warnings Value for List of String
     */
    @JsonSetter("warnings")
    public void setWarnings(List<String> warnings) {
        this.warnings = warnings;
    }

    /**
     * Getter for OverviewPolyline.
     * [Polyline
     * encoding](https://developers.google.com/maps/documentation/utilities/polylinealgorithm) is a
     * lossy compression algorithm that allows you to store a series of coordinates as a single
     * string. Point coordinates are encoded using signed values. If you only have a few static
     * points, you may also wish to use the interactive polyline encoding utility. The encoding
     * process converts a binary value into a series of character codes for ASCII characters using
     * the familiar base64 encoding scheme: to ensure proper display of these characters, encoded
     * values are summed with 63 (the ASCII character '?') before converting them into ASCII. The
     * algorithm also checks for additional character codes for a given point by checking the least
     * significant bit of each byte group; if this bit is set to 1, the point is not yet fully
     * formed and additional data must follow. Additionally, to conserve space, points only include
     * the offset from the previous point (except of course for the first point). All points are
     * encoded in Base64 as signed integers, as latitudes and longitudes are signed values. The
     * encoding format within a polyline needs to represent two coordinates representing latitude
     * and longitude to a reasonable precision. Given a maximum longitude of +/- 180 degrees to a
     * precision of 5 decimal places (180.00000 to -180.00000), this results in the need for a 32
     * bit signed binary integer value.
     * @return Returns the DirectionsPolyline
     */
    @JsonGetter("overview_polyline")
    public DirectionsPolyline getOverviewPolyline() {
        return overviewPolyline;
    }

    /**
     * Setter for OverviewPolyline.
     * [Polyline
     * encoding](https://developers.google.com/maps/documentation/utilities/polylinealgorithm) is a
     * lossy compression algorithm that allows you to store a series of coordinates as a single
     * string. Point coordinates are encoded using signed values. If you only have a few static
     * points, you may also wish to use the interactive polyline encoding utility. The encoding
     * process converts a binary value into a series of character codes for ASCII characters using
     * the familiar base64 encoding scheme: to ensure proper display of these characters, encoded
     * values are summed with 63 (the ASCII character '?') before converting them into ASCII. The
     * algorithm also checks for additional character codes for a given point by checking the least
     * significant bit of each byte group; if this bit is set to 1, the point is not yet fully
     * formed and additional data must follow. Additionally, to conserve space, points only include
     * the offset from the previous point (except of course for the first point). All points are
     * encoded in Base64 as signed integers, as latitudes and longitudes are signed values. The
     * encoding format within a polyline needs to represent two coordinates representing latitude
     * and longitude to a reasonable precision. Given a maximum longitude of +/- 180 degrees to a
     * precision of 5 decimal places (180.00000 to -180.00000), this results in the need for a 32
     * bit signed binary integer value.
     * @param overviewPolyline Value for DirectionsPolyline
     */
    @JsonSetter("overview_polyline")
    public void setOverviewPolyline(DirectionsPolyline overviewPolyline) {
        this.overviewPolyline = overviewPolyline;
    }

    /**
     * Getter for Fare.
     * The total fare for the route. ``` { "currency" : "USD", "value" : 6, "text" : "$6.00" } ```
     * @return Returns the Fare
     */
    @JsonGetter("fare")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Fare getFare() {
        return fare;
    }

    /**
     * Setter for Fare.
     * The total fare for the route. ``` { "currency" : "USD", "value" : 6, "text" : "$6.00" } ```
     * @param fare Value for Fare
     */
    @JsonSetter("fare")
    public void setFare(Fare fare) {
        this.fare = fare;
    }

    /**
     * Hidden method for the serialization of additional properties.
     * @return The map of additionally set properties.
     */
    @JsonAnyGetter
    private Map<String, Object> getAdditionalProperties() {
        return additionalProperties.getAdditionalProperties();
    }

    /**
     * Hidden method for the de-serialization of additional properties.
     * @param name The name of the additional property.
     * @param value The Object value of the additional property.
     */
    @JsonAnySetter
    private void setAdditionalProperties(String name, Object value) {
        additionalProperties.setAdditionalProperty(name,
                ConversionHelper.convertToSimpleType(value,
                        x -> x),
                true);
    }

    /**
     * Getter for the value of additional properties based on provided property name.
     * @param name The name of the additional property.
     * @return Either the Object property value or null if not exist.
     */
    
    public Object getAdditionalProperty(String name) {
        return additionalProperties.getAdditionalProperty(name);
    }

    /**
     * Converts this DirectionsRoute into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "DirectionsRoute [" + "legs=" + legs + ", bounds=" + bounds + ", copyrights="
                + copyrights + ", summary=" + summary + ", waypointOrder=" + waypointOrder
                + ", warnings=" + warnings + ", overviewPolyline=" + overviewPolyline + ", fare="
                + fare + ", additionalProperties=" + additionalProperties + "]";
    }

    /**
     * Builds a new {@link DirectionsRoute.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link DirectionsRoute.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(legs, bounds, copyrights, summary, waypointOrder, warnings,
                overviewPolyline)
                .fare(getFare());
        builder.additionalProperties = additionalProperties;
        return builder;
    }

    /**
     * Class to build instances of {@link DirectionsRoute}.
     */
    public static class Builder {
        private List<DirectionsLeg> legs;
        private Bounds bounds;
        private String copyrights;
        private String summary;
        private List<Integer> waypointOrder;
        private List<String> warnings;
        private DirectionsPolyline overviewPolyline;
        private Fare fare;
        private AdditionalProperties<Object> additionalProperties =
                new AdditionalProperties<Object>();

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  legs  List of DirectionsLeg value for legs.
         * @param  bounds  Bounds value for bounds.
         * @param  copyrights  String value for copyrights.
         * @param  summary  String value for summary.
         * @param  waypointOrder  List of Integer value for waypointOrder.
         * @param  warnings  List of String value for warnings.
         * @param  overviewPolyline  DirectionsPolyline value for overviewPolyline.
         */
        public Builder(List<DirectionsLeg> legs, Bounds bounds, String copyrights, String summary,
                List<Integer> waypointOrder, List<String> warnings,
                DirectionsPolyline overviewPolyline) {
            this.legs = legs;
            this.bounds = bounds;
            this.copyrights = copyrights;
            this.summary = summary;
            this.waypointOrder = waypointOrder;
            this.warnings = warnings;
            this.overviewPolyline = overviewPolyline;
        }

        /**
         * Setter for legs.
         * @param  legs  List of DirectionsLeg value for legs.
         * @return Builder
         */
        public Builder legs(List<DirectionsLeg> legs) {
            this.legs = legs;
            return this;
        }

        /**
         * Setter for bounds.
         * @param  bounds  Bounds value for bounds.
         * @return Builder
         */
        public Builder bounds(Bounds bounds) {
            this.bounds = bounds;
            return this;
        }

        /**
         * Setter for copyrights.
         * @param  copyrights  String value for copyrights.
         * @return Builder
         */
        public Builder copyrights(String copyrights) {
            this.copyrights = copyrights;
            return this;
        }

        /**
         * Setter for summary.
         * @param  summary  String value for summary.
         * @return Builder
         */
        public Builder summary(String summary) {
            this.summary = summary;
            return this;
        }

        /**
         * Setter for waypointOrder.
         * @param  waypointOrder  List of Integer value for waypointOrder.
         * @return Builder
         */
        public Builder waypointOrder(List<Integer> waypointOrder) {
            this.waypointOrder = waypointOrder;
            return this;
        }

        /**
         * Setter for warnings.
         * @param  warnings  List of String value for warnings.
         * @return Builder
         */
        public Builder warnings(List<String> warnings) {
            this.warnings = warnings;
            return this;
        }

        /**
         * Setter for overviewPolyline.
         * @param  overviewPolyline  DirectionsPolyline value for overviewPolyline.
         * @return Builder
         */
        public Builder overviewPolyline(DirectionsPolyline overviewPolyline) {
            this.overviewPolyline = overviewPolyline;
            return this;
        }

        /**
         * Setter for fare.
         * @param  fare  Fare value for fare.
         * @return Builder
         */
        public Builder fare(Fare fare) {
            this.fare = fare;
            return this;
        }

        /**
         * Setter for additional property that are not in model fields.
         * @param name The name of the additional property.
         * @param value The Object value of the additional property.
         * @return Builder.
         */
        public Builder additionalProperty(String name, Object value) {
            this.additionalProperties.setAdditionalProperty(name, value);
            return this;
        }

        /**
         * Builds a new {@link DirectionsRoute} object using the set fields.
         * @return {@link DirectionsRoute}
         */
        public DirectionsRoute build() {
            DirectionsRoute model =
                    new DirectionsRoute(legs, bounds, copyrights, summary, waypointOrder, warnings,
                            overviewPolyline, fare);
            model.additionalProperties = additionalProperties;
            return model;
        }
    }
}
