/*
 * GoogleMapsPlatformLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.googleapis.www.models;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.AdditionalProperties;
import io.apimatic.core.utilities.ConversionHelper;
import java.util.Map;

/**
 * This is a model class for DistanceMatrixElement type.
 */
public class DistanceMatrixElement {
    private Fare fare;
    private TextValueObject distance;
    private TextValueObject durationInTraffic;
    private TextValueObject duration;
    private DistanceMatrixElementStatus status;
    private AdditionalProperties<Object> additionalProperties = 
            new AdditionalProperties<Object>(this.getClass());

    /**
     * Default constructor.
     */
    public DistanceMatrixElement() {
    }

    /**
     * Initialization constructor.
     * @param  status  DistanceMatrixElementStatus value for status.
     * @param  fare  Fare value for fare.
     * @param  distance  TextValueObject value for distance.
     * @param  durationInTraffic  TextValueObject value for durationInTraffic.
     * @param  duration  TextValueObject value for duration.
     */
    public DistanceMatrixElement(
            DistanceMatrixElementStatus status,
            Fare fare,
            TextValueObject distance,
            TextValueObject durationInTraffic,
            TextValueObject duration) {
        this.fare = fare;
        this.distance = distance;
        this.durationInTraffic = durationInTraffic;
        this.duration = duration;
        this.status = status;
    }

    /**
     * Getter for Fare.
     * The total fare for the route. ``` { "currency" : "USD", "value" : 6, "text" : "$6.00" } ```
     * @return Returns the Fare
     */
    @JsonGetter("fare")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Fare getFare() {
        return fare;
    }

    /**
     * Setter for Fare.
     * The total fare for the route. ``` { "currency" : "USD", "value" : 6, "text" : "$6.00" } ```
     * @param fare Value for Fare
     */
    @JsonSetter("fare")
    public void setFare(Fare fare) {
        this.fare = fare;
    }

    /**
     * Getter for Distance.
     * An object containing a numeric value and its formatted text representation.
     * @return Returns the TextValueObject
     */
    @JsonGetter("distance")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public TextValueObject getDistance() {
        return distance;
    }

    /**
     * Setter for Distance.
     * An object containing a numeric value and its formatted text representation.
     * @param distance Value for TextValueObject
     */
    @JsonSetter("distance")
    public void setDistance(TextValueObject distance) {
        this.distance = distance;
    }

    /**
     * Getter for DurationInTraffic.
     * An object containing a numeric value and its formatted text representation.
     * @return Returns the TextValueObject
     */
    @JsonGetter("duration_in_traffic")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public TextValueObject getDurationInTraffic() {
        return durationInTraffic;
    }

    /**
     * Setter for DurationInTraffic.
     * An object containing a numeric value and its formatted text representation.
     * @param durationInTraffic Value for TextValueObject
     */
    @JsonSetter("duration_in_traffic")
    public void setDurationInTraffic(TextValueObject durationInTraffic) {
        this.durationInTraffic = durationInTraffic;
    }

    /**
     * Getter for Duration.
     * An object containing a numeric value and its formatted text representation.
     * @return Returns the TextValueObject
     */
    @JsonGetter("duration")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public TextValueObject getDuration() {
        return duration;
    }

    /**
     * Setter for Duration.
     * An object containing a numeric value and its formatted text representation.
     * @param duration Value for TextValueObject
     */
    @JsonSetter("duration")
    public void setDuration(TextValueObject duration) {
        this.duration = duration;
    }

    /**
     * Getter for Status.
     * - `OK` indicates the response contains a valid result. - `NOT_FOUND` indicates that the
     * origin and/or destination of this pairing could not be geocoded. - `ZERO_RESULTS` indicates
     * no route could be found between the origin and destination. - `MAX_ROUTE_LENGTH_EXCEEDED`
     * indicates the requested route is too long and cannot be processed.
     * @return Returns the DistanceMatrixElementStatus
     */
    @JsonGetter("status")
    public DistanceMatrixElementStatus getStatus() {
        return status;
    }

    /**
     * Setter for Status.
     * - `OK` indicates the response contains a valid result. - `NOT_FOUND` indicates that the
     * origin and/or destination of this pairing could not be geocoded. - `ZERO_RESULTS` indicates
     * no route could be found between the origin and destination. - `MAX_ROUTE_LENGTH_EXCEEDED`
     * indicates the requested route is too long and cannot be processed.
     * @param status Value for DistanceMatrixElementStatus
     */
    @JsonSetter("status")
    public void setStatus(DistanceMatrixElementStatus status) {
        this.status = status;
    }

    /**
     * Hidden method for the serialization of additional properties.
     * @return The map of additionally set properties.
     */
    @JsonAnyGetter
    private Map<String, Object> getAdditionalProperties() {
        return additionalProperties.getAdditionalProperties();
    }

    /**
     * Hidden method for the de-serialization of additional properties.
     * @param name The name of the additional property.
     * @param value The Object value of the additional property.
     */
    @JsonAnySetter
    private void setAdditionalProperties(String name, Object value) {
        additionalProperties.setAdditionalProperty(name,
                ConversionHelper.convertToSimpleType(value,
                        x -> x),
                true);
    }

    /**
     * Getter for the value of additional properties based on provided property name.
     * @param name The name of the additional property.
     * @return Either the Object property value or null if not exist.
     */
    
    public Object getAdditionalProperty(String name) {
        return additionalProperties.getAdditionalProperty(name);
    }

    /**
     * Converts this DistanceMatrixElement into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "DistanceMatrixElement [" + "status=" + status + ", fare=" + fare + ", distance="
                + distance + ", durationInTraffic=" + durationInTraffic + ", duration=" + duration
                + ", additionalProperties=" + additionalProperties + "]";
    }

    /**
     * Builds a new {@link DistanceMatrixElement.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link DistanceMatrixElement.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(status)
                .fare(getFare())
                .distance(getDistance())
                .durationInTraffic(getDurationInTraffic())
                .duration(getDuration());
        builder.additionalProperties = additionalProperties;
        return builder;
    }

    /**
     * Class to build instances of {@link DistanceMatrixElement}.
     */
    public static class Builder {
        private DistanceMatrixElementStatus status;
        private Fare fare;
        private TextValueObject distance;
        private TextValueObject durationInTraffic;
        private TextValueObject duration;
        private AdditionalProperties<Object> additionalProperties =
                new AdditionalProperties<Object>();

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  status  DistanceMatrixElementStatus value for status.
         */
        public Builder(DistanceMatrixElementStatus status) {
            this.status = status;
        }

        /**
         * Setter for status.
         * @param  status  DistanceMatrixElementStatus value for status.
         * @return Builder
         */
        public Builder status(DistanceMatrixElementStatus status) {
            this.status = status;
            return this;
        }

        /**
         * Setter for fare.
         * @param  fare  Fare value for fare.
         * @return Builder
         */
        public Builder fare(Fare fare) {
            this.fare = fare;
            return this;
        }

        /**
         * Setter for distance.
         * @param  distance  TextValueObject value for distance.
         * @return Builder
         */
        public Builder distance(TextValueObject distance) {
            this.distance = distance;
            return this;
        }

        /**
         * Setter for durationInTraffic.
         * @param  durationInTraffic  TextValueObject value for durationInTraffic.
         * @return Builder
         */
        public Builder durationInTraffic(TextValueObject durationInTraffic) {
            this.durationInTraffic = durationInTraffic;
            return this;
        }

        /**
         * Setter for duration.
         * @param  duration  TextValueObject value for duration.
         * @return Builder
         */
        public Builder duration(TextValueObject duration) {
            this.duration = duration;
            return this;
        }

        /**
         * Setter for additional property that are not in model fields.
         * @param name The name of the additional property.
         * @param value The Object value of the additional property.
         * @return Builder.
         */
        public Builder additionalProperty(String name, Object value) {
            this.additionalProperties.setAdditionalProperty(name, value);
            return this;
        }

        /**
         * Builds a new {@link DistanceMatrixElement} object using the set fields.
         * @return {@link DistanceMatrixElement}
         */
        public DistanceMatrixElement build() {
            DistanceMatrixElement model =
                    new DistanceMatrixElement(status, fare, distance, durationInTraffic, duration);
            model.additionalProperties = additionalProperties;
            return model;
        }
    }
}
