/*
 * GoogleMapsPlatformLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.googleapis.www.models;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.AdditionalProperties;
import io.apimatic.core.utilities.ConversionHelper;
import java.util.List;
import java.util.Map;

/**
 * This is a model class for ElevationResponse type.
 */
public class ElevationResponse {
    private String errorMessage;
    private ElevationStatus status;
    private List<ElevationResult> results;
    private AdditionalProperties<Object> additionalProperties = 
            new AdditionalProperties<Object>(this.getClass());

    /**
     * Default constructor.
     */
    public ElevationResponse() {
    }

    /**
     * Initialization constructor.
     * @param  status  ElevationStatus value for status.
     * @param  results  List of ElevationResult value for results.
     * @param  errorMessage  String value for errorMessage.
     */
    public ElevationResponse(
            ElevationStatus status,
            List<ElevationResult> results,
            String errorMessage) {
        this.errorMessage = errorMessage;
        this.status = status;
        this.results = results;
    }

    /**
     * Getter for ErrorMessage.
     * When the service returns a status code other than `OK`, there may be an additional
     * `error_message` field within the response object. This field contains more detailed
     * information about thereasons behind the given status code. This field is not always returned,
     * and its content is subject to change.
     * @return Returns the String
     */
    @JsonGetter("error_message")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getErrorMessage() {
        return errorMessage;
    }

    /**
     * Setter for ErrorMessage.
     * When the service returns a status code other than `OK`, there may be an additional
     * `error_message` field within the response object. This field contains more detailed
     * information about thereasons behind the given status code. This field is not always returned,
     * and its content is subject to change.
     * @param errorMessage Value for String
     */
    @JsonSetter("error_message")
    public void setErrorMessage(String errorMessage) {
        this.errorMessage = errorMessage;
    }

    /**
     * Getter for Status.
     * Status codes returned by service. - `OK` indicating the API request was successful. -
     * `DATA_NOT_AVAILABLE` indicating that there's no available data for the input locations. -
     * `INVALID_REQUEST` indicating the API request was malformed. - `OVER_DAILY_LIMIT` indicating
     * any of the following: - The API key is missing or invalid. - Billing has not been enabled on
     * your account. - A self-imposed usage cap has been exceeded. - The provided method of payment
     * is no longer valid (for example, a credit card has expired). - `OVER_QUERY_LIMIT` indicating
     * the requestor has exceeded quota. - `REQUEST_DENIED` indicating the API did not complete the
     * request. - `UNKNOWN_ERROR` indicating an unknown error.
     * @return Returns the ElevationStatus
     */
    @JsonGetter("status")
    public ElevationStatus getStatus() {
        return status;
    }

    /**
     * Setter for Status.
     * Status codes returned by service. - `OK` indicating the API request was successful. -
     * `DATA_NOT_AVAILABLE` indicating that there's no available data for the input locations. -
     * `INVALID_REQUEST` indicating the API request was malformed. - `OVER_DAILY_LIMIT` indicating
     * any of the following: - The API key is missing or invalid. - Billing has not been enabled on
     * your account. - A self-imposed usage cap has been exceeded. - The provided method of payment
     * is no longer valid (for example, a credit card has expired). - `OVER_QUERY_LIMIT` indicating
     * the requestor has exceeded quota. - `REQUEST_DENIED` indicating the API did not complete the
     * request. - `UNKNOWN_ERROR` indicating an unknown error.
     * @param status Value for ElevationStatus
     */
    @JsonSetter("status")
    public void setStatus(ElevationStatus status) {
        this.status = status;
    }

    /**
     * Getter for Results.
     * @return Returns the List of ElevationResult
     */
    @JsonGetter("results")
    public List<ElevationResult> getResults() {
        return results;
    }

    /**
     * Setter for Results.
     * @param results Value for List of ElevationResult
     */
    @JsonSetter("results")
    public void setResults(List<ElevationResult> results) {
        this.results = results;
    }

    /**
     * Hidden method for the serialization of additional properties.
     * @return The map of additionally set properties.
     */
    @JsonAnyGetter
    private Map<String, Object> getAdditionalProperties() {
        return additionalProperties.getAdditionalProperties();
    }

    /**
     * Hidden method for the de-serialization of additional properties.
     * @param name The name of the additional property.
     * @param value The Object value of the additional property.
     */
    @JsonAnySetter
    private void setAdditionalProperties(String name, Object value) {
        additionalProperties.setAdditionalProperty(name,
                ConversionHelper.convertToSimpleType(value,
                        x -> x),
                true);
    }

    /**
     * Getter for the value of additional properties based on provided property name.
     * @param name The name of the additional property.
     * @return Either the Object property value or null if not exist.
     */
    
    public Object getAdditionalProperty(String name) {
        return additionalProperties.getAdditionalProperty(name);
    }

    /**
     * Converts this ElevationResponse into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "ElevationResponse [" + "status=" + status + ", results=" + results
                + ", errorMessage=" + errorMessage + ", additionalProperties="
                + additionalProperties + "]";
    }

    /**
     * Builds a new {@link ElevationResponse.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link ElevationResponse.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(status, results)
                .errorMessage(getErrorMessage());
        builder.additionalProperties = additionalProperties;
        return builder;
    }

    /**
     * Class to build instances of {@link ElevationResponse}.
     */
    public static class Builder {
        private ElevationStatus status;
        private List<ElevationResult> results;
        private String errorMessage;
        private AdditionalProperties<Object> additionalProperties =
                new AdditionalProperties<Object>();

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  status  ElevationStatus value for status.
         * @param  results  List of ElevationResult value for results.
         */
        public Builder(ElevationStatus status, List<ElevationResult> results) {
            this.status = status;
            this.results = results;
        }

        /**
         * Setter for status.
         * @param  status  ElevationStatus value for status.
         * @return Builder
         */
        public Builder status(ElevationStatus status) {
            this.status = status;
            return this;
        }

        /**
         * Setter for results.
         * @param  results  List of ElevationResult value for results.
         * @return Builder
         */
        public Builder results(List<ElevationResult> results) {
            this.results = results;
            return this;
        }

        /**
         * Setter for errorMessage.
         * @param  errorMessage  String value for errorMessage.
         * @return Builder
         */
        public Builder errorMessage(String errorMessage) {
            this.errorMessage = errorMessage;
            return this;
        }

        /**
         * Setter for additional property that are not in model fields.
         * @param name The name of the additional property.
         * @param value The Object value of the additional property.
         * @return Builder.
         */
        public Builder additionalProperty(String name, Object value) {
            this.additionalProperties.setAdditionalProperty(name, value);
            return this;
        }

        /**
         * Builds a new {@link ElevationResponse} object using the set fields.
         * @return {@link ElevationResponse}
         */
        public ElevationResponse build() {
            ElevationResponse model =
                    new ElevationResponse(status, results, errorMessage);
            model.additionalProperties = additionalProperties;
            return model;
        }
    }
}
