/*
 * GoogleMapsPlatformLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.googleapis.www.models;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.AdditionalProperties;
import io.apimatic.core.utilities.ConversionHelper;
import java.util.List;
import java.util.Map;

/**
 * This is a model class for ErrorDetail type.
 */
public class ErrorDetail {
    private String mType;
    private String message;
    private String reason;
    private String domain;
    private Object metadata;
    private List<FieldViolation> fieldViolations;
    private AdditionalProperties<Object> additionalProperties = 
            new AdditionalProperties<Object>(this.getClass());

    /**
     * Default constructor.
     */
    public ErrorDetail() {
    }

    /**
     * Initialization constructor.
     * @param  mType  String value for mType.
     * @param  message  String value for message.
     * @param  reason  String value for reason.
     * @param  domain  String value for domain.
     * @param  metadata  Object value for metadata.
     * @param  fieldViolations  List of FieldViolation value for fieldViolations.
     */
    public ErrorDetail(
            String mType,
            String message,
            String reason,
            String domain,
            Object metadata,
            List<FieldViolation> fieldViolations) {
        this.mType = mType;
        this.message = message;
        this.reason = reason;
        this.domain = domain;
        this.metadata = metadata;
        this.fieldViolations = fieldViolations;
    }

    /**
     * Getter for MType.
     * The type of error.
     * @return Returns the String
     */
    @JsonGetter("@type")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getMType() {
        return mType;
    }

    /**
     * Setter for MType.
     * The type of error.
     * @param mType Value for String
     */
    @JsonSetter("@type")
    public void setMType(String mType) {
        this.mType = mType;
    }

    /**
     * Getter for Message.
     * A short description of the error.
     * @return Returns the String
     */
    @JsonGetter("message")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getMessage() {
        return message;
    }

    /**
     * Setter for Message.
     * A short description of the error.
     * @param message Value for String
     */
    @JsonSetter("message")
    public void setMessage(String message) {
        this.message = message;
    }

    /**
     * Getter for Reason.
     * A reason for the error.
     * @return Returns the String
     */
    @JsonGetter("reason")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getReason() {
        return reason;
    }

    /**
     * Setter for Reason.
     * A reason for the error.
     * @param reason Value for String
     */
    @JsonSetter("reason")
    public void setReason(String reason) {
        this.reason = reason;
    }

    /**
     * Getter for Domain.
     * The domain in which the error occurred.
     * @return Returns the String
     */
    @JsonGetter("domain")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getDomain() {
        return domain;
    }

    /**
     * Setter for Domain.
     * The domain in which the error occurred.
     * @param domain Value for String
     */
    @JsonSetter("domain")
    public void setDomain(String domain) {
        this.domain = domain;
    }

    /**
     * Getter for Metadata.
     * Additional metadata about the error.
     * @return Returns the Object
     */
    @JsonGetter("metadata")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Object getMetadata() {
        return metadata;
    }

    /**
     * Setter for Metadata.
     * Additional metadata about the error.
     * @param metadata Value for Object
     */
    @JsonSetter("metadata")
    public void setMetadata(Object metadata) {
        this.metadata = metadata;
    }

    /**
     * Getter for FieldViolations.
     * A list of field violations.
     * @return Returns the List of FieldViolation
     */
    @JsonGetter("fieldViolations")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public List<FieldViolation> getFieldViolations() {
        return fieldViolations;
    }

    /**
     * Setter for FieldViolations.
     * A list of field violations.
     * @param fieldViolations Value for List of FieldViolation
     */
    @JsonSetter("fieldViolations")
    public void setFieldViolations(List<FieldViolation> fieldViolations) {
        this.fieldViolations = fieldViolations;
    }

    /**
     * Hidden method for the serialization of additional properties.
     * @return The map of additionally set properties.
     */
    @JsonAnyGetter
    private Map<String, Object> getAdditionalProperties() {
        return additionalProperties.getAdditionalProperties();
    }

    /**
     * Hidden method for the de-serialization of additional properties.
     * @param name The name of the additional property.
     * @param value The Object value of the additional property.
     */
    @JsonAnySetter
    private void setAdditionalProperties(String name, Object value) {
        additionalProperties.setAdditionalProperty(name,
                ConversionHelper.convertToSimpleType(value,
                        x -> x),
                true);
    }

    /**
     * Getter for the value of additional properties based on provided property name.
     * @param name The name of the additional property.
     * @return Either the Object property value or null if not exist.
     */
    
    public Object getAdditionalProperty(String name) {
        return additionalProperties.getAdditionalProperty(name);
    }

    /**
     * Converts this ErrorDetail into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "ErrorDetail [" + "mType=" + mType + ", message=" + message + ", reason=" + reason
                + ", domain=" + domain + ", metadata=" + metadata + ", fieldViolations="
                + fieldViolations + ", additionalProperties=" + additionalProperties + "]";
    }

    /**
     * Builds a new {@link ErrorDetail.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link ErrorDetail.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .mType(getMType())
                .message(getMessage())
                .reason(getReason())
                .domain(getDomain())
                .metadata(getMetadata())
                .fieldViolations(getFieldViolations());
        builder.additionalProperties = additionalProperties;
        return builder;
    }

    /**
     * Class to build instances of {@link ErrorDetail}.
     */
    public static class Builder {
        private String mType;
        private String message;
        private String reason;
        private String domain;
        private Object metadata;
        private List<FieldViolation> fieldViolations;
        private AdditionalProperties<Object> additionalProperties =
                new AdditionalProperties<Object>();



        /**
         * Setter for mType.
         * @param  mType  String value for mType.
         * @return Builder
         */
        public Builder mType(String mType) {
            this.mType = mType;
            return this;
        }

        /**
         * Setter for message.
         * @param  message  String value for message.
         * @return Builder
         */
        public Builder message(String message) {
            this.message = message;
            return this;
        }

        /**
         * Setter for reason.
         * @param  reason  String value for reason.
         * @return Builder
         */
        public Builder reason(String reason) {
            this.reason = reason;
            return this;
        }

        /**
         * Setter for domain.
         * @param  domain  String value for domain.
         * @return Builder
         */
        public Builder domain(String domain) {
            this.domain = domain;
            return this;
        }

        /**
         * Setter for metadata.
         * @param  metadata  Object value for metadata.
         * @return Builder
         */
        public Builder metadata(Object metadata) {
            this.metadata = metadata;
            return this;
        }

        /**
         * Setter for fieldViolations.
         * @param  fieldViolations  List of FieldViolation value for fieldViolations.
         * @return Builder
         */
        public Builder fieldViolations(List<FieldViolation> fieldViolations) {
            this.fieldViolations = fieldViolations;
            return this;
        }

        /**
         * Setter for additional property that are not in model fields.
         * @param name The name of the additional property.
         * @param value The Object value of the additional property.
         * @return Builder.
         */
        public Builder additionalProperty(String name, Object value) {
            this.additionalProperties.setAdditionalProperty(name, value);
            return this;
        }

        /**
         * Builds a new {@link ErrorDetail} object using the set fields.
         * @return {@link ErrorDetail}
         */
        public ErrorDetail build() {
            ErrorDetail model =
                    new ErrorDetail(mType, message, reason, domain, metadata, fieldViolations);
            model.additionalProperties = additionalProperties;
            return model;
        }
    }
}
