/*
 * GoogleMapsPlatformLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.googleapis.www.models;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.AdditionalProperties;
import io.apimatic.core.utilities.ConversionHelper;
import java.util.Map;

/**
 * This is a model class for Fare type.
 */
public class Fare {
    private String currency;
    private double value;
    private String text;
    private AdditionalProperties<Object> additionalProperties = 
            new AdditionalProperties<Object>(this.getClass());

    /**
     * Default constructor.
     */
    public Fare() {
    }

    /**
     * Initialization constructor.
     * @param  currency  String value for currency.
     * @param  value  double value for value.
     * @param  text  String value for text.
     */
    public Fare(
            String currency,
            double value,
            String text) {
        this.currency = currency;
        this.value = value;
        this.text = text;
    }

    /**
     * Getter for Currency.
     * An [ISO 4217 currency code](https://en.wikipedia.org/wiki/ISO_4217) indicating the currency
     * that the amount is expressed in.
     * @return Returns the String
     */
    @JsonGetter("currency")
    public String getCurrency() {
        return currency;
    }

    /**
     * Setter for Currency.
     * An [ISO 4217 currency code](https://en.wikipedia.org/wiki/ISO_4217) indicating the currency
     * that the amount is expressed in.
     * @param currency Value for String
     */
    @JsonSetter("currency")
    public void setCurrency(String currency) {
        this.currency = currency;
    }

    /**
     * Getter for Value.
     * The total fare amount, in the currency specified.
     * @return Returns the double
     */
    @JsonGetter("value")
    public double getValue() {
        return value;
    }

    /**
     * Setter for Value.
     * The total fare amount, in the currency specified.
     * @param value Value for double
     */
    @JsonSetter("value")
    public void setValue(double value) {
        this.value = value;
    }

    /**
     * Getter for Text.
     * The total fare amount, formatted in the requested language.
     * @return Returns the String
     */
    @JsonGetter("text")
    public String getText() {
        return text;
    }

    /**
     * Setter for Text.
     * The total fare amount, formatted in the requested language.
     * @param text Value for String
     */
    @JsonSetter("text")
    public void setText(String text) {
        this.text = text;
    }

    /**
     * Hidden method for the serialization of additional properties.
     * @return The map of additionally set properties.
     */
    @JsonAnyGetter
    private Map<String, Object> getAdditionalProperties() {
        return additionalProperties.getAdditionalProperties();
    }

    /**
     * Hidden method for the de-serialization of additional properties.
     * @param name The name of the additional property.
     * @param value The Object value of the additional property.
     */
    @JsonAnySetter
    private void setAdditionalProperties(String name, Object value) {
        additionalProperties.setAdditionalProperty(name,
                ConversionHelper.convertToSimpleType(value,
                        x -> x),
                true);
    }

    /**
     * Getter for the value of additional properties based on provided property name.
     * @param name The name of the additional property.
     * @return Either the Object property value or null if not exist.
     */
    
    public Object getAdditionalProperty(String name) {
        return additionalProperties.getAdditionalProperty(name);
    }

    /**
     * Converts this Fare into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "Fare [" + "currency=" + currency + ", value=" + value + ", text=" + text
                + ", additionalProperties=" + additionalProperties + "]";
    }

    /**
     * Builds a new {@link Fare.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link Fare.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(currency, value, text);
        builder.additionalProperties = additionalProperties;
        return builder;
    }

    /**
     * Class to build instances of {@link Fare}.
     */
    public static class Builder {
        private String currency;
        private double value;
        private String text;
        private AdditionalProperties<Object> additionalProperties =
                new AdditionalProperties<Object>();

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  currency  String value for currency.
         * @param  value  double value for value.
         * @param  text  String value for text.
         */
        public Builder(String currency, double value, String text) {
            this.currency = currency;
            this.value = value;
            this.text = text;
        }

        /**
         * Setter for currency.
         * @param  currency  String value for currency.
         * @return Builder
         */
        public Builder currency(String currency) {
            this.currency = currency;
            return this;
        }

        /**
         * Setter for value.
         * @param  value  double value for value.
         * @return Builder
         */
        public Builder value(double value) {
            this.value = value;
            return this;
        }

        /**
         * Setter for text.
         * @param  text  String value for text.
         * @return Builder
         */
        public Builder text(String text) {
            this.text = text;
            return this;
        }

        /**
         * Setter for additional property that are not in model fields.
         * @param name The name of the additional property.
         * @param value The Object value of the additional property.
         * @return Builder.
         */
        public Builder additionalProperty(String name, Object value) {
            this.additionalProperties.setAdditionalProperty(name, value);
            return this;
        }

        /**
         * Builds a new {@link Fare} object using the set fields.
         * @return {@link Fare}
         */
        public Fare build() {
            Fare model =
                    new Fare(currency, value, text);
            model.additionalProperties = additionalProperties;
            return model;
        }
    }
}
