/*
 * GoogleMapsPlatformLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.googleapis.www.models;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.AdditionalProperties;
import io.apimatic.core.utilities.ConversionHelper;
import java.util.Map;

/**
 * This is a model class for Geometry type.
 */
public class Geometry {
    private LatLngLiteral location;
    private Bounds viewport;
    private AdditionalProperties<Object> additionalProperties = 
            new AdditionalProperties<Object>(this.getClass());

    /**
     * Default constructor.
     */
    public Geometry() {
    }

    /**
     * Initialization constructor.
     * @param  location  LatLngLiteral value for location.
     * @param  viewport  Bounds value for viewport.
     */
    public Geometry(
            LatLngLiteral location,
            Bounds viewport) {
        this.location = location;
        this.viewport = viewport;
    }

    /**
     * Getter for Location.
     * An object describing a specific location with Latitude and Longitude in decimal degrees.
     * @return Returns the LatLngLiteral
     */
    @JsonGetter("location")
    public LatLngLiteral getLocation() {
        return location;
    }

    /**
     * Setter for Location.
     * An object describing a specific location with Latitude and Longitude in decimal degrees.
     * @param location Value for LatLngLiteral
     */
    @JsonSetter("location")
    public void setLocation(LatLngLiteral location) {
        this.location = location;
    }

    /**
     * Getter for Viewport.
     * A rectangle in geographical coordinates from points at the southwest and northeast corners.
     * @return Returns the Bounds
     */
    @JsonGetter("viewport")
    public Bounds getViewport() {
        return viewport;
    }

    /**
     * Setter for Viewport.
     * A rectangle in geographical coordinates from points at the southwest and northeast corners.
     * @param viewport Value for Bounds
     */
    @JsonSetter("viewport")
    public void setViewport(Bounds viewport) {
        this.viewport = viewport;
    }

    /**
     * Hidden method for the serialization of additional properties.
     * @return The map of additionally set properties.
     */
    @JsonAnyGetter
    private Map<String, Object> getAdditionalProperties() {
        return additionalProperties.getAdditionalProperties();
    }

    /**
     * Hidden method for the de-serialization of additional properties.
     * @param name The name of the additional property.
     * @param value The Object value of the additional property.
     */
    @JsonAnySetter
    private void setAdditionalProperties(String name, Object value) {
        additionalProperties.setAdditionalProperty(name,
                ConversionHelper.convertToSimpleType(value,
                        x -> x),
                true);
    }

    /**
     * Getter for the value of additional properties based on provided property name.
     * @param name The name of the additional property.
     * @return Either the Object property value or null if not exist.
     */
    
    public Object getAdditionalProperty(String name) {
        return additionalProperties.getAdditionalProperty(name);
    }

    /**
     * Converts this Geometry into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "Geometry [" + "location=" + location + ", viewport=" + viewport
                + ", additionalProperties=" + additionalProperties + "]";
    }

    /**
     * Builds a new {@link Geometry.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link Geometry.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(location, viewport);
        builder.additionalProperties = additionalProperties;
        return builder;
    }

    /**
     * Class to build instances of {@link Geometry}.
     */
    public static class Builder {
        private LatLngLiteral location;
        private Bounds viewport;
        private AdditionalProperties<Object> additionalProperties =
                new AdditionalProperties<Object>();

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  location  LatLngLiteral value for location.
         * @param  viewport  Bounds value for viewport.
         */
        public Builder(LatLngLiteral location, Bounds viewport) {
            this.location = location;
            this.viewport = viewport;
        }

        /**
         * Setter for location.
         * @param  location  LatLngLiteral value for location.
         * @return Builder
         */
        public Builder location(LatLngLiteral location) {
            this.location = location;
            return this;
        }

        /**
         * Setter for viewport.
         * @param  viewport  Bounds value for viewport.
         * @return Builder
         */
        public Builder viewport(Bounds viewport) {
            this.viewport = viewport;
            return this;
        }

        /**
         * Setter for additional property that are not in model fields.
         * @param name The name of the additional property.
         * @param value The Object value of the additional property.
         * @return Builder.
         */
        public Builder additionalProperty(String name, Object value) {
            this.additionalProperties.setAdditionalProperty(name, value);
            return this;
        }

        /**
         * Builds a new {@link Geometry} object using the set fields.
         * @return {@link Geometry}
         */
        public Geometry build() {
            Geometry model =
                    new Geometry(location, viewport);
            model.additionalProperties = additionalProperties;
            return model;
        }
    }
}
