/*
 * GoogleMapsPlatformLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.googleapis.www.models;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.AdditionalProperties;
import io.apimatic.core.utilities.ConversionHelper;
import java.util.Map;

/**
 * This is a model class for LatitudeLongitudeLiteral type.
 */
public class LatitudeLongitudeLiteral {
    private double latitude;
    private double longitude;
    private AdditionalProperties<Object> additionalProperties = 
            new AdditionalProperties<Object>(this.getClass());

    /**
     * Default constructor.
     */
    public LatitudeLongitudeLiteral() {
    }

    /**
     * Initialization constructor.
     * @param  latitude  double value for latitude.
     * @param  longitude  double value for longitude.
     */
    public LatitudeLongitudeLiteral(
            double latitude,
            double longitude) {
        this.latitude = latitude;
        this.longitude = longitude;
    }

    /**
     * Getter for Latitude.
     * Latitude in decimal degrees
     * @return Returns the double
     */
    @JsonGetter("latitude")
    public double getLatitude() {
        return latitude;
    }

    /**
     * Setter for Latitude.
     * Latitude in decimal degrees
     * @param latitude Value for double
     */
    @JsonSetter("latitude")
    public void setLatitude(double latitude) {
        this.latitude = latitude;
    }

    /**
     * Getter for Longitude.
     * Longitude in decimal degrees
     * @return Returns the double
     */
    @JsonGetter("longitude")
    public double getLongitude() {
        return longitude;
    }

    /**
     * Setter for Longitude.
     * Longitude in decimal degrees
     * @param longitude Value for double
     */
    @JsonSetter("longitude")
    public void setLongitude(double longitude) {
        this.longitude = longitude;
    }

    /**
     * Hidden method for the serialization of additional properties.
     * @return The map of additionally set properties.
     */
    @JsonAnyGetter
    private Map<String, Object> getAdditionalProperties() {
        return additionalProperties.getAdditionalProperties();
    }

    /**
     * Hidden method for the de-serialization of additional properties.
     * @param name The name of the additional property.
     * @param value The Object value of the additional property.
     */
    @JsonAnySetter
    private void setAdditionalProperties(String name, Object value) {
        additionalProperties.setAdditionalProperty(name,
                ConversionHelper.convertToSimpleType(value,
                        x -> x),
                true);
    }

    /**
     * Getter for the value of additional properties based on provided property name.
     * @param name The name of the additional property.
     * @return Either the Object property value or null if not exist.
     */
    
    public Object getAdditionalProperty(String name) {
        return additionalProperties.getAdditionalProperty(name);
    }

    /**
     * Converts this LatitudeLongitudeLiteral into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "LatitudeLongitudeLiteral [" + "latitude=" + latitude + ", longitude=" + longitude
                + ", additionalProperties=" + additionalProperties + "]";
    }

    /**
     * Builds a new {@link LatitudeLongitudeLiteral.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link LatitudeLongitudeLiteral.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(latitude, longitude);
        builder.additionalProperties = additionalProperties;
        return builder;
    }

    /**
     * Class to build instances of {@link LatitudeLongitudeLiteral}.
     */
    public static class Builder {
        private double latitude;
        private double longitude;
        private AdditionalProperties<Object> additionalProperties =
                new AdditionalProperties<Object>();

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  latitude  double value for latitude.
         * @param  longitude  double value for longitude.
         */
        public Builder(double latitude, double longitude) {
            this.latitude = latitude;
            this.longitude = longitude;
        }

        /**
         * Setter for latitude.
         * @param  latitude  double value for latitude.
         * @return Builder
         */
        public Builder latitude(double latitude) {
            this.latitude = latitude;
            return this;
        }

        /**
         * Setter for longitude.
         * @param  longitude  double value for longitude.
         * @return Builder
         */
        public Builder longitude(double longitude) {
            this.longitude = longitude;
            return this;
        }

        /**
         * Setter for additional property that are not in model fields.
         * @param name The name of the additional property.
         * @param value The Object value of the additional property.
         * @return Builder.
         */
        public Builder additionalProperty(String name, Object value) {
            this.additionalProperties.setAdditionalProperty(name, value);
            return this;
        }

        /**
         * Builds a new {@link LatitudeLongitudeLiteral} object using the set fields.
         * @return {@link LatitudeLongitudeLiteral}
         */
        public LatitudeLongitudeLiteral build() {
            LatitudeLongitudeLiteral model =
                    new LatitudeLongitudeLiteral(latitude, longitude);
            model.additionalProperties = additionalProperties;
            return model;
        }
    }
}
