/*
 * GoogleMapsPlatformLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.googleapis.www.models;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.AdditionalProperties;
import io.apimatic.core.utilities.ConversionHelper;
import java.util.List;
import java.util.Map;

/**
 * This is a model class for PlacesNearbySearchResponse type.
 */
public class PlacesNearbySearchResponse {
    private List<String> htmlAttributions;
    private List<Place> results;
    private PlacesSearchStatus status;
    private String errorMessage;
    private List<String> infoMessages;
    private String nextPageToken;
    private AdditionalProperties<Object> additionalProperties = 
            new AdditionalProperties<Object>(this.getClass());

    /**
     * Default constructor.
     */
    public PlacesNearbySearchResponse() {
    }

    /**
     * Initialization constructor.
     * @param  htmlAttributions  List of String value for htmlAttributions.
     * @param  results  List of Place value for results.
     * @param  status  PlacesSearchStatus value for status.
     * @param  errorMessage  String value for errorMessage.
     * @param  infoMessages  List of String value for infoMessages.
     * @param  nextPageToken  String value for nextPageToken.
     */
    public PlacesNearbySearchResponse(
            List<String> htmlAttributions,
            List<Place> results,
            PlacesSearchStatus status,
            String errorMessage,
            List<String> infoMessages,
            String nextPageToken) {
        this.htmlAttributions = htmlAttributions;
        this.results = results;
        this.status = status;
        this.errorMessage = errorMessage;
        this.infoMessages = infoMessages;
        this.nextPageToken = nextPageToken;
    }

    /**
     * Getter for HtmlAttributions.
     * May contain a set of attributions about this listing which must be displayed to the user
     * (some listings may not have attribution).
     * @return Returns the List of String
     */
    @JsonGetter("html_attributions")
    public List<String> getHtmlAttributions() {
        return htmlAttributions;
    }

    /**
     * Setter for HtmlAttributions.
     * May contain a set of attributions about this listing which must be displayed to the user
     * (some listings may not have attribution).
     * @param htmlAttributions Value for List of String
     */
    @JsonSetter("html_attributions")
    public void setHtmlAttributions(List<String> htmlAttributions) {
        this.htmlAttributions = htmlAttributions;
    }

    /**
     * Getter for Results.
     * Contains an array of places. &lt;div class="caution"&gt;Place Search requests return a subset of
     * the fields that are returned by Place Details requests. If the field you want is not returned
     * by Place Search, you can use Place Search to get a `place_id`, then use that Place ID to make
     * a Place Details request.&lt;/div&gt;
     * @return Returns the List of Place
     */
    @JsonGetter("results")
    public List<Place> getResults() {
        return results;
    }

    /**
     * Setter for Results.
     * Contains an array of places. &lt;div class="caution"&gt;Place Search requests return a subset of
     * the fields that are returned by Place Details requests. If the field you want is not returned
     * by Place Search, you can use Place Search to get a `place_id`, then use that Place ID to make
     * a Place Details request.&lt;/div&gt;
     * @param results Value for List of Place
     */
    @JsonSetter("results")
    public void setResults(List<Place> results) {
        this.results = results;
    }

    /**
     * Getter for Status.
     * Status codes returned by service. - `OK` indicating the API request was successful. -
     * `ZERO_RESULTS` indicating that the search was successful but returned no results. This may
     * occur if the search was passed a `latlng` in a remote location. - `INVALID_REQUEST`
     * indicating the API request was malformed, generally due to missing required query parameter
     * (`location` or `radius`). - `OVER_QUERY_LIMIT` indicating any of the following: - You have
     * exceeded the QPS limits. - Billing has not been enabled on your account. - The monthly $200
     * credit, or a self-imposed usage cap, has been exceeded. - The provided method of payment is
     * no longer valid (for example, a credit card has expired). See the [Maps
     * FAQ](https://developers.google.com/maps/faq#over-limit-key-error) for more information about
     * how to resolve this error. - `REQUEST_DENIED` indicating that your request was denied,
     * generally because: - The request is missing an API key. - The `key` parameter is invalid. -
     * `UNKNOWN_ERROR` indicating an unknown error.
     * @return Returns the PlacesSearchStatus
     */
    @JsonGetter("status")
    public PlacesSearchStatus getStatus() {
        return status;
    }

    /**
     * Setter for Status.
     * Status codes returned by service. - `OK` indicating the API request was successful. -
     * `ZERO_RESULTS` indicating that the search was successful but returned no results. This may
     * occur if the search was passed a `latlng` in a remote location. - `INVALID_REQUEST`
     * indicating the API request was malformed, generally due to missing required query parameter
     * (`location` or `radius`). - `OVER_QUERY_LIMIT` indicating any of the following: - You have
     * exceeded the QPS limits. - Billing has not been enabled on your account. - The monthly $200
     * credit, or a self-imposed usage cap, has been exceeded. - The provided method of payment is
     * no longer valid (for example, a credit card has expired). See the [Maps
     * FAQ](https://developers.google.com/maps/faq#over-limit-key-error) for more information about
     * how to resolve this error. - `REQUEST_DENIED` indicating that your request was denied,
     * generally because: - The request is missing an API key. - The `key` parameter is invalid. -
     * `UNKNOWN_ERROR` indicating an unknown error.
     * @param status Value for PlacesSearchStatus
     */
    @JsonSetter("status")
    public void setStatus(PlacesSearchStatus status) {
        this.status = status;
    }

    /**
     * Getter for ErrorMessage.
     * When the service returns a status code other than `OK&lt;`, there may be an additional
     * `error_message` field within the response object. This field contains more detailed
     * information about thereasons behind the given status code. This field is not always returned,
     * and its content is subject to change.
     * @return Returns the String
     */
    @JsonGetter("error_message")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getErrorMessage() {
        return errorMessage;
    }

    /**
     * Setter for ErrorMessage.
     * When the service returns a status code other than `OK&lt;`, there may be an additional
     * `error_message` field within the response object. This field contains more detailed
     * information about thereasons behind the given status code. This field is not always returned,
     * and its content is subject to change.
     * @param errorMessage Value for String
     */
    @JsonSetter("error_message")
    public void setErrorMessage(String errorMessage) {
        this.errorMessage = errorMessage;
    }

    /**
     * Getter for InfoMessages.
     * When the service returns additional information about the request specification, there may be
     * an additional `info_messages` field within the response object. This field is only returned
     * for successful requests. It may not always be returned, and its content is subject to change.
     * @return Returns the List of String
     */
    @JsonGetter("info_messages")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public List<String> getInfoMessages() {
        return infoMessages;
    }

    /**
     * Setter for InfoMessages.
     * When the service returns additional information about the request specification, there may be
     * an additional `info_messages` field within the response object. This field is only returned
     * for successful requests. It may not always be returned, and its content is subject to change.
     * @param infoMessages Value for List of String
     */
    @JsonSetter("info_messages")
    public void setInfoMessages(List<String> infoMessages) {
        this.infoMessages = infoMessages;
    }

    /**
     * Getter for NextPageToken.
     * Contains a token that can be used to return up to 20 additional results. A next_page_token
     * will not be returned if there are no additional results to display. The maximum number of
     * results that can be returned is 60. There is a short delay between when a next_page_token is
     * issued, and when it will become valid.
     * @return Returns the String
     */
    @JsonGetter("next_page_token")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getNextPageToken() {
        return nextPageToken;
    }

    /**
     * Setter for NextPageToken.
     * Contains a token that can be used to return up to 20 additional results. A next_page_token
     * will not be returned if there are no additional results to display. The maximum number of
     * results that can be returned is 60. There is a short delay between when a next_page_token is
     * issued, and when it will become valid.
     * @param nextPageToken Value for String
     */
    @JsonSetter("next_page_token")
    public void setNextPageToken(String nextPageToken) {
        this.nextPageToken = nextPageToken;
    }

    /**
     * Hidden method for the serialization of additional properties.
     * @return The map of additionally set properties.
     */
    @JsonAnyGetter
    private Map<String, Object> getAdditionalProperties() {
        return additionalProperties.getAdditionalProperties();
    }

    /**
     * Hidden method for the de-serialization of additional properties.
     * @param name The name of the additional property.
     * @param value The Object value of the additional property.
     */
    @JsonAnySetter
    private void setAdditionalProperties(String name, Object value) {
        additionalProperties.setAdditionalProperty(name,
                ConversionHelper.convertToSimpleType(value,
                        x -> x),
                true);
    }

    /**
     * Getter for the value of additional properties based on provided property name.
     * @param name The name of the additional property.
     * @return Either the Object property value or null if not exist.
     */
    
    public Object getAdditionalProperty(String name) {
        return additionalProperties.getAdditionalProperty(name);
    }

    /**
     * Converts this PlacesNearbySearchResponse into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "PlacesNearbySearchResponse [" + "htmlAttributions=" + htmlAttributions
                + ", results=" + results + ", status=" + status + ", errorMessage=" + errorMessage
                + ", infoMessages=" + infoMessages + ", nextPageToken=" + nextPageToken
                + ", additionalProperties=" + additionalProperties + "]";
    }

    /**
     * Builds a new {@link PlacesNearbySearchResponse.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link PlacesNearbySearchResponse.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(htmlAttributions, results, status)
                .errorMessage(getErrorMessage())
                .infoMessages(getInfoMessages())
                .nextPageToken(getNextPageToken());
        builder.additionalProperties = additionalProperties;
        return builder;
    }

    /**
     * Class to build instances of {@link PlacesNearbySearchResponse}.
     */
    public static class Builder {
        private List<String> htmlAttributions;
        private List<Place> results;
        private PlacesSearchStatus status;
        private String errorMessage;
        private List<String> infoMessages;
        private String nextPageToken;
        private AdditionalProperties<Object> additionalProperties =
                new AdditionalProperties<Object>();

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  htmlAttributions  List of String value for htmlAttributions.
         * @param  results  List of Place value for results.
         * @param  status  PlacesSearchStatus value for status.
         */
        public Builder(List<String> htmlAttributions, List<Place> results,
                PlacesSearchStatus status) {
            this.htmlAttributions = htmlAttributions;
            this.results = results;
            this.status = status;
        }

        /**
         * Setter for htmlAttributions.
         * @param  htmlAttributions  List of String value for htmlAttributions.
         * @return Builder
         */
        public Builder htmlAttributions(List<String> htmlAttributions) {
            this.htmlAttributions = htmlAttributions;
            return this;
        }

        /**
         * Setter for results.
         * @param  results  List of Place value for results.
         * @return Builder
         */
        public Builder results(List<Place> results) {
            this.results = results;
            return this;
        }

        /**
         * Setter for status.
         * @param  status  PlacesSearchStatus value for status.
         * @return Builder
         */
        public Builder status(PlacesSearchStatus status) {
            this.status = status;
            return this;
        }

        /**
         * Setter for errorMessage.
         * @param  errorMessage  String value for errorMessage.
         * @return Builder
         */
        public Builder errorMessage(String errorMessage) {
            this.errorMessage = errorMessage;
            return this;
        }

        /**
         * Setter for infoMessages.
         * @param  infoMessages  List of String value for infoMessages.
         * @return Builder
         */
        public Builder infoMessages(List<String> infoMessages) {
            this.infoMessages = infoMessages;
            return this;
        }

        /**
         * Setter for nextPageToken.
         * @param  nextPageToken  String value for nextPageToken.
         * @return Builder
         */
        public Builder nextPageToken(String nextPageToken) {
            this.nextPageToken = nextPageToken;
            return this;
        }

        /**
         * Setter for additional property that are not in model fields.
         * @param name The name of the additional property.
         * @param value The Object value of the additional property.
         * @return Builder.
         */
        public Builder additionalProperty(String name, Object value) {
            this.additionalProperties.setAdditionalProperty(name, value);
            return this;
        }

        /**
         * Builds a new {@link PlacesNearbySearchResponse} object using the set fields.
         * @return {@link PlacesNearbySearchResponse}
         */
        public PlacesNearbySearchResponse build() {
            PlacesNearbySearchResponse model =
                    new PlacesNearbySearchResponse(htmlAttributions, results, status, errorMessage,
                            infoMessages, nextPageToken);
            model.additionalProperties = additionalProperties;
            return model;
        }
    }
}
