/*
 * GoogleMapsPlatformLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.googleapis.www.models;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.AdditionalProperties;
import io.apimatic.core.utilities.ConversionHelper;
import java.util.Map;

/**
 * This is a model class for PlaceAutocompleteTerm type.
 */
public class PlaceAutocompleteTerm {
    private String value;
    private double offset;
    private AdditionalProperties<Object> additionalProperties = 
            new AdditionalProperties<Object>(this.getClass());

    /**
     * Default constructor.
     */
    public PlaceAutocompleteTerm() {
    }

    /**
     * Initialization constructor.
     * @param  value  String value for value.
     * @param  offset  double value for offset.
     */
    public PlaceAutocompleteTerm(
            String value,
            double offset) {
        this.value = value;
        this.offset = offset;
    }

    /**
     * Getter for Value.
     * The text of the term.
     * @return Returns the String
     */
    @JsonGetter("value")
    public String getValue() {
        return value;
    }

    /**
     * Setter for Value.
     * The text of the term.
     * @param value Value for String
     */
    @JsonSetter("value")
    public void setValue(String value) {
        this.value = value;
    }

    /**
     * Getter for Offset.
     * Defines the start position of this term in the description, measured in Unicode characters
     * @return Returns the double
     */
    @JsonGetter("offset")
    public double getOffset() {
        return offset;
    }

    /**
     * Setter for Offset.
     * Defines the start position of this term in the description, measured in Unicode characters
     * @param offset Value for double
     */
    @JsonSetter("offset")
    public void setOffset(double offset) {
        this.offset = offset;
    }

    /**
     * Hidden method for the serialization of additional properties.
     * @return The map of additionally set properties.
     */
    @JsonAnyGetter
    private Map<String, Object> getAdditionalProperties() {
        return additionalProperties.getAdditionalProperties();
    }

    /**
     * Hidden method for the de-serialization of additional properties.
     * @param name The name of the additional property.
     * @param value The Object value of the additional property.
     */
    @JsonAnySetter
    private void setAdditionalProperties(String name, Object value) {
        additionalProperties.setAdditionalProperty(name,
                ConversionHelper.convertToSimpleType(value,
                        x -> x),
                true);
    }

    /**
     * Getter for the value of additional properties based on provided property name.
     * @param name The name of the additional property.
     * @return Either the Object property value or null if not exist.
     */
    
    public Object getAdditionalProperty(String name) {
        return additionalProperties.getAdditionalProperty(name);
    }

    /**
     * Converts this PlaceAutocompleteTerm into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "PlaceAutocompleteTerm [" + "value=" + value + ", offset=" + offset
                + ", additionalProperties=" + additionalProperties + "]";
    }

    /**
     * Builds a new {@link PlaceAutocompleteTerm.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link PlaceAutocompleteTerm.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(value, offset);
        builder.additionalProperties = additionalProperties;
        return builder;
    }

    /**
     * Class to build instances of {@link PlaceAutocompleteTerm}.
     */
    public static class Builder {
        private String value;
        private double offset;
        private AdditionalProperties<Object> additionalProperties =
                new AdditionalProperties<Object>();

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  value  String value for value.
         * @param  offset  double value for offset.
         */
        public Builder(String value, double offset) {
            this.value = value;
            this.offset = offset;
        }

        /**
         * Setter for value.
         * @param  value  String value for value.
         * @return Builder
         */
        public Builder value(String value) {
            this.value = value;
            return this;
        }

        /**
         * Setter for offset.
         * @param  offset  double value for offset.
         * @return Builder
         */
        public Builder offset(double offset) {
            this.offset = offset;
            return this;
        }

        /**
         * Setter for additional property that are not in model fields.
         * @param name The name of the additional property.
         * @param value The Object value of the additional property.
         * @return Builder.
         */
        public Builder additionalProperty(String name, Object value) {
            this.additionalProperties.setAdditionalProperty(name, value);
            return this;
        }

        /**
         * Builds a new {@link PlaceAutocompleteTerm} object using the set fields.
         * @return {@link PlaceAutocompleteTerm}
         */
        public PlaceAutocompleteTerm build() {
            PlaceAutocompleteTerm model =
                    new PlaceAutocompleteTerm(value, offset);
            model.additionalProperties = additionalProperties;
            return model;
        }
    }
}
