/*
 * GoogleMapsPlatformLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.googleapis.www.models;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.AdditionalProperties;
import io.apimatic.core.utilities.ConversionHelper;
import java.util.List;
import java.util.Map;

/**
 * This is a model class for PlacesDetailsResponse type.
 */
public class PlacesDetailsResponse {
    private List<String> htmlAttributions;
    private Place result;
    private PlacesDetailsStatus status;
    private List<String> infoMessages;
    private AdditionalProperties<Object> additionalProperties = 
            new AdditionalProperties<Object>(this.getClass());

    /**
     * Default constructor.
     */
    public PlacesDetailsResponse() {
    }

    /**
     * Initialization constructor.
     * @param  htmlAttributions  List of String value for htmlAttributions.
     * @param  result  Place value for result.
     * @param  status  PlacesDetailsStatus value for status.
     * @param  infoMessages  List of String value for infoMessages.
     */
    public PlacesDetailsResponse(
            List<String> htmlAttributions,
            Place result,
            PlacesDetailsStatus status,
            List<String> infoMessages) {
        this.htmlAttributions = htmlAttributions;
        this.result = result;
        this.status = status;
        this.infoMessages = infoMessages;
    }

    /**
     * Getter for HtmlAttributions.
     * May contain a set of attributions about this listing which must be displayed to the user
     * (some listings may not have attribution).
     * @return Returns the List of String
     */
    @JsonGetter("html_attributions")
    public List<String> getHtmlAttributions() {
        return htmlAttributions;
    }

    /**
     * Setter for HtmlAttributions.
     * May contain a set of attributions about this listing which must be displayed to the user
     * (some listings may not have attribution).
     * @param htmlAttributions Value for List of String
     */
    @JsonSetter("html_attributions")
    public void setHtmlAttributions(List<String> htmlAttributions) {
        this.htmlAttributions = htmlAttributions;
    }

    /**
     * Getter for Result.
     * Attributes describing a place. Not all attributes will be available for all place types.
     * @return Returns the Place
     */
    @JsonGetter("result")
    public Place getResult() {
        return result;
    }

    /**
     * Setter for Result.
     * Attributes describing a place. Not all attributes will be available for all place types.
     * @param result Value for Place
     */
    @JsonSetter("result")
    public void setResult(Place result) {
        this.result = result;
    }

    /**
     * Getter for Status.
     * Status codes returned by service. - `OK` indicating the API request was successful. -
     * `ZERO_RESULTS` indicating that the referenced location, `place_id`, was valid but no longer
     * refers to a valid result. This may occur if the establishment is no longer in business. -
     * `NOT_FOUND` indicating that that the referenced location, `place_id`, was not found in the
     * Places database. - `INVALID_REQUEST` indicating the API request was malformed. -
     * `OVER_QUERY_LIMIT` indicating any of the following: - You have exceeded the QPS limits. -
     * Billing has not been enabled on your account. - The monthly $200 credit, or a self-imposed
     * usage cap, has been exceeded. - The provided method of payment is no longer valid (for
     * example, a credit card has expired). See the [Maps
     * FAQ](https://developers.google.com/maps/faq#over-limit-key-error) for more information about
     * how to resolve this error. - `REQUEST_DENIED` indicating that your request was denied,
     * generally because: - The request is missing an API key. - The `key` parameter is invalid. -
     * `UNKNOWN_ERROR` indicating an unknown error.
     * @return Returns the PlacesDetailsStatus
     */
    @JsonGetter("status")
    public PlacesDetailsStatus getStatus() {
        return status;
    }

    /**
     * Setter for Status.
     * Status codes returned by service. - `OK` indicating the API request was successful. -
     * `ZERO_RESULTS` indicating that the referenced location, `place_id`, was valid but no longer
     * refers to a valid result. This may occur if the establishment is no longer in business. -
     * `NOT_FOUND` indicating that that the referenced location, `place_id`, was not found in the
     * Places database. - `INVALID_REQUEST` indicating the API request was malformed. -
     * `OVER_QUERY_LIMIT` indicating any of the following: - You have exceeded the QPS limits. -
     * Billing has not been enabled on your account. - The monthly $200 credit, or a self-imposed
     * usage cap, has been exceeded. - The provided method of payment is no longer valid (for
     * example, a credit card has expired). See the [Maps
     * FAQ](https://developers.google.com/maps/faq#over-limit-key-error) for more information about
     * how to resolve this error. - `REQUEST_DENIED` indicating that your request was denied,
     * generally because: - The request is missing an API key. - The `key` parameter is invalid. -
     * `UNKNOWN_ERROR` indicating an unknown error.
     * @param status Value for PlacesDetailsStatus
     */
    @JsonSetter("status")
    public void setStatus(PlacesDetailsStatus status) {
        this.status = status;
    }

    /**
     * Getter for InfoMessages.
     * When the service returns additional information about the request specification, there may be
     * an additional `info_messages` field within the response object. This field is only returned
     * for successful requests. It may not always be returned, and its content is subject to change.
     * @return Returns the List of String
     */
    @JsonGetter("info_messages")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public List<String> getInfoMessages() {
        return infoMessages;
    }

    /**
     * Setter for InfoMessages.
     * When the service returns additional information about the request specification, there may be
     * an additional `info_messages` field within the response object. This field is only returned
     * for successful requests. It may not always be returned, and its content is subject to change.
     * @param infoMessages Value for List of String
     */
    @JsonSetter("info_messages")
    public void setInfoMessages(List<String> infoMessages) {
        this.infoMessages = infoMessages;
    }

    /**
     * Hidden method for the serialization of additional properties.
     * @return The map of additionally set properties.
     */
    @JsonAnyGetter
    private Map<String, Object> getAdditionalProperties() {
        return additionalProperties.getAdditionalProperties();
    }

    /**
     * Hidden method for the de-serialization of additional properties.
     * @param name The name of the additional property.
     * @param value The Object value of the additional property.
     */
    @JsonAnySetter
    private void setAdditionalProperties(String name, Object value) {
        additionalProperties.setAdditionalProperty(name,
                ConversionHelper.convertToSimpleType(value,
                        x -> x),
                true);
    }

    /**
     * Getter for the value of additional properties based on provided property name.
     * @param name The name of the additional property.
     * @return Either the Object property value or null if not exist.
     */
    
    public Object getAdditionalProperty(String name) {
        return additionalProperties.getAdditionalProperty(name);
    }

    /**
     * Converts this PlacesDetailsResponse into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "PlacesDetailsResponse [" + "htmlAttributions=" + htmlAttributions + ", result="
                + result + ", status=" + status + ", infoMessages=" + infoMessages
                + ", additionalProperties=" + additionalProperties + "]";
    }

    /**
     * Builds a new {@link PlacesDetailsResponse.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link PlacesDetailsResponse.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(htmlAttributions, result, status)
                .infoMessages(getInfoMessages());
        builder.additionalProperties = additionalProperties;
        return builder;
    }

    /**
     * Class to build instances of {@link PlacesDetailsResponse}.
     */
    public static class Builder {
        private List<String> htmlAttributions;
        private Place result;
        private PlacesDetailsStatus status;
        private List<String> infoMessages;
        private AdditionalProperties<Object> additionalProperties =
                new AdditionalProperties<Object>();

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  htmlAttributions  List of String value for htmlAttributions.
         * @param  result  Place value for result.
         * @param  status  PlacesDetailsStatus value for status.
         */
        public Builder(List<String> htmlAttributions, Place result, PlacesDetailsStatus status) {
            this.htmlAttributions = htmlAttributions;
            this.result = result;
            this.status = status;
        }

        /**
         * Setter for htmlAttributions.
         * @param  htmlAttributions  List of String value for htmlAttributions.
         * @return Builder
         */
        public Builder htmlAttributions(List<String> htmlAttributions) {
            this.htmlAttributions = htmlAttributions;
            return this;
        }

        /**
         * Setter for result.
         * @param  result  Place value for result.
         * @return Builder
         */
        public Builder result(Place result) {
            this.result = result;
            return this;
        }

        /**
         * Setter for status.
         * @param  status  PlacesDetailsStatus value for status.
         * @return Builder
         */
        public Builder status(PlacesDetailsStatus status) {
            this.status = status;
            return this;
        }

        /**
         * Setter for infoMessages.
         * @param  infoMessages  List of String value for infoMessages.
         * @return Builder
         */
        public Builder infoMessages(List<String> infoMessages) {
            this.infoMessages = infoMessages;
            return this;
        }

        /**
         * Setter for additional property that are not in model fields.
         * @param name The name of the additional property.
         * @param value The Object value of the additional property.
         * @return Builder.
         */
        public Builder additionalProperty(String name, Object value) {
            this.additionalProperties.setAdditionalProperty(name, value);
            return this;
        }

        /**
         * Builds a new {@link PlacesDetailsResponse} object using the set fields.
         * @return {@link PlacesDetailsResponse}
         */
        public PlacesDetailsResponse build() {
            PlacesDetailsResponse model =
                    new PlacesDetailsResponse(htmlAttributions, result, status, infoMessages);
            model.additionalProperties = additionalProperties;
            return model;
        }
    }
}
