/*
 * GoogleMapsPlatformLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.googleapis.www.models;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.AdditionalProperties;
import io.apimatic.core.utilities.ConversionHelper;
import java.util.List;
import java.util.Map;

/**
 * This is a model class for PlacesFindPlaceFromTextResponse type.
 */
public class PlacesFindPlaceFromTextResponse {
    private List<Place> candidates;
    private PlacesSearchStatus status;
    private String errorMessage;
    private List<String> infoMessages;
    private AdditionalProperties<Object> additionalProperties = 
            new AdditionalProperties<Object>(this.getClass());

    /**
     * Default constructor.
     */
    public PlacesFindPlaceFromTextResponse() {
    }

    /**
     * Initialization constructor.
     * @param  candidates  List of Place value for candidates.
     * @param  status  PlacesSearchStatus value for status.
     * @param  errorMessage  String value for errorMessage.
     * @param  infoMessages  List of String value for infoMessages.
     */
    public PlacesFindPlaceFromTextResponse(
            List<Place> candidates,
            PlacesSearchStatus status,
            String errorMessage,
            List<String> infoMessages) {
        this.candidates = candidates;
        this.status = status;
        this.errorMessage = errorMessage;
        this.infoMessages = infoMessages;
    }

    /**
     * Getter for Candidates.
     * Contains an array of Place candidates. &lt;div class="caution"&gt;Place Search requests return a
     * subset of the fields that are returned by Place Details requests. If the field you want is
     * not returned by Place Search, you can use Place Search to get a place_id, then use that Place
     * ID to make a Place Details request.&lt;/div&gt;
     * @return Returns the List of Place
     */
    @JsonGetter("candidates")
    public List<Place> getCandidates() {
        return candidates;
    }

    /**
     * Setter for Candidates.
     * Contains an array of Place candidates. &lt;div class="caution"&gt;Place Search requests return a
     * subset of the fields that are returned by Place Details requests. If the field you want is
     * not returned by Place Search, you can use Place Search to get a place_id, then use that Place
     * ID to make a Place Details request.&lt;/div&gt;
     * @param candidates Value for List of Place
     */
    @JsonSetter("candidates")
    public void setCandidates(List<Place> candidates) {
        this.candidates = candidates;
    }

    /**
     * Getter for Status.
     * Status codes returned by service. - `OK` indicating the API request was successful. -
     * `ZERO_RESULTS` indicating that the search was successful but returned no results. This may
     * occur if the search was passed a `latlng` in a remote location. - `INVALID_REQUEST`
     * indicating the API request was malformed, generally due to missing required query parameter
     * (`location` or `radius`). - `OVER_QUERY_LIMIT` indicating any of the following: - You have
     * exceeded the QPS limits. - Billing has not been enabled on your account. - The monthly $200
     * credit, or a self-imposed usage cap, has been exceeded. - The provided method of payment is
     * no longer valid (for example, a credit card has expired). See the [Maps
     * FAQ](https://developers.google.com/maps/faq#over-limit-key-error) for more information about
     * how to resolve this error. - `REQUEST_DENIED` indicating that your request was denied,
     * generally because: - The request is missing an API key. - The `key` parameter is invalid. -
     * `UNKNOWN_ERROR` indicating an unknown error.
     * @return Returns the PlacesSearchStatus
     */
    @JsonGetter("status")
    public PlacesSearchStatus getStatus() {
        return status;
    }

    /**
     * Setter for Status.
     * Status codes returned by service. - `OK` indicating the API request was successful. -
     * `ZERO_RESULTS` indicating that the search was successful but returned no results. This may
     * occur if the search was passed a `latlng` in a remote location. - `INVALID_REQUEST`
     * indicating the API request was malformed, generally due to missing required query parameter
     * (`location` or `radius`). - `OVER_QUERY_LIMIT` indicating any of the following: - You have
     * exceeded the QPS limits. - Billing has not been enabled on your account. - The monthly $200
     * credit, or a self-imposed usage cap, has been exceeded. - The provided method of payment is
     * no longer valid (for example, a credit card has expired). See the [Maps
     * FAQ](https://developers.google.com/maps/faq#over-limit-key-error) for more information about
     * how to resolve this error. - `REQUEST_DENIED` indicating that your request was denied,
     * generally because: - The request is missing an API key. - The `key` parameter is invalid. -
     * `UNKNOWN_ERROR` indicating an unknown error.
     * @param status Value for PlacesSearchStatus
     */
    @JsonSetter("status")
    public void setStatus(PlacesSearchStatus status) {
        this.status = status;
    }

    /**
     * Getter for ErrorMessage.
     * When the service returns a status code other than `OK&lt;`, there may be an additional
     * `error_message` field within the response object. This field contains more detailed
     * information about thereasons behind the given status code. This field is not always returned,
     * and its content is subject to change.
     * @return Returns the String
     */
    @JsonGetter("error_message")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getErrorMessage() {
        return errorMessage;
    }

    /**
     * Setter for ErrorMessage.
     * When the service returns a status code other than `OK&lt;`, there may be an additional
     * `error_message` field within the response object. This field contains more detailed
     * information about thereasons behind the given status code. This field is not always returned,
     * and its content is subject to change.
     * @param errorMessage Value for String
     */
    @JsonSetter("error_message")
    public void setErrorMessage(String errorMessage) {
        this.errorMessage = errorMessage;
    }

    /**
     * Getter for InfoMessages.
     * When the service returns additional information about the request specification, there may be
     * an additional `info_messages` field within the response object. This field is only returned
     * for successful requests. It may not always be returned, and its content is subject to change.
     * @return Returns the List of String
     */
    @JsonGetter("info_messages")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public List<String> getInfoMessages() {
        return infoMessages;
    }

    /**
     * Setter for InfoMessages.
     * When the service returns additional information about the request specification, there may be
     * an additional `info_messages` field within the response object. This field is only returned
     * for successful requests. It may not always be returned, and its content is subject to change.
     * @param infoMessages Value for List of String
     */
    @JsonSetter("info_messages")
    public void setInfoMessages(List<String> infoMessages) {
        this.infoMessages = infoMessages;
    }

    /**
     * Hidden method for the serialization of additional properties.
     * @return The map of additionally set properties.
     */
    @JsonAnyGetter
    private Map<String, Object> getAdditionalProperties() {
        return additionalProperties.getAdditionalProperties();
    }

    /**
     * Hidden method for the de-serialization of additional properties.
     * @param name The name of the additional property.
     * @param value The Object value of the additional property.
     */
    @JsonAnySetter
    private void setAdditionalProperties(String name, Object value) {
        additionalProperties.setAdditionalProperty(name,
                ConversionHelper.convertToSimpleType(value,
                        x -> x),
                true);
    }

    /**
     * Getter for the value of additional properties based on provided property name.
     * @param name The name of the additional property.
     * @return Either the Object property value or null if not exist.
     */
    
    public Object getAdditionalProperty(String name) {
        return additionalProperties.getAdditionalProperty(name);
    }

    /**
     * Converts this PlacesFindPlaceFromTextResponse into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "PlacesFindPlaceFromTextResponse [" + "candidates=" + candidates + ", status="
                + status + ", errorMessage=" + errorMessage + ", infoMessages=" + infoMessages
                + ", additionalProperties=" + additionalProperties + "]";
    }

    /**
     * Builds a new {@link PlacesFindPlaceFromTextResponse.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link PlacesFindPlaceFromTextResponse.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(candidates, status)
                .errorMessage(getErrorMessage())
                .infoMessages(getInfoMessages());
        builder.additionalProperties = additionalProperties;
        return builder;
    }

    /**
     * Class to build instances of {@link PlacesFindPlaceFromTextResponse}.
     */
    public static class Builder {
        private List<Place> candidates;
        private PlacesSearchStatus status;
        private String errorMessage;
        private List<String> infoMessages;
        private AdditionalProperties<Object> additionalProperties =
                new AdditionalProperties<Object>();

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  candidates  List of Place value for candidates.
         * @param  status  PlacesSearchStatus value for status.
         */
        public Builder(List<Place> candidates, PlacesSearchStatus status) {
            this.candidates = candidates;
            this.status = status;
        }

        /**
         * Setter for candidates.
         * @param  candidates  List of Place value for candidates.
         * @return Builder
         */
        public Builder candidates(List<Place> candidates) {
            this.candidates = candidates;
            return this;
        }

        /**
         * Setter for status.
         * @param  status  PlacesSearchStatus value for status.
         * @return Builder
         */
        public Builder status(PlacesSearchStatus status) {
            this.status = status;
            return this;
        }

        /**
         * Setter for errorMessage.
         * @param  errorMessage  String value for errorMessage.
         * @return Builder
         */
        public Builder errorMessage(String errorMessage) {
            this.errorMessage = errorMessage;
            return this;
        }

        /**
         * Setter for infoMessages.
         * @param  infoMessages  List of String value for infoMessages.
         * @return Builder
         */
        public Builder infoMessages(List<String> infoMessages) {
            this.infoMessages = infoMessages;
            return this;
        }

        /**
         * Setter for additional property that are not in model fields.
         * @param name The name of the additional property.
         * @param value The Object value of the additional property.
         * @return Builder.
         */
        public Builder additionalProperty(String name, Object value) {
            this.additionalProperties.setAdditionalProperty(name, value);
            return this;
        }

        /**
         * Builds a new {@link PlacesFindPlaceFromTextResponse} object using the set fields.
         * @return {@link PlacesFindPlaceFromTextResponse}
         */
        public PlacesFindPlaceFromTextResponse build() {
            PlacesFindPlaceFromTextResponse model =
                    new PlacesFindPlaceFromTextResponse(candidates, status, errorMessage,
                            infoMessages);
            model.additionalProperties = additionalProperties;
            return model;
        }
    }
}
