/*
 * GoogleMapsPlatformLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.googleapis.www.models;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.AdditionalProperties;
import io.apimatic.core.utilities.ConversionHelper;
import java.util.Map;

/**
 * This is a model class for PlaceAutocompleteMatchedSubstring type.
 */
public class PlaceAutocompleteMatchedSubstring {
    private double length;
    private double offset;
    private AdditionalProperties<Object> additionalProperties = 
            new AdditionalProperties<Object>(this.getClass());

    /**
     * Default constructor.
     */
    public PlaceAutocompleteMatchedSubstring() {
    }

    /**
     * Initialization constructor.
     * @param  length  double value for length.
     * @param  offset  double value for offset.
     */
    public PlaceAutocompleteMatchedSubstring(
            double length,
            double offset) {
        this.length = length;
        this.offset = offset;
    }

    /**
     * Getter for Length.
     * Length of the matched substring in the prediction result text.
     * @return Returns the double
     */
    @JsonGetter("length")
    public double getLength() {
        return length;
    }

    /**
     * Setter for Length.
     * Length of the matched substring in the prediction result text.
     * @param length Value for double
     */
    @JsonSetter("length")
    public void setLength(double length) {
        this.length = length;
    }

    /**
     * Getter for Offset.
     * Start location of the matched substring in the prediction result text.
     * @return Returns the double
     */
    @JsonGetter("offset")
    public double getOffset() {
        return offset;
    }

    /**
     * Setter for Offset.
     * Start location of the matched substring in the prediction result text.
     * @param offset Value for double
     */
    @JsonSetter("offset")
    public void setOffset(double offset) {
        this.offset = offset;
    }

    /**
     * Hidden method for the serialization of additional properties.
     * @return The map of additionally set properties.
     */
    @JsonAnyGetter
    private Map<String, Object> getAdditionalProperties() {
        return additionalProperties.getAdditionalProperties();
    }

    /**
     * Hidden method for the de-serialization of additional properties.
     * @param name The name of the additional property.
     * @param value The Object value of the additional property.
     */
    @JsonAnySetter
    private void setAdditionalProperties(String name, Object value) {
        additionalProperties.setAdditionalProperty(name,
                ConversionHelper.convertToSimpleType(value,
                        x -> x),
                true);
    }

    /**
     * Getter for the value of additional properties based on provided property name.
     * @param name The name of the additional property.
     * @return Either the Object property value or null if not exist.
     */
    
    public Object getAdditionalProperty(String name) {
        return additionalProperties.getAdditionalProperty(name);
    }

    /**
     * Converts this PlaceAutocompleteMatchedSubstring into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "PlaceAutocompleteMatchedSubstring [" + "length=" + length + ", offset=" + offset
                + ", additionalProperties=" + additionalProperties + "]";
    }

    /**
     * Builds a new {@link PlaceAutocompleteMatchedSubstring.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link PlaceAutocompleteMatchedSubstring.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(length, offset);
        builder.additionalProperties = additionalProperties;
        return builder;
    }

    /**
     * Class to build instances of {@link PlaceAutocompleteMatchedSubstring}.
     */
    public static class Builder {
        private double length;
        private double offset;
        private AdditionalProperties<Object> additionalProperties =
                new AdditionalProperties<Object>();

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  length  double value for length.
         * @param  offset  double value for offset.
         */
        public Builder(double length, double offset) {
            this.length = length;
            this.offset = offset;
        }

        /**
         * Setter for length.
         * @param  length  double value for length.
         * @return Builder
         */
        public Builder length(double length) {
            this.length = length;
            return this;
        }

        /**
         * Setter for offset.
         * @param  offset  double value for offset.
         * @return Builder
         */
        public Builder offset(double offset) {
            this.offset = offset;
            return this;
        }

        /**
         * Setter for additional property that are not in model fields.
         * @param name The name of the additional property.
         * @param value The Object value of the additional property.
         * @return Builder.
         */
        public Builder additionalProperty(String name, Object value) {
            this.additionalProperties.setAdditionalProperty(name, value);
            return this;
        }

        /**
         * Builds a new {@link PlaceAutocompleteMatchedSubstring} object using the set fields.
         * @return {@link PlaceAutocompleteMatchedSubstring}
         */
        public PlaceAutocompleteMatchedSubstring build() {
            PlaceAutocompleteMatchedSubstring model =
                    new PlaceAutocompleteMatchedSubstring(length, offset);
            model.additionalProperties = additionalProperties;
            return model;
        }
    }
}
