/*
 * GoogleMapsPlatformLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.googleapis.www.models;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.TreeMap;


/**
 * PlacesDetailsStatus to be used.
 */
public enum PlacesDetailsStatus {
    OK,

    ZERO_RESULTS,

    INVALID_REQUEST,

    NOT_FOUND,

    OVER_QUERY_LIMIT,

    REQUEST_DENIED,

    UNKNOWN_ERROR;


    private static TreeMap<String, PlacesDetailsStatus> valueMap = new TreeMap<>();
    private String value;

    static {
        OK.value = "OK";
        ZERO_RESULTS.value = "ZERO_RESULTS";
        INVALID_REQUEST.value = "INVALID_REQUEST";
        NOT_FOUND.value = "NOT_FOUND";
        OVER_QUERY_LIMIT.value = "OVER_QUERY_LIMIT";
        REQUEST_DENIED.value = "REQUEST_DENIED";
        UNKNOWN_ERROR.value = "UNKNOWN_ERROR";

        valueMap.put("OK", OK);
        valueMap.put("ZERO_RESULTS", ZERO_RESULTS);
        valueMap.put("INVALID_REQUEST", INVALID_REQUEST);
        valueMap.put("NOT_FOUND", NOT_FOUND);
        valueMap.put("OVER_QUERY_LIMIT", OVER_QUERY_LIMIT);
        valueMap.put("REQUEST_DENIED", REQUEST_DENIED);
        valueMap.put("UNKNOWN_ERROR", UNKNOWN_ERROR);
    }

    /**
     * Returns the enum member associated with the given string value.
     * @param toConvert String value to get enum member.
     * @return The enum member against the given string value.
     * @throws IOException when provided value is not mapped to any enum member.
     */
    @JsonCreator
    public static PlacesDetailsStatus constructFromString(String toConvert) throws IOException {
        PlacesDetailsStatus enumValue = fromString(toConvert);
        if (enumValue == null) {
            throw new IOException("Unable to create enum instance with value: " + toConvert);
        }
        return enumValue;
    }

    /**
     * Returns the enum member associated with the given string value.
     * @param toConvert String value to get enum member.
     * @return The enum member against the given string value.
     */
    public static PlacesDetailsStatus fromString(String toConvert) {
        return valueMap.get(toConvert);
    }

    /**
     * Returns the string value associated with the enum member.
     * @return The string value against enum member.
     */
    @JsonValue
    public String value() {
        return value;
    }
        
    /**
     * Get string representation of this enum.
     */
    @Override
    public String toString() {
        return value.toString();
    }

    /**
     * Convert list of PlacesDetailsStatus values to list of string values.
     * @param toConvert The list of PlacesDetailsStatus values to convert.
     * @return List of representative string values.
     */
    public static List<String> toValue(List<PlacesDetailsStatus> toConvert) {
        if (toConvert == null) {
            return null;
        }
        List<String> convertedValues = new ArrayList<>();
        for (PlacesDetailsStatus enumValue : toConvert) {
            convertedValues.add(enumValue.value);
        }
        return convertedValues;
    }
} 