/*
 * GoogleMapsPlatformLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.googleapis.www.models;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.AdditionalProperties;
import io.apimatic.core.utilities.ConversionHelper;
import java.util.Map;

/**
 * This is a model class for PlusCode type.
 */
public class PlusCode {
    private String compoundCode;
    private String globalCode;
    private AdditionalProperties<Object> additionalProperties = 
            new AdditionalProperties<Object>(this.getClass());

    /**
     * Default constructor.
     */
    public PlusCode() {
    }

    /**
     * Initialization constructor.
     * @param  globalCode  String value for globalCode.
     * @param  compoundCode  String value for compoundCode.
     */
    public PlusCode(
            String globalCode,
            String compoundCode) {
        this.compoundCode = compoundCode;
        this.globalCode = globalCode;
    }

    /**
     * Getter for CompoundCode.
     * The `compound_code` is a 6 character or longer local code with an explicit location
     * (`CWC8+R9, Mountain View, CA, USA`). Some APIs may return an empty string if the
     * `compound_code` is not available.
     * @return Returns the String
     */
    @JsonGetter("compound_code")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getCompoundCode() {
        return compoundCode;
    }

    /**
     * Setter for CompoundCode.
     * The `compound_code` is a 6 character or longer local code with an explicit location
     * (`CWC8+R9, Mountain View, CA, USA`). Some APIs may return an empty string if the
     * `compound_code` is not available.
     * @param compoundCode Value for String
     */
    @JsonSetter("compound_code")
    public void setCompoundCode(String compoundCode) {
        this.compoundCode = compoundCode;
    }

    /**
     * Getter for GlobalCode.
     * The `global_code` is a 4 character area code and 6 character or longer local code
     * (`849VCWC8+R9`).
     * @return Returns the String
     */
    @JsonGetter("global_code")
    public String getGlobalCode() {
        return globalCode;
    }

    /**
     * Setter for GlobalCode.
     * The `global_code` is a 4 character area code and 6 character or longer local code
     * (`849VCWC8+R9`).
     * @param globalCode Value for String
     */
    @JsonSetter("global_code")
    public void setGlobalCode(String globalCode) {
        this.globalCode = globalCode;
    }

    /**
     * Hidden method for the serialization of additional properties.
     * @return The map of additionally set properties.
     */
    @JsonAnyGetter
    private Map<String, Object> getAdditionalProperties() {
        return additionalProperties.getAdditionalProperties();
    }

    /**
     * Hidden method for the de-serialization of additional properties.
     * @param name The name of the additional property.
     * @param value The Object value of the additional property.
     */
    @JsonAnySetter
    private void setAdditionalProperties(String name, Object value) {
        additionalProperties.setAdditionalProperty(name,
                ConversionHelper.convertToSimpleType(value,
                        x -> x),
                true);
    }

    /**
     * Getter for the value of additional properties based on provided property name.
     * @param name The name of the additional property.
     * @return Either the Object property value or null if not exist.
     */
    
    public Object getAdditionalProperty(String name) {
        return additionalProperties.getAdditionalProperty(name);
    }

    /**
     * Converts this PlusCode into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "PlusCode [" + "globalCode=" + globalCode + ", compoundCode=" + compoundCode
                + ", additionalProperties=" + additionalProperties + "]";
    }

    /**
     * Builds a new {@link PlusCode.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link PlusCode.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(globalCode)
                .compoundCode(getCompoundCode());
        builder.additionalProperties = additionalProperties;
        return builder;
    }

    /**
     * Class to build instances of {@link PlusCode}.
     */
    public static class Builder {
        private String globalCode;
        private String compoundCode;
        private AdditionalProperties<Object> additionalProperties =
                new AdditionalProperties<Object>();

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  globalCode  String value for globalCode.
         */
        public Builder(String globalCode) {
            this.globalCode = globalCode;
        }

        /**
         * Setter for globalCode.
         * @param  globalCode  String value for globalCode.
         * @return Builder
         */
        public Builder globalCode(String globalCode) {
            this.globalCode = globalCode;
            return this;
        }

        /**
         * Setter for compoundCode.
         * @param  compoundCode  String value for compoundCode.
         * @return Builder
         */
        public Builder compoundCode(String compoundCode) {
            this.compoundCode = compoundCode;
            return this;
        }

        /**
         * Setter for additional property that are not in model fields.
         * @param name The name of the additional property.
         * @param value The Object value of the additional property.
         * @return Builder.
         */
        public Builder additionalProperty(String name, Object value) {
            this.additionalProperties.setAdditionalProperty(name, value);
            return this;
        }

        /**
         * Builds a new {@link PlusCode} object using the set fields.
         * @return {@link PlusCode}
         */
        public PlusCode build() {
            PlusCode model =
                    new PlusCode(globalCode, compoundCode);
            model.additionalProperties = additionalProperties;
            return model;
        }
    }
}
