/*
 * GoogleMapsPlatformLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.googleapis.www.authentication;

/**
 * A data class for Custom Query Parameter credentials.
 */
public class CustomQueryAuthenticationModel {
    private String key;

    /**
     * A Constructor for CustomQueryAuthenticationModel.
     */
    private CustomQueryAuthenticationModel(String key) {
        this.key = key;
    }

    /**
     * Getter for key.
     * @return key The value of key.
     */
    public String getKey() {
        return this.key;
    }

    /**
     * Builds a new {@link CustomQueryAuthenticationModel.Builder} object.
     * Creates the instance with the state of the current auth model.
     * @return a new {@link CustomQueryAuthenticationModel.Builder} object.
     */
    public Builder toBuilder() {
        return new Builder(getKey());
    }

    /**
     * A Builder class for Custom Query Parameter credentials.
     */
    public static class Builder {
        private String key;

        /**
         * The constructor with required auth credentials.
         * @param key The value of Key.
         */
        public Builder(String key) {
            if (key == null) {
                throw new NullPointerException("Key cannot be null.");
            }

            this.key = key;
        }

        /**
         * Setter for key.
         * @param key The value of key.
         * @return Builder The current instance of Builder.
         */
        public Builder key(String key) {
            if (key == null) {
                throw new NullPointerException("Key cannot be null.");
            }

            this.key = key;
            return this;
        }

        /**
         * Builds the instance of CustomQueryAuthenticationModel using the provided credentials.
         * @return The instance of CustomQueryAuthenticationModel.
         */
        public CustomQueryAuthenticationModel build() {
            return new CustomQueryAuthenticationModel(key);
        }
    }
}