/*
 * GoogleMapsPlatformLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.googleapis.maps.models;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.AdditionalProperties;
import io.apimatic.core.utilities.ConversionHelper;
import java.util.Map;

/**
 * This is a model class for Bounds type.
 */
public class Bounds {
    private LatLngLiteral northeast;
    private LatLngLiteral southwest;
    private AdditionalProperties<Object> additionalProperties = 
            new AdditionalProperties<Object>(this.getClass());

    /**
     * Default constructor.
     */
    public Bounds() {
    }

    /**
     * Initialization constructor.
     * @param  northeast  LatLngLiteral value for northeast.
     * @param  southwest  LatLngLiteral value for southwest.
     */
    public Bounds(
            LatLngLiteral northeast,
            LatLngLiteral southwest) {
        this.northeast = northeast;
        this.southwest = southwest;
    }

    /**
     * Getter for Northeast.
     * An object describing a specific location with Latitude and Longitude in decimal degrees.
     * @return Returns the LatLngLiteral
     */
    @JsonGetter("northeast")
    public LatLngLiteral getNortheast() {
        return northeast;
    }

    /**
     * Setter for Northeast.
     * An object describing a specific location with Latitude and Longitude in decimal degrees.
     * @param northeast Value for LatLngLiteral
     */
    @JsonSetter("northeast")
    public void setNortheast(LatLngLiteral northeast) {
        this.northeast = northeast;
    }

    /**
     * Getter for Southwest.
     * An object describing a specific location with Latitude and Longitude in decimal degrees.
     * @return Returns the LatLngLiteral
     */
    @JsonGetter("southwest")
    public LatLngLiteral getSouthwest() {
        return southwest;
    }

    /**
     * Setter for Southwest.
     * An object describing a specific location with Latitude and Longitude in decimal degrees.
     * @param southwest Value for LatLngLiteral
     */
    @JsonSetter("southwest")
    public void setSouthwest(LatLngLiteral southwest) {
        this.southwest = southwest;
    }

    /**
     * Hidden method for the serialization of additional properties.
     * @return The map of additionally set properties.
     */
    @JsonAnyGetter
    private Map<String, Object> getAdditionalProperties() {
        return additionalProperties.getAdditionalProperties();
    }

    /**
     * Hidden method for the de-serialization of additional properties.
     * @param name The name of the additional property.
     * @param value The Object value of the additional property.
     */
    @JsonAnySetter
    private void setAdditionalProperties(String name, Object value) {
        additionalProperties.setAdditionalProperty(name,
                ConversionHelper.convertToSimpleType(value,
                        x -> x),
                true);
    }

    /**
     * Getter for the value of additional properties based on provided property name.
     * @param name The name of the additional property.
     * @return Either the Object property value or null if not exist.
     */
    
    public Object getAdditionalProperty(String name) {
        return additionalProperties.getAdditionalProperty(name);
    }

    /**
     * Converts this Bounds into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "Bounds [" + "northeast=" + northeast + ", southwest=" + southwest
                + ", additionalProperties=" + additionalProperties + "]";
    }

    /**
     * Builds a new {@link Bounds.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link Bounds.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(northeast, southwest);
        builder.additionalProperties = additionalProperties;
        return builder;
    }

    /**
     * Class to build instances of {@link Bounds}.
     */
    public static class Builder {
        private LatLngLiteral northeast;
        private LatLngLiteral southwest;
        private AdditionalProperties<Object> additionalProperties =
                new AdditionalProperties<Object>();

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  northeast  LatLngLiteral value for northeast.
         * @param  southwest  LatLngLiteral value for southwest.
         */
        public Builder(LatLngLiteral northeast, LatLngLiteral southwest) {
            this.northeast = northeast;
            this.southwest = southwest;
        }

        /**
         * Setter for northeast.
         * @param  northeast  LatLngLiteral value for northeast.
         * @return Builder
         */
        public Builder northeast(LatLngLiteral northeast) {
            this.northeast = northeast;
            return this;
        }

        /**
         * Setter for southwest.
         * @param  southwest  LatLngLiteral value for southwest.
         * @return Builder
         */
        public Builder southwest(LatLngLiteral southwest) {
            this.southwest = southwest;
            return this;
        }

        /**
         * Setter for additional property that are not in model fields.
         * @param name The name of the additional property.
         * @param value The Object value of the additional property.
         * @return Builder.
         */
        public Builder additionalProperty(String name, Object value) {
            this.additionalProperties.setAdditionalProperty(name, value);
            return this;
        }

        /**
         * Builds a new {@link Bounds} object using the set fields.
         * @return {@link Bounds}
         */
        public Bounds build() {
            Bounds model =
                    new Bounds(northeast, southwest);
            model.additionalProperties = additionalProperties;
            return model;
        }
    }
}
