/*
 * GoogleMapsPlatformLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.googleapis.maps.models;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.AdditionalProperties;
import io.apimatic.core.utilities.ConversionHelper;
import java.util.Map;

/**
 * This is a model class for CellTower type.
 */
public class CellTower {
    private int cellId;
    private int locationAreaCode;
    private int mobileCountryCode;
    private int mobileNetworkCode;
    private Integer age;
    private Double signalStrength;
    private Double timingAdvance;
    private AdditionalProperties<Object> additionalProperties = 
            new AdditionalProperties<Object>(this.getClass());

    /**
     * Default constructor.
     */
    public CellTower() {
    }

    /**
     * Initialization constructor.
     * @param  cellId  int value for cellId.
     * @param  locationAreaCode  int value for locationAreaCode.
     * @param  mobileCountryCode  int value for mobileCountryCode.
     * @param  mobileNetworkCode  int value for mobileNetworkCode.
     * @param  age  Integer value for age.
     * @param  signalStrength  Double value for signalStrength.
     * @param  timingAdvance  Double value for timingAdvance.
     */
    public CellTower(
            int cellId,
            int locationAreaCode,
            int mobileCountryCode,
            int mobileNetworkCode,
            Integer age,
            Double signalStrength,
            Double timingAdvance) {
        this.cellId = cellId;
        this.locationAreaCode = locationAreaCode;
        this.mobileCountryCode = mobileCountryCode;
        this.mobileNetworkCode = mobileNetworkCode;
        this.age = age;
        this.signalStrength = signalStrength;
        this.timingAdvance = timingAdvance;
    }

    /**
     * Getter for CellId.
     * Unique identifier of the cell. On GSM, this is the Cell ID (CID); CDMA networks use the Base
     * Station ID (BID). WCDMA networks use the UTRAN/GERAN Cell Identity (UC-Id), which is a 32-bit
     * value concatenating the Radio Network Controller (RNC) and Cell ID. Specifying only the
     * 16-bit Cell ID value in WCDMA networks may return inaccurate results.
     * @return Returns the int
     */
    @JsonGetter("cellId")
    public int getCellId() {
        return cellId;
    }

    /**
     * Setter for CellId.
     * Unique identifier of the cell. On GSM, this is the Cell ID (CID); CDMA networks use the Base
     * Station ID (BID). WCDMA networks use the UTRAN/GERAN Cell Identity (UC-Id), which is a 32-bit
     * value concatenating the Radio Network Controller (RNC) and Cell ID. Specifying only the
     * 16-bit Cell ID value in WCDMA networks may return inaccurate results.
     * @param cellId Value for int
     */
    @JsonSetter("cellId")
    public void setCellId(int cellId) {
        this.cellId = cellId;
    }

    /**
     * Getter for LocationAreaCode.
     * The Location Area Code (LAC) for GSM and WCDMA networks. The Network ID (NID) for CDMA
     * networks.
     * @return Returns the int
     */
    @JsonGetter("locationAreaCode")
    public int getLocationAreaCode() {
        return locationAreaCode;
    }

    /**
     * Setter for LocationAreaCode.
     * The Location Area Code (LAC) for GSM and WCDMA networks. The Network ID (NID) for CDMA
     * networks.
     * @param locationAreaCode Value for int
     */
    @JsonSetter("locationAreaCode")
    public void setLocationAreaCode(int locationAreaCode) {
        this.locationAreaCode = locationAreaCode;
    }

    /**
     * Getter for MobileCountryCode.
     * The cell tower's Mobile Country Code (MCC).
     * @return Returns the int
     */
    @JsonGetter("mobileCountryCode")
    public int getMobileCountryCode() {
        return mobileCountryCode;
    }

    /**
     * Setter for MobileCountryCode.
     * The cell tower's Mobile Country Code (MCC).
     * @param mobileCountryCode Value for int
     */
    @JsonSetter("mobileCountryCode")
    public void setMobileCountryCode(int mobileCountryCode) {
        this.mobileCountryCode = mobileCountryCode;
    }

    /**
     * Getter for MobileNetworkCode.
     * The cell tower's Mobile Network Code. This is the MNC for GSM and WCDMA; CDMA uses the System
     * ID (SID).
     * @return Returns the int
     */
    @JsonGetter("mobileNetworkCode")
    public int getMobileNetworkCode() {
        return mobileNetworkCode;
    }

    /**
     * Setter for MobileNetworkCode.
     * The cell tower's Mobile Network Code. This is the MNC for GSM and WCDMA; CDMA uses the System
     * ID (SID).
     * @param mobileNetworkCode Value for int
     */
    @JsonSetter("mobileNetworkCode")
    public void setMobileNetworkCode(int mobileNetworkCode) {
        this.mobileNetworkCode = mobileNetworkCode;
    }

    /**
     * Getter for Age.
     * The number of milliseconds since this cell was primary. If age is 0, the cellId represents a
     * current measurement.
     * @return Returns the Integer
     */
    @JsonGetter("age")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Integer getAge() {
        return age;
    }

    /**
     * Setter for Age.
     * The number of milliseconds since this cell was primary. If age is 0, the cellId represents a
     * current measurement.
     * @param age Value for Integer
     */
    @JsonSetter("age")
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * Getter for SignalStrength.
     * Radio signal strength measured in dBm.
     * @return Returns the Double
     */
    @JsonGetter("signalStrength")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Double getSignalStrength() {
        return signalStrength;
    }

    /**
     * Setter for SignalStrength.
     * Radio signal strength measured in dBm.
     * @param signalStrength Value for Double
     */
    @JsonSetter("signalStrength")
    public void setSignalStrength(Double signalStrength) {
        this.signalStrength = signalStrength;
    }

    /**
     * Getter for TimingAdvance.
     * The timing advance value.
     * @return Returns the Double
     */
    @JsonGetter("timingAdvance")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Double getTimingAdvance() {
        return timingAdvance;
    }

    /**
     * Setter for TimingAdvance.
     * The timing advance value.
     * @param timingAdvance Value for Double
     */
    @JsonSetter("timingAdvance")
    public void setTimingAdvance(Double timingAdvance) {
        this.timingAdvance = timingAdvance;
    }

    /**
     * Hidden method for the serialization of additional properties.
     * @return The map of additionally set properties.
     */
    @JsonAnyGetter
    private Map<String, Object> getAdditionalProperties() {
        return additionalProperties.getAdditionalProperties();
    }

    /**
     * Hidden method for the de-serialization of additional properties.
     * @param name The name of the additional property.
     * @param value The Object value of the additional property.
     */
    @JsonAnySetter
    private void setAdditionalProperties(String name, Object value) {
        additionalProperties.setAdditionalProperty(name,
                ConversionHelper.convertToSimpleType(value,
                        x -> x),
                true);
    }

    /**
     * Getter for the value of additional properties based on provided property name.
     * @param name The name of the additional property.
     * @return Either the Object property value or null if not exist.
     */
    
    public Object getAdditionalProperty(String name) {
        return additionalProperties.getAdditionalProperty(name);
    }

    /**
     * Converts this CellTower into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "CellTower [" + "cellId=" + cellId + ", locationAreaCode=" + locationAreaCode
                + ", mobileCountryCode=" + mobileCountryCode + ", mobileNetworkCode="
                + mobileNetworkCode + ", age=" + age + ", signalStrength=" + signalStrength
                + ", timingAdvance=" + timingAdvance + ", additionalProperties="
                + additionalProperties + "]";
    }

    /**
     * Builds a new {@link CellTower.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link CellTower.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(cellId, locationAreaCode, mobileCountryCode,
                mobileNetworkCode)
                .age(getAge())
                .signalStrength(getSignalStrength())
                .timingAdvance(getTimingAdvance());
        builder.additionalProperties = additionalProperties;
        return builder;
    }

    /**
     * Class to build instances of {@link CellTower}.
     */
    public static class Builder {
        private int cellId;
        private int locationAreaCode;
        private int mobileCountryCode;
        private int mobileNetworkCode;
        private Integer age;
        private Double signalStrength;
        private Double timingAdvance;
        private AdditionalProperties<Object> additionalProperties =
                new AdditionalProperties<Object>();

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  cellId  int value for cellId.
         * @param  locationAreaCode  int value for locationAreaCode.
         * @param  mobileCountryCode  int value for mobileCountryCode.
         * @param  mobileNetworkCode  int value for mobileNetworkCode.
         */
        public Builder(int cellId, int locationAreaCode, int mobileCountryCode,
                int mobileNetworkCode) {
            this.cellId = cellId;
            this.locationAreaCode = locationAreaCode;
            this.mobileCountryCode = mobileCountryCode;
            this.mobileNetworkCode = mobileNetworkCode;
        }

        /**
         * Setter for cellId.
         * @param  cellId  int value for cellId.
         * @return Builder
         */
        public Builder cellId(int cellId) {
            this.cellId = cellId;
            return this;
        }

        /**
         * Setter for locationAreaCode.
         * @param  locationAreaCode  int value for locationAreaCode.
         * @return Builder
         */
        public Builder locationAreaCode(int locationAreaCode) {
            this.locationAreaCode = locationAreaCode;
            return this;
        }

        /**
         * Setter for mobileCountryCode.
         * @param  mobileCountryCode  int value for mobileCountryCode.
         * @return Builder
         */
        public Builder mobileCountryCode(int mobileCountryCode) {
            this.mobileCountryCode = mobileCountryCode;
            return this;
        }

        /**
         * Setter for mobileNetworkCode.
         * @param  mobileNetworkCode  int value for mobileNetworkCode.
         * @return Builder
         */
        public Builder mobileNetworkCode(int mobileNetworkCode) {
            this.mobileNetworkCode = mobileNetworkCode;
            return this;
        }

        /**
         * Setter for age.
         * @param  age  Integer value for age.
         * @return Builder
         */
        public Builder age(Integer age) {
            this.age = age;
            return this;
        }

        /**
         * Setter for signalStrength.
         * @param  signalStrength  Double value for signalStrength.
         * @return Builder
         */
        public Builder signalStrength(Double signalStrength) {
            this.signalStrength = signalStrength;
            return this;
        }

        /**
         * Setter for timingAdvance.
         * @param  timingAdvance  Double value for timingAdvance.
         * @return Builder
         */
        public Builder timingAdvance(Double timingAdvance) {
            this.timingAdvance = timingAdvance;
            return this;
        }

        /**
         * Setter for additional property that are not in model fields.
         * @param name The name of the additional property.
         * @param value The Object value of the additional property.
         * @return Builder.
         */
        public Builder additionalProperty(String name, Object value) {
            this.additionalProperties.setAdditionalProperty(name, value);
            return this;
        }

        /**
         * Builds a new {@link CellTower} object using the set fields.
         * @return {@link CellTower}
         */
        public CellTower build() {
            CellTower model =
                    new CellTower(cellId, locationAreaCode, mobileCountryCode, mobileNetworkCode,
                            age, signalStrength, timingAdvance);
            model.additionalProperties = additionalProperties;
            return model;
        }
    }
}
