/*
 * GoogleMapsPlatformLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.googleapis.maps.models;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.AdditionalProperties;
import io.apimatic.core.utilities.ConversionHelper;
import java.util.List;
import java.util.Map;

/**
 * This is a model class for DirectionsGeocodedWaypoint type.
 */
public class DirectionsGeocodedWaypoint {
    private GeocoderStatus geocoderStatus;
    private Object partialMatch;
    private String placeId;
    private List<Type> types;
    private AdditionalProperties<Object> additionalProperties = 
            new AdditionalProperties<Object>(this.getClass());

    /**
     * Default constructor.
     */
    public DirectionsGeocodedWaypoint() {
    }

    /**
     * Initialization constructor.
     * @param  geocoderStatus  GeocoderStatus value for geocoderStatus.
     * @param  partialMatch  Object value for partialMatch.
     * @param  placeId  String value for placeId.
     * @param  types  List of Type value for types.
     */
    public DirectionsGeocodedWaypoint(
            GeocoderStatus geocoderStatus,
            Object partialMatch,
            String placeId,
            List<Type> types) {
        this.geocoderStatus = geocoderStatus;
        this.partialMatch = partialMatch;
        this.placeId = placeId;
        this.types = types;
    }

    /**
     * Getter for GeocoderStatus.
     * Indicates the status code resulting from the geocoding operation. This field may contain the
     * following values.
     * @return Returns the GeocoderStatus
     */
    @JsonGetter("geocoder_status")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public GeocoderStatus getGeocoderStatus() {
        return geocoderStatus;
    }

    /**
     * Setter for GeocoderStatus.
     * Indicates the status code resulting from the geocoding operation. This field may contain the
     * following values.
     * @param geocoderStatus Value for GeocoderStatus
     */
    @JsonSetter("geocoder_status")
    public void setGeocoderStatus(GeocoderStatus geocoderStatus) {
        this.geocoderStatus = geocoderStatus;
    }

    /**
     * Getter for PartialMatch.
     * Indicates that the geocoder did not return an exact match for the original request, though it
     * was able to match part of the requested address. You may wish to examine the original request
     * for misspellings and/or an incomplete address. Partial matches most often occur for street
     * addresses that do not exist within the locality you pass in the request. Partial matches may
     * also be returned when a request matches two or more locations in the same locality. For
     * example, "21 Henr St, Bristol, UK" will return a partial match for both Henry Street and
     * Henrietta Street. Note that if a request includes a misspelled address component, the
     * geocoding service may suggest an alternative address. Suggestions triggered in this way will
     * also be marked as a partial match.
     * @return Returns the Object
     */
    @JsonGetter("partial_match")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Object getPartialMatch() {
        return partialMatch;
    }

    /**
     * Setter for PartialMatch.
     * Indicates that the geocoder did not return an exact match for the original request, though it
     * was able to match part of the requested address. You may wish to examine the original request
     * for misspellings and/or an incomplete address. Partial matches most often occur for street
     * addresses that do not exist within the locality you pass in the request. Partial matches may
     * also be returned when a request matches two or more locations in the same locality. For
     * example, "21 Henr St, Bristol, UK" will return a partial match for both Henry Street and
     * Henrietta Street. Note that if a request includes a misspelled address component, the
     * geocoding service may suggest an alternative address. Suggestions triggered in this way will
     * also be marked as a partial match.
     * @param partialMatch Value for Object
     */
    @JsonSetter("partial_match")
    public void setPartialMatch(Object partialMatch) {
        this.partialMatch = partialMatch;
    }

    /**
     * Getter for PlaceId.
     * A unique identifier that can be used with other Google APIs. See the [Place ID
     * overview](https://developers.google.com/maps/documentation/places/web-service/place-id).
     * @return Returns the String
     */
    @JsonGetter("place_id")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getPlaceId() {
        return placeId;
    }

    /**
     * Setter for PlaceId.
     * A unique identifier that can be used with other Google APIs. See the [Place ID
     * overview](https://developers.google.com/maps/documentation/places/web-service/place-id).
     * @param placeId Value for String
     */
    @JsonSetter("place_id")
    public void setPlaceId(String placeId) {
        this.placeId = placeId;
    }

    /**
     * Getter for Types.
     * Indicates the address type of the geocoding result used for calculating directions. *
     * `administrative_area_level_1` indicates a first-order civil entity below the country level.
     * Within the United States, these administrative levels are states. Not all nations exhibit
     * these administrative levels. In most cases, administrative_area_level_1 short names will
     * closely match ISO 3166-2 subdivisions and other widely circulated lists; however this is not
     * guaranteed as our geocoding results are based on a variety of signals and location data. *
     * `administrative_area_level_2` indicates a second-order civil entity below the country level.
     * Within the United States, these administrative levels are counties. Not all nations exhibit
     * these administrative levels. * `administrative_area_level_3` indicates a third-order civil
     * entity below the country level. This type indicates a minor civil division. Not all nations
     * exhibit these administrative levels. * `administrative_area_level_4` indicates a fourth-order
     * civil entity below the country level. This type indicates a minor civil division. Not all
     * nations exhibit these administrative levels. * `administrative_area_level_5` indicates a
     * fifth-order civil entity below the country level. This type indicates a minor civil division.
     * Not all nations exhibit these administrative levels. * `airport` indicates an airport. *
     * `colloquial_area` indicates a commonly-used alternative name for the entity. * `country`
     * indicates the national political entity, and is typically the highest order type returned by
     * the Geocoder. * `intersection` indicates a major intersection, usually of two major roads. *
     * `locality` indicates an incorporated city or town political entity. * `natural_feature`
     * indicates a prominent natural feature. * `neighborhood` indicates a named neighborhood *
     * `park` indicates a named park. * `plus_code` indicates an encoded location reference, derived
     * from latitude and longitude. Plus codes can be used as a replacement for street addresses in
     * places where they do not exist (where buildings are not numbered or streets are not named).
     * See [https://plus.codes](https://plus.codes/) for details. * `point_of_interest` indicates a
     * named point of interest. Typically, these "POI"s are prominent local entities that don't
     * easily fit in another category, such as "Empire State Building" or "Eiffel Tower". *
     * `political` indicates a political entity. Usually, this type indicates a polygon of some
     * civil administration. * `postal_code` indicates a postal code as used to address postal mail
     * within the country. * `premise` indicates a named location, usually a building or collection
     * of buildings with a common name * `route` indicates a named route (such as "US 101"). *
     * `street_address` indicates a precise street address. * `sublocality` indicates a first-order
     * civil entity below a locality. For some locations may receive one of the additional types:
     * sublocality_level_1 to sublocality_level_5. Each sublocality level is a civil entity. Larger
     * numbers indicate a smaller geographic area. * `subpremise` indicates a first-order entity
     * below a named location, usually a singular building within a collection of buildings with a
     * common name * `tourist_attraction` indicates a tourist attraction. * `train_station`
     * indicates a train station. * `transit_station` indicates a transit station. An empty list of
     * types indicates there are no known types for the particular address component, for example,
     * Lieu-dit in France.
     * @return Returns the List of Type
     */
    @JsonGetter("types")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public List<Type> getTypes() {
        return types;
    }

    /**
     * Setter for Types.
     * Indicates the address type of the geocoding result used for calculating directions. *
     * `administrative_area_level_1` indicates a first-order civil entity below the country level.
     * Within the United States, these administrative levels are states. Not all nations exhibit
     * these administrative levels. In most cases, administrative_area_level_1 short names will
     * closely match ISO 3166-2 subdivisions and other widely circulated lists; however this is not
     * guaranteed as our geocoding results are based on a variety of signals and location data. *
     * `administrative_area_level_2` indicates a second-order civil entity below the country level.
     * Within the United States, these administrative levels are counties. Not all nations exhibit
     * these administrative levels. * `administrative_area_level_3` indicates a third-order civil
     * entity below the country level. This type indicates a minor civil division. Not all nations
     * exhibit these administrative levels. * `administrative_area_level_4` indicates a fourth-order
     * civil entity below the country level. This type indicates a minor civil division. Not all
     * nations exhibit these administrative levels. * `administrative_area_level_5` indicates a
     * fifth-order civil entity below the country level. This type indicates a minor civil division.
     * Not all nations exhibit these administrative levels. * `airport` indicates an airport. *
     * `colloquial_area` indicates a commonly-used alternative name for the entity. * `country`
     * indicates the national political entity, and is typically the highest order type returned by
     * the Geocoder. * `intersection` indicates a major intersection, usually of two major roads. *
     * `locality` indicates an incorporated city or town political entity. * `natural_feature`
     * indicates a prominent natural feature. * `neighborhood` indicates a named neighborhood *
     * `park` indicates a named park. * `plus_code` indicates an encoded location reference, derived
     * from latitude and longitude. Plus codes can be used as a replacement for street addresses in
     * places where they do not exist (where buildings are not numbered or streets are not named).
     * See [https://plus.codes](https://plus.codes/) for details. * `point_of_interest` indicates a
     * named point of interest. Typically, these "POI"s are prominent local entities that don't
     * easily fit in another category, such as "Empire State Building" or "Eiffel Tower". *
     * `political` indicates a political entity. Usually, this type indicates a polygon of some
     * civil administration. * `postal_code` indicates a postal code as used to address postal mail
     * within the country. * `premise` indicates a named location, usually a building or collection
     * of buildings with a common name * `route` indicates a named route (such as "US 101"). *
     * `street_address` indicates a precise street address. * `sublocality` indicates a first-order
     * civil entity below a locality. For some locations may receive one of the additional types:
     * sublocality_level_1 to sublocality_level_5. Each sublocality level is a civil entity. Larger
     * numbers indicate a smaller geographic area. * `subpremise` indicates a first-order entity
     * below a named location, usually a singular building within a collection of buildings with a
     * common name * `tourist_attraction` indicates a tourist attraction. * `train_station`
     * indicates a train station. * `transit_station` indicates a transit station. An empty list of
     * types indicates there are no known types for the particular address component, for example,
     * Lieu-dit in France.
     * @param types Value for List of Type
     */
    @JsonSetter("types")
    public void setTypes(List<Type> types) {
        this.types = types;
    }

    /**
     * Hidden method for the serialization of additional properties.
     * @return The map of additionally set properties.
     */
    @JsonAnyGetter
    private Map<String, Object> getAdditionalProperties() {
        return additionalProperties.getAdditionalProperties();
    }

    /**
     * Hidden method for the de-serialization of additional properties.
     * @param name The name of the additional property.
     * @param value The Object value of the additional property.
     */
    @JsonAnySetter
    private void setAdditionalProperties(String name, Object value) {
        additionalProperties.setAdditionalProperty(name,
                ConversionHelper.convertToSimpleType(value,
                        x -> x),
                true);
    }

    /**
     * Getter for the value of additional properties based on provided property name.
     * @param name The name of the additional property.
     * @return Either the Object property value or null if not exist.
     */
    
    public Object getAdditionalProperty(String name) {
        return additionalProperties.getAdditionalProperty(name);
    }

    /**
     * Converts this DirectionsGeocodedWaypoint into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "DirectionsGeocodedWaypoint [" + "geocoderStatus=" + geocoderStatus
                + ", partialMatch=" + partialMatch + ", placeId=" + placeId + ", types=" + types
                + ", additionalProperties=" + additionalProperties + "]";
    }

    /**
     * Builds a new {@link DirectionsGeocodedWaypoint.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link DirectionsGeocodedWaypoint.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .geocoderStatus(getGeocoderStatus())
                .partialMatch(getPartialMatch())
                .placeId(getPlaceId())
                .types(getTypes());
        builder.additionalProperties = additionalProperties;
        return builder;
    }

    /**
     * Class to build instances of {@link DirectionsGeocodedWaypoint}.
     */
    public static class Builder {
        private GeocoderStatus geocoderStatus;
        private Object partialMatch;
        private String placeId;
        private List<Type> types;
        private AdditionalProperties<Object> additionalProperties =
                new AdditionalProperties<Object>();



        /**
         * Setter for geocoderStatus.
         * @param  geocoderStatus  GeocoderStatus value for geocoderStatus.
         * @return Builder
         */
        public Builder geocoderStatus(GeocoderStatus geocoderStatus) {
            this.geocoderStatus = geocoderStatus;
            return this;
        }

        /**
         * Setter for partialMatch.
         * @param  partialMatch  Object value for partialMatch.
         * @return Builder
         */
        public Builder partialMatch(Object partialMatch) {
            this.partialMatch = partialMatch;
            return this;
        }

        /**
         * Setter for placeId.
         * @param  placeId  String value for placeId.
         * @return Builder
         */
        public Builder placeId(String placeId) {
            this.placeId = placeId;
            return this;
        }

        /**
         * Setter for types.
         * @param  types  List of Type value for types.
         * @return Builder
         */
        public Builder types(List<Type> types) {
            this.types = types;
            return this;
        }

        /**
         * Setter for additional property that are not in model fields.
         * @param name The name of the additional property.
         * @param value The Object value of the additional property.
         * @return Builder.
         */
        public Builder additionalProperty(String name, Object value) {
            this.additionalProperties.setAdditionalProperty(name, value);
            return this;
        }

        /**
         * Builds a new {@link DirectionsGeocodedWaypoint} object using the set fields.
         * @return {@link DirectionsGeocodedWaypoint}
         */
        public DirectionsGeocodedWaypoint build() {
            DirectionsGeocodedWaypoint model =
                    new DirectionsGeocodedWaypoint(geocoderStatus, partialMatch, placeId, types);
            model.additionalProperties = additionalProperties;
            return model;
        }
    }
}
