/*
 * GoogleMapsPlatformLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.googleapis.maps.models;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.AdditionalProperties;
import io.apimatic.core.utilities.ConversionHelper;
import java.util.Map;

/**
 * This is a model class for DirectionsViaWaypoint type.
 */
public class DirectionsViaWaypoint {
    private LatLngLiteral location;
    private Integer stepIndex;
    private Double stepInterpolation;
    private AdditionalProperties<Object> additionalProperties = 
            new AdditionalProperties<Object>(this.getClass());

    /**
     * Default constructor.
     */
    public DirectionsViaWaypoint() {
    }

    /**
     * Initialization constructor.
     * @param  location  LatLngLiteral value for location.
     * @param  stepIndex  Integer value for stepIndex.
     * @param  stepInterpolation  Double value for stepInterpolation.
     */
    public DirectionsViaWaypoint(
            LatLngLiteral location,
            Integer stepIndex,
            Double stepInterpolation) {
        this.location = location;
        this.stepIndex = stepIndex;
        this.stepInterpolation = stepInterpolation;
    }

    /**
     * Getter for Location.
     * An object describing a specific location with Latitude and Longitude in decimal degrees.
     * @return Returns the LatLngLiteral
     */
    @JsonGetter("location")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public LatLngLiteral getLocation() {
        return location;
    }

    /**
     * Setter for Location.
     * An object describing a specific location with Latitude and Longitude in decimal degrees.
     * @param location Value for LatLngLiteral
     */
    @JsonSetter("location")
    public void setLocation(LatLngLiteral location) {
        this.location = location;
    }

    /**
     * Getter for StepIndex.
     * The index of the step containing the waypoint.
     * @return Returns the Integer
     */
    @JsonGetter("step_index")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Integer getStepIndex() {
        return stepIndex;
    }

    /**
     * Setter for StepIndex.
     * The index of the step containing the waypoint.
     * @param stepIndex Value for Integer
     */
    @JsonSetter("step_index")
    public void setStepIndex(Integer stepIndex) {
        this.stepIndex = stepIndex;
    }

    /**
     * Getter for StepInterpolation.
     * The position of the waypoint along the step's polyline, expressed as a ratio from 0 to 1.
     * @return Returns the Double
     */
    @JsonGetter("step_interpolation")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Double getStepInterpolation() {
        return stepInterpolation;
    }

    /**
     * Setter for StepInterpolation.
     * The position of the waypoint along the step's polyline, expressed as a ratio from 0 to 1.
     * @param stepInterpolation Value for Double
     */
    @JsonSetter("step_interpolation")
    public void setStepInterpolation(Double stepInterpolation) {
        this.stepInterpolation = stepInterpolation;
    }

    /**
     * Hidden method for the serialization of additional properties.
     * @return The map of additionally set properties.
     */
    @JsonAnyGetter
    private Map<String, Object> getAdditionalProperties() {
        return additionalProperties.getAdditionalProperties();
    }

    /**
     * Hidden method for the de-serialization of additional properties.
     * @param name The name of the additional property.
     * @param value The Object value of the additional property.
     */
    @JsonAnySetter
    private void setAdditionalProperties(String name, Object value) {
        additionalProperties.setAdditionalProperty(name,
                ConversionHelper.convertToSimpleType(value,
                        x -> x),
                true);
    }

    /**
     * Getter for the value of additional properties based on provided property name.
     * @param name The name of the additional property.
     * @return Either the Object property value or null if not exist.
     */
    
    public Object getAdditionalProperty(String name) {
        return additionalProperties.getAdditionalProperty(name);
    }

    /**
     * Converts this DirectionsViaWaypoint into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "DirectionsViaWaypoint [" + "location=" + location + ", stepIndex=" + stepIndex
                + ", stepInterpolation=" + stepInterpolation + ", additionalProperties="
                + additionalProperties + "]";
    }

    /**
     * Builds a new {@link DirectionsViaWaypoint.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link DirectionsViaWaypoint.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .location(getLocation())
                .stepIndex(getStepIndex())
                .stepInterpolation(getStepInterpolation());
        builder.additionalProperties = additionalProperties;
        return builder;
    }

    /**
     * Class to build instances of {@link DirectionsViaWaypoint}.
     */
    public static class Builder {
        private LatLngLiteral location;
        private Integer stepIndex;
        private Double stepInterpolation;
        private AdditionalProperties<Object> additionalProperties =
                new AdditionalProperties<Object>();



        /**
         * Setter for location.
         * @param  location  LatLngLiteral value for location.
         * @return Builder
         */
        public Builder location(LatLngLiteral location) {
            this.location = location;
            return this;
        }

        /**
         * Setter for stepIndex.
         * @param  stepIndex  Integer value for stepIndex.
         * @return Builder
         */
        public Builder stepIndex(Integer stepIndex) {
            this.stepIndex = stepIndex;
            return this;
        }

        /**
         * Setter for stepInterpolation.
         * @param  stepInterpolation  Double value for stepInterpolation.
         * @return Builder
         */
        public Builder stepInterpolation(Double stepInterpolation) {
            this.stepInterpolation = stepInterpolation;
            return this;
        }

        /**
         * Setter for additional property that are not in model fields.
         * @param name The name of the additional property.
         * @param value The Object value of the additional property.
         * @return Builder.
         */
        public Builder additionalProperty(String name, Object value) {
            this.additionalProperties.setAdditionalProperty(name, value);
            return this;
        }

        /**
         * Builds a new {@link DirectionsViaWaypoint} object using the set fields.
         * @return {@link DirectionsViaWaypoint}
         */
        public DirectionsViaWaypoint build() {
            DirectionsViaWaypoint model =
                    new DirectionsViaWaypoint(location, stepIndex, stepInterpolation);
            model.additionalProperties = additionalProperties;
            return model;
        }
    }
}
