/*
 * GoogleMapsPlatformLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.googleapis.maps.models;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.AdditionalProperties;
import io.apimatic.core.utilities.ConversionHelper;
import java.util.Map;

/**
 * This is a model class for ElevationResult type.
 */
public class ElevationResult {
    private double elevation;
    private Double resolution;
    private LatLngLiteral location;
    private AdditionalProperties<Object> additionalProperties = 
            new AdditionalProperties<Object>(this.getClass());

    /**
     * Default constructor.
     */
    public ElevationResult() {
    }

    /**
     * Initialization constructor.
     * @param  elevation  double value for elevation.
     * @param  location  LatLngLiteral value for location.
     * @param  resolution  Double value for resolution.
     */
    public ElevationResult(
            double elevation,
            LatLngLiteral location,
            Double resolution) {
        this.elevation = elevation;
        this.resolution = resolution;
        this.location = location;
    }

    /**
     * Getter for Elevation.
     * The elevation of the location in meters.
     * @return Returns the double
     */
    @JsonGetter("elevation")
    public double getElevation() {
        return elevation;
    }

    /**
     * Setter for Elevation.
     * The elevation of the location in meters.
     * @param elevation Value for double
     */
    @JsonSetter("elevation")
    public void setElevation(double elevation) {
        this.elevation = elevation;
    }

    /**
     * Getter for Resolution.
     * The value indicating the maximum distance between data points from which the elevation was
     * interpolated, in meters. This property will be missing if the resolution is not known. Note
     * that elevation data becomes more coarse (larger resolution values) when multiple points are
     * passed. To obtain the most accurate elevation value for a point, it should be queried
     * independently.
     * @return Returns the Double
     */
    @JsonGetter("resolution")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Double getResolution() {
        return resolution;
    }

    /**
     * Setter for Resolution.
     * The value indicating the maximum distance between data points from which the elevation was
     * interpolated, in meters. This property will be missing if the resolution is not known. Note
     * that elevation data becomes more coarse (larger resolution values) when multiple points are
     * passed. To obtain the most accurate elevation value for a point, it should be queried
     * independently.
     * @param resolution Value for Double
     */
    @JsonSetter("resolution")
    public void setResolution(Double resolution) {
        this.resolution = resolution;
    }

    /**
     * Getter for Location.
     * An object describing a specific location with Latitude and Longitude in decimal degrees.
     * @return Returns the LatLngLiteral
     */
    @JsonGetter("location")
    public LatLngLiteral getLocation() {
        return location;
    }

    /**
     * Setter for Location.
     * An object describing a specific location with Latitude and Longitude in decimal degrees.
     * @param location Value for LatLngLiteral
     */
    @JsonSetter("location")
    public void setLocation(LatLngLiteral location) {
        this.location = location;
    }

    /**
     * Hidden method for the serialization of additional properties.
     * @return The map of additionally set properties.
     */
    @JsonAnyGetter
    private Map<String, Object> getAdditionalProperties() {
        return additionalProperties.getAdditionalProperties();
    }

    /**
     * Hidden method for the de-serialization of additional properties.
     * @param name The name of the additional property.
     * @param value The Object value of the additional property.
     */
    @JsonAnySetter
    private void setAdditionalProperties(String name, Object value) {
        additionalProperties.setAdditionalProperty(name,
                ConversionHelper.convertToSimpleType(value,
                        x -> x),
                true);
    }

    /**
     * Getter for the value of additional properties based on provided property name.
     * @param name The name of the additional property.
     * @return Either the Object property value or null if not exist.
     */
    
    public Object getAdditionalProperty(String name) {
        return additionalProperties.getAdditionalProperty(name);
    }

    /**
     * Converts this ElevationResult into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "ElevationResult [" + "elevation=" + elevation + ", location=" + location
                + ", resolution=" + resolution + ", additionalProperties=" + additionalProperties
                + "]";
    }

    /**
     * Builds a new {@link ElevationResult.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link ElevationResult.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(elevation, location)
                .resolution(getResolution());
        builder.additionalProperties = additionalProperties;
        return builder;
    }

    /**
     * Class to build instances of {@link ElevationResult}.
     */
    public static class Builder {
        private double elevation;
        private LatLngLiteral location;
        private Double resolution;
        private AdditionalProperties<Object> additionalProperties =
                new AdditionalProperties<Object>();

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  elevation  double value for elevation.
         * @param  location  LatLngLiteral value for location.
         */
        public Builder(double elevation, LatLngLiteral location) {
            this.elevation = elevation;
            this.location = location;
        }

        /**
         * Setter for elevation.
         * @param  elevation  double value for elevation.
         * @return Builder
         */
        public Builder elevation(double elevation) {
            this.elevation = elevation;
            return this;
        }

        /**
         * Setter for location.
         * @param  location  LatLngLiteral value for location.
         * @return Builder
         */
        public Builder location(LatLngLiteral location) {
            this.location = location;
            return this;
        }

        /**
         * Setter for resolution.
         * @param  resolution  Double value for resolution.
         * @return Builder
         */
        public Builder resolution(Double resolution) {
            this.resolution = resolution;
            return this;
        }

        /**
         * Setter for additional property that are not in model fields.
         * @param name The name of the additional property.
         * @param value The Object value of the additional property.
         * @return Builder.
         */
        public Builder additionalProperty(String name, Object value) {
            this.additionalProperties.setAdditionalProperty(name, value);
            return this;
        }

        /**
         * Builds a new {@link ElevationResult} object using the set fields.
         * @return {@link ElevationResult}
         */
        public ElevationResult build() {
            ElevationResult model =
                    new ElevationResult(elevation, location, resolution);
            model.additionalProperties = additionalProperties;
            return model;
        }
    }
}
