/*
 * GoogleMapsPlatformLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.googleapis.maps.models;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.TreeMap;


/**
 * Maneuver to be used.
 */
public enum Maneuver {
    TURNSLIGHTLEFT,

    TURNSHARPLEFT,

    TURNLEFT,

    TURNSLIGHTRIGHT,

    TURNSHARPRIGHT,

    KEEPRIGHT,

    KEEPLEFT,

    UTURNLEFT,

    UTURNRIGHT,

    TURNRIGHT,

    STRAIGHT,

    RAMPLEFT,

    RAMPRIGHT,

    MERGE,

    FORKLEFT,

    FORKRIGHT,

    FERRY,

    FERRYTRAIN,

    ROUNDABOUTLEFT,

    ROUNDABOUTRIGHT;


    private static TreeMap<String, Maneuver> valueMap = new TreeMap<>();
    private String value;

    static {
        TURNSLIGHTLEFT.value = "turn-slight-left";
        TURNSHARPLEFT.value = "turn-sharp-left";
        TURNLEFT.value = "turn-left";
        TURNSLIGHTRIGHT.value = "turn-slight-right";
        TURNSHARPRIGHT.value = "turn-sharp-right";
        KEEPRIGHT.value = "keep-right";
        KEEPLEFT.value = "keep-left";
        UTURNLEFT.value = "uturn-left";
        UTURNRIGHT.value = "uturn-right";
        TURNRIGHT.value = "turn-right";
        STRAIGHT.value = "straight";
        RAMPLEFT.value = "ramp-left";
        RAMPRIGHT.value = "ramp-right";
        MERGE.value = "merge";
        FORKLEFT.value = "fork-left";
        FORKRIGHT.value = "fork-right";
        FERRY.value = "ferry";
        FERRYTRAIN.value = "ferry-train";
        ROUNDABOUTLEFT.value = "roundabout-left";
        ROUNDABOUTRIGHT.value = "roundabout-right";

        valueMap.put("turn-slight-left", TURNSLIGHTLEFT);
        valueMap.put("turn-sharp-left", TURNSHARPLEFT);
        valueMap.put("turn-left", TURNLEFT);
        valueMap.put("turn-slight-right", TURNSLIGHTRIGHT);
        valueMap.put("turn-sharp-right", TURNSHARPRIGHT);
        valueMap.put("keep-right", KEEPRIGHT);
        valueMap.put("keep-left", KEEPLEFT);
        valueMap.put("uturn-left", UTURNLEFT);
        valueMap.put("uturn-right", UTURNRIGHT);
        valueMap.put("turn-right", TURNRIGHT);
        valueMap.put("straight", STRAIGHT);
        valueMap.put("ramp-left", RAMPLEFT);
        valueMap.put("ramp-right", RAMPRIGHT);
        valueMap.put("merge", MERGE);
        valueMap.put("fork-left", FORKLEFT);
        valueMap.put("fork-right", FORKRIGHT);
        valueMap.put("ferry", FERRY);
        valueMap.put("ferry-train", FERRYTRAIN);
        valueMap.put("roundabout-left", ROUNDABOUTLEFT);
        valueMap.put("roundabout-right", ROUNDABOUTRIGHT);
    }

    /**
     * Returns the enum member associated with the given string value.
     * @param toConvert String value to get enum member.
     * @return The enum member against the given string value.
     * @throws IOException when provided value is not mapped to any enum member.
     */
    @JsonCreator
    public static Maneuver constructFromString(String toConvert) throws IOException {
        Maneuver enumValue = fromString(toConvert);
        if (enumValue == null) {
            throw new IOException("Unable to create enum instance with value: " + toConvert);
        }
        return enumValue;
    }

    /**
     * Returns the enum member associated with the given string value.
     * @param toConvert String value to get enum member.
     * @return The enum member against the given string value.
     */
    public static Maneuver fromString(String toConvert) {
        return valueMap.get(toConvert);
    }

    /**
     * Returns the string value associated with the enum member.
     * @return The string value against enum member.
     */
    @JsonValue
    public String value() {
        return value;
    }
        
    /**
     * Get string representation of this enum.
     */
    @Override
    public String toString() {
        return value.toString();
    }

    /**
     * Convert list of Maneuver values to list of string values.
     * @param toConvert The list of Maneuver values to convert.
     * @return List of representative string values.
     */
    public static List<String> toValue(List<Maneuver> toConvert) {
        if (toConvert == null) {
            return null;
        }
        List<String> convertedValues = new ArrayList<>();
        for (Maneuver enumValue : toConvert) {
            convertedValues.add(enumValue.value);
        }
        return convertedValues;
    }
} 