/*
 * GoogleMapsPlatformLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.googleapis.maps.models;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.AdditionalProperties;
import io.apimatic.core.utilities.ConversionHelper;
import java.util.Map;

/**
 * This is a model class for PlaceOpeningHoursPeriod type.
 */
public class PlaceOpeningHoursPeriod {
    private PlaceOpeningHoursPeriodDetail open;
    private PlaceOpeningHoursPeriodDetail close;
    private AdditionalProperties<Object> additionalProperties = 
            new AdditionalProperties<Object>(this.getClass());

    /**
     * Default constructor.
     */
    public PlaceOpeningHoursPeriod() {
    }

    /**
     * Initialization constructor.
     * @param  open  PlaceOpeningHoursPeriodDetail value for open.
     * @param  close  PlaceOpeningHoursPeriodDetail value for close.
     */
    public PlaceOpeningHoursPeriod(
            PlaceOpeningHoursPeriodDetail open,
            PlaceOpeningHoursPeriodDetail close) {
        this.open = open;
        this.close = close;
    }

    /**
     * Getter for Open.
     * @return Returns the PlaceOpeningHoursPeriodDetail
     */
    @JsonGetter("open")
    public PlaceOpeningHoursPeriodDetail getOpen() {
        return open;
    }

    /**
     * Setter for Open.
     * @param open Value for PlaceOpeningHoursPeriodDetail
     */
    @JsonSetter("open")
    public void setOpen(PlaceOpeningHoursPeriodDetail open) {
        this.open = open;
    }

    /**
     * Getter for Close.
     * @return Returns the PlaceOpeningHoursPeriodDetail
     */
    @JsonGetter("close")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public PlaceOpeningHoursPeriodDetail getClose() {
        return close;
    }

    /**
     * Setter for Close.
     * @param close Value for PlaceOpeningHoursPeriodDetail
     */
    @JsonSetter("close")
    public void setClose(PlaceOpeningHoursPeriodDetail close) {
        this.close = close;
    }

    /**
     * Hidden method for the serialization of additional properties.
     * @return The map of additionally set properties.
     */
    @JsonAnyGetter
    private Map<String, Object> getAdditionalProperties() {
        return additionalProperties.getAdditionalProperties();
    }

    /**
     * Hidden method for the de-serialization of additional properties.
     * @param name The name of the additional property.
     * @param value The Object value of the additional property.
     */
    @JsonAnySetter
    private void setAdditionalProperties(String name, Object value) {
        additionalProperties.setAdditionalProperty(name,
                ConversionHelper.convertToSimpleType(value,
                        x -> x),
                true);
    }

    /**
     * Getter for the value of additional properties based on provided property name.
     * @param name The name of the additional property.
     * @return Either the Object property value or null if not exist.
     */
    
    public Object getAdditionalProperty(String name) {
        return additionalProperties.getAdditionalProperty(name);
    }

    /**
     * Converts this PlaceOpeningHoursPeriod into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "PlaceOpeningHoursPeriod [" + "open=" + open + ", close=" + close
                + ", additionalProperties=" + additionalProperties + "]";
    }

    /**
     * Builds a new {@link PlaceOpeningHoursPeriod.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link PlaceOpeningHoursPeriod.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(open)
                .close(getClose());
        builder.additionalProperties = additionalProperties;
        return builder;
    }

    /**
     * Class to build instances of {@link PlaceOpeningHoursPeriod}.
     */
    public static class Builder {
        private PlaceOpeningHoursPeriodDetail open;
        private PlaceOpeningHoursPeriodDetail close;
        private AdditionalProperties<Object> additionalProperties =
                new AdditionalProperties<Object>();

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  open  PlaceOpeningHoursPeriodDetail value for open.
         */
        public Builder(PlaceOpeningHoursPeriodDetail open) {
            this.open = open;
        }

        /**
         * Setter for open.
         * @param  open  PlaceOpeningHoursPeriodDetail value for open.
         * @return Builder
         */
        public Builder open(PlaceOpeningHoursPeriodDetail open) {
            this.open = open;
            return this;
        }

        /**
         * Setter for close.
         * @param  close  PlaceOpeningHoursPeriodDetail value for close.
         * @return Builder
         */
        public Builder close(PlaceOpeningHoursPeriodDetail close) {
            this.close = close;
            return this;
        }

        /**
         * Setter for additional property that are not in model fields.
         * @param name The name of the additional property.
         * @param value The Object value of the additional property.
         * @return Builder.
         */
        public Builder additionalProperty(String name, Object value) {
            this.additionalProperties.setAdditionalProperty(name, value);
            return this;
        }

        /**
         * Builds a new {@link PlaceOpeningHoursPeriod} object using the set fields.
         * @return {@link PlaceOpeningHoursPeriod}
         */
        public PlaceOpeningHoursPeriod build() {
            PlaceOpeningHoursPeriod model =
                    new PlaceOpeningHoursPeriod(open, close);
            model.additionalProperties = additionalProperties;
            return model;
        }
    }
}
