/*
 * GoogleMapsPlatformLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.googleapis.maps.models;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.AdditionalProperties;
import io.apimatic.core.utilities.ConversionHelper;
import java.util.List;
import java.util.Map;

/**
 * This is a model class for PlaceAutocompletePrediction type.
 */
public class PlaceAutocompletePrediction {
    private String description;
    private List<PlaceAutocompleteMatchedSubstring> matchedSubstrings;
    private String placeId;
    private String reference;
    private PlaceAutocompleteStructuredFormat structuredFormatting;
    private List<PlaceAutocompleteTerm> terms;
    private List<String> types;
    private Integer distanceMeters;
    private AdditionalProperties<Object> additionalProperties = 
            new AdditionalProperties<Object>(this.getClass());

    /**
     * Default constructor.
     */
    public PlaceAutocompletePrediction() {
    }

    /**
     * Initialization constructor.
     * @param  description  String value for description.
     * @param  matchedSubstrings  List of PlaceAutocompleteMatchedSubstring value for
     *         matchedSubstrings.
     * @param  structuredFormatting  PlaceAutocompleteStructuredFormat value for
     *         structuredFormatting.
     * @param  terms  List of PlaceAutocompleteTerm value for terms.
     * @param  placeId  String value for placeId.
     * @param  reference  String value for reference.
     * @param  types  List of String value for types.
     * @param  distanceMeters  Integer value for distanceMeters.
     */
    public PlaceAutocompletePrediction(
            String description,
            List<PlaceAutocompleteMatchedSubstring> matchedSubstrings,
            PlaceAutocompleteStructuredFormat structuredFormatting,
            List<PlaceAutocompleteTerm> terms,
            String placeId,
            String reference,
            List<String> types,
            Integer distanceMeters) {
        this.description = description;
        this.matchedSubstrings = matchedSubstrings;
        this.placeId = placeId;
        this.reference = reference;
        this.structuredFormatting = structuredFormatting;
        this.terms = terms;
        this.types = types;
        this.distanceMeters = distanceMeters;
    }

    /**
     * Getter for Description.
     * Contains the human-readable name for the returned result. For `establishment` results, this
     * is usually the business name. This content is meant to be read as-is. Do not programmatically
     * parse the formatted address.
     * @return Returns the String
     */
    @JsonGetter("description")
    public String getDescription() {
        return description;
    }

    /**
     * Setter for Description.
     * Contains the human-readable name for the returned result. For `establishment` results, this
     * is usually the business name. This content is meant to be read as-is. Do not programmatically
     * parse the formatted address.
     * @param description Value for String
     */
    @JsonSetter("description")
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * Getter for MatchedSubstrings.
     * A list of substrings that describe the location of the entered term in the prediction result
     * text, so that the term can be highlighted if desired.
     * @return Returns the List of PlaceAutocompleteMatchedSubstring
     */
    @JsonGetter("matched_substrings")
    public List<PlaceAutocompleteMatchedSubstring> getMatchedSubstrings() {
        return matchedSubstrings;
    }

    /**
     * Setter for MatchedSubstrings.
     * A list of substrings that describe the location of the entered term in the prediction result
     * text, so that the term can be highlighted if desired.
     * @param matchedSubstrings Value for List of PlaceAutocompleteMatchedSubstring
     */
    @JsonSetter("matched_substrings")
    public void setMatchedSubstrings(List<PlaceAutocompleteMatchedSubstring> matchedSubstrings) {
        this.matchedSubstrings = matchedSubstrings;
    }

    /**
     * Getter for PlaceId.
     * A textual identifier that uniquely identifies a place. To retrieve information about the
     * place, pass this identifier in the placeId field of a Places API request. For more
     * information about place IDs, see the [Place
     * IDs](https://developers.google.com/maps/documentation/places/web-service/place-id) overview.
     * @return Returns the String
     */
    @JsonGetter("place_id")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getPlaceId() {
        return placeId;
    }

    /**
     * Setter for PlaceId.
     * A textual identifier that uniquely identifies a place. To retrieve information about the
     * place, pass this identifier in the placeId field of a Places API request. For more
     * information about place IDs, see the [Place
     * IDs](https://developers.google.com/maps/documentation/places/web-service/place-id) overview.
     * @param placeId Value for String
     */
    @JsonSetter("place_id")
    public void setPlaceId(String placeId) {
        this.placeId = placeId;
    }

    /**
     * Getter for Reference.
     * See place_id.
     * @return Returns the String
     */
    @JsonGetter("reference")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getReference() {
        return reference;
    }

    /**
     * Setter for Reference.
     * See place_id.
     * @param reference Value for String
     */
    @JsonSetter("reference")
    public void setReference(String reference) {
        this.reference = reference;
    }

    /**
     * Getter for StructuredFormatting.
     * @return Returns the PlaceAutocompleteStructuredFormat
     */
    @JsonGetter("structured_formatting")
    public PlaceAutocompleteStructuredFormat getStructuredFormatting() {
        return structuredFormatting;
    }

    /**
     * Setter for StructuredFormatting.
     * @param structuredFormatting Value for PlaceAutocompleteStructuredFormat
     */
    @JsonSetter("structured_formatting")
    public void setStructuredFormatting(PlaceAutocompleteStructuredFormat structuredFormatting) {
        this.structuredFormatting = structuredFormatting;
    }

    /**
     * Getter for Terms.
     * Contains an array of terms identifying each section of the returned description (a section of
     * the description is generally terminated with a comma). Each entry in the array has a `value`
     * field, containing the text of the term, and an `offset` field, defining the start position of
     * this term in the description, measured in Unicode characters.
     * @return Returns the List of PlaceAutocompleteTerm
     */
    @JsonGetter("terms")
    public List<PlaceAutocompleteTerm> getTerms() {
        return terms;
    }

    /**
     * Setter for Terms.
     * Contains an array of terms identifying each section of the returned description (a section of
     * the description is generally terminated with a comma). Each entry in the array has a `value`
     * field, containing the text of the term, and an `offset` field, defining the start position of
     * this term in the description, measured in Unicode characters.
     * @param terms Value for List of PlaceAutocompleteTerm
     */
    @JsonSetter("terms")
    public void setTerms(List<PlaceAutocompleteTerm> terms) {
        this.terms = terms;
    }

    /**
     * Getter for Types.
     * Contains an array of types that apply to this place. For example: `[ "political", "locality"
     * ]` or `[ "establishment", "geocode", "beauty_salon" ]`. The array can contain multiple
     * values. Learn more about [Place
     * types](https://developers.google.com/maps/documentation/places/web-service/supported_types).
     * @return Returns the List of String
     */
    @JsonGetter("types")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public List<String> getTypes() {
        return types;
    }

    /**
     * Setter for Types.
     * Contains an array of types that apply to this place. For example: `[ "political", "locality"
     * ]` or `[ "establishment", "geocode", "beauty_salon" ]`. The array can contain multiple
     * values. Learn more about [Place
     * types](https://developers.google.com/maps/documentation/places/web-service/supported_types).
     * @param types Value for List of String
     */
    @JsonSetter("types")
    public void setTypes(List<String> types) {
        this.types = types;
    }

    /**
     * Getter for DistanceMeters.
     * The straight-line distance in meters from the origin. This field is only returned for
     * requests made with an `origin`.
     * @return Returns the Integer
     */
    @JsonGetter("distance_meters")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Integer getDistanceMeters() {
        return distanceMeters;
    }

    /**
     * Setter for DistanceMeters.
     * The straight-line distance in meters from the origin. This field is only returned for
     * requests made with an `origin`.
     * @param distanceMeters Value for Integer
     */
    @JsonSetter("distance_meters")
    public void setDistanceMeters(Integer distanceMeters) {
        this.distanceMeters = distanceMeters;
    }

    /**
     * Hidden method for the serialization of additional properties.
     * @return The map of additionally set properties.
     */
    @JsonAnyGetter
    private Map<String, Object> getAdditionalProperties() {
        return additionalProperties.getAdditionalProperties();
    }

    /**
     * Hidden method for the de-serialization of additional properties.
     * @param name The name of the additional property.
     * @param value The Object value of the additional property.
     */
    @JsonAnySetter
    private void setAdditionalProperties(String name, Object value) {
        additionalProperties.setAdditionalProperty(name,
                ConversionHelper.convertToSimpleType(value,
                        x -> x),
                true);
    }

    /**
     * Getter for the value of additional properties based on provided property name.
     * @param name The name of the additional property.
     * @return Either the Object property value or null if not exist.
     */
    
    public Object getAdditionalProperty(String name) {
        return additionalProperties.getAdditionalProperty(name);
    }

    /**
     * Converts this PlaceAutocompletePrediction into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "PlaceAutocompletePrediction [" + "description=" + description
                + ", matchedSubstrings=" + matchedSubstrings + ", structuredFormatting="
                + structuredFormatting + ", terms=" + terms + ", placeId=" + placeId
                + ", reference=" + reference + ", types=" + types + ", distanceMeters="
                + distanceMeters + ", additionalProperties=" + additionalProperties + "]";
    }

    /**
     * Builds a new {@link PlaceAutocompletePrediction.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link PlaceAutocompletePrediction.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(description, matchedSubstrings, structuredFormatting, terms)
                .placeId(getPlaceId())
                .reference(getReference())
                .types(getTypes())
                .distanceMeters(getDistanceMeters());
        builder.additionalProperties = additionalProperties;
        return builder;
    }

    /**
     * Class to build instances of {@link PlaceAutocompletePrediction}.
     */
    public static class Builder {
        private String description;
        private List<PlaceAutocompleteMatchedSubstring> matchedSubstrings;
        private PlaceAutocompleteStructuredFormat structuredFormatting;
        private List<PlaceAutocompleteTerm> terms;
        private String placeId;
        private String reference;
        private List<String> types;
        private Integer distanceMeters;
        private AdditionalProperties<Object> additionalProperties =
                new AdditionalProperties<Object>();

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  description  String value for description.
         * @param  matchedSubstrings  List of PlaceAutocompleteMatchedSubstring value for
         *         matchedSubstrings.
         * @param  structuredFormatting  PlaceAutocompleteStructuredFormat value for
         *         structuredFormatting.
         * @param  terms  List of PlaceAutocompleteTerm value for terms.
         */
        public Builder(String description,
                List<PlaceAutocompleteMatchedSubstring> matchedSubstrings,
                PlaceAutocompleteStructuredFormat structuredFormatting,
                List<PlaceAutocompleteTerm> terms) {
            this.description = description;
            this.matchedSubstrings = matchedSubstrings;
            this.structuredFormatting = structuredFormatting;
            this.terms = terms;
        }

        /**
         * Setter for description.
         * @param  description  String value for description.
         * @return Builder
         */
        public Builder description(String description) {
            this.description = description;
            return this;
        }

        /**
         * Setter for matchedSubstrings.
         * @param  matchedSubstrings  List of PlaceAutocompleteMatchedSubstring value for
         *         matchedSubstrings.
         * @return Builder
         */
        public Builder matchedSubstrings(
                List<PlaceAutocompleteMatchedSubstring> matchedSubstrings) {
            this.matchedSubstrings = matchedSubstrings;
            return this;
        }

        /**
         * Setter for structuredFormatting.
         * @param  structuredFormatting  PlaceAutocompleteStructuredFormat value for
         *         structuredFormatting.
         * @return Builder
         */
        public Builder structuredFormatting(
                PlaceAutocompleteStructuredFormat structuredFormatting) {
            this.structuredFormatting = structuredFormatting;
            return this;
        }

        /**
         * Setter for terms.
         * @param  terms  List of PlaceAutocompleteTerm value for terms.
         * @return Builder
         */
        public Builder terms(List<PlaceAutocompleteTerm> terms) {
            this.terms = terms;
            return this;
        }

        /**
         * Setter for placeId.
         * @param  placeId  String value for placeId.
         * @return Builder
         */
        public Builder placeId(String placeId) {
            this.placeId = placeId;
            return this;
        }

        /**
         * Setter for reference.
         * @param  reference  String value for reference.
         * @return Builder
         */
        public Builder reference(String reference) {
            this.reference = reference;
            return this;
        }

        /**
         * Setter for types.
         * @param  types  List of String value for types.
         * @return Builder
         */
        public Builder types(List<String> types) {
            this.types = types;
            return this;
        }

        /**
         * Setter for distanceMeters.
         * @param  distanceMeters  Integer value for distanceMeters.
         * @return Builder
         */
        public Builder distanceMeters(Integer distanceMeters) {
            this.distanceMeters = distanceMeters;
            return this;
        }

        /**
         * Setter for additional property that are not in model fields.
         * @param name The name of the additional property.
         * @param value The Object value of the additional property.
         * @return Builder.
         */
        public Builder additionalProperty(String name, Object value) {
            this.additionalProperties.setAdditionalProperty(name, value);
            return this;
        }

        /**
         * Builds a new {@link PlaceAutocompletePrediction} object using the set fields.
         * @return {@link PlaceAutocompletePrediction}
         */
        public PlaceAutocompletePrediction build() {
            PlaceAutocompletePrediction model =
                    new PlaceAutocompletePrediction(description, matchedSubstrings,
                            structuredFormatting, terms, placeId, reference, types, distanceMeters);
            model.additionalProperties = additionalProperties;
            return model;
        }
    }
}
