/*
 * GoogleMapsPlatformLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.googleapis.maps.models;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.AdditionalProperties;
import io.apimatic.core.utilities.ConversionHelper;
import java.util.Map;

/**
 * This is a model class for PlaceSpecialDay type.
 */
public class PlaceSpecialDay {
    private String date;
    private Boolean exceptionalHours;
    private AdditionalProperties<Object> additionalProperties = 
            new AdditionalProperties<Object>(this.getClass());

    /**
     * Default constructor.
     */
    public PlaceSpecialDay() {
    }

    /**
     * Initialization constructor.
     * @param  date  String value for date.
     * @param  exceptionalHours  Boolean value for exceptionalHours.
     */
    public PlaceSpecialDay(
            String date,
            Boolean exceptionalHours) {
        this.date = date;
        this.exceptionalHours = exceptionalHours;
    }

    /**
     * Getter for Date.
     * A date expressed in RFC3339 format in the local timezone for the place, for example
     * 2010-12-31.
     * @return Returns the String
     */
    @JsonGetter("date")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getDate() {
        return date;
    }

    /**
     * Setter for Date.
     * A date expressed in RFC3339 format in the local timezone for the place, for example
     * 2010-12-31.
     * @param date Value for String
     */
    @JsonSetter("date")
    public void setDate(String date) {
        this.date = date;
    }

    /**
     * Getter for ExceptionalHours.
     * True if there are exceptional hours for this day. If `true`, this means that there is at
     * least one exception for this day. Exceptions cause different values to occur in the subfields
     * of `current_opening_hours` and `secondary_opening_hours` such as `periods`, `weekday_text`,
     * `open_now`. The exceptions apply to the hours, and the hours are used to generate the other
     * fields.
     * @return Returns the Boolean
     */
    @JsonGetter("exceptional_hours")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Boolean getExceptionalHours() {
        return exceptionalHours;
    }

    /**
     * Setter for ExceptionalHours.
     * True if there are exceptional hours for this day. If `true`, this means that there is at
     * least one exception for this day. Exceptions cause different values to occur in the subfields
     * of `current_opening_hours` and `secondary_opening_hours` such as `periods`, `weekday_text`,
     * `open_now`. The exceptions apply to the hours, and the hours are used to generate the other
     * fields.
     * @param exceptionalHours Value for Boolean
     */
    @JsonSetter("exceptional_hours")
    public void setExceptionalHours(Boolean exceptionalHours) {
        this.exceptionalHours = exceptionalHours;
    }

    /**
     * Hidden method for the serialization of additional properties.
     * @return The map of additionally set properties.
     */
    @JsonAnyGetter
    private Map<String, Object> getAdditionalProperties() {
        return additionalProperties.getAdditionalProperties();
    }

    /**
     * Hidden method for the de-serialization of additional properties.
     * @param name The name of the additional property.
     * @param value The Object value of the additional property.
     */
    @JsonAnySetter
    private void setAdditionalProperties(String name, Object value) {
        additionalProperties.setAdditionalProperty(name,
                ConversionHelper.convertToSimpleType(value,
                        x -> x),
                true);
    }

    /**
     * Getter for the value of additional properties based on provided property name.
     * @param name The name of the additional property.
     * @return Either the Object property value or null if not exist.
     */
    
    public Object getAdditionalProperty(String name) {
        return additionalProperties.getAdditionalProperty(name);
    }

    /**
     * Converts this PlaceSpecialDay into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "PlaceSpecialDay [" + "date=" + date + ", exceptionalHours=" + exceptionalHours
                + ", additionalProperties=" + additionalProperties + "]";
    }

    /**
     * Builds a new {@link PlaceSpecialDay.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link PlaceSpecialDay.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .date(getDate())
                .exceptionalHours(getExceptionalHours());
        builder.additionalProperties = additionalProperties;
        return builder;
    }

    /**
     * Class to build instances of {@link PlaceSpecialDay}.
     */
    public static class Builder {
        private String date;
        private Boolean exceptionalHours;
        private AdditionalProperties<Object> additionalProperties =
                new AdditionalProperties<Object>();



        /**
         * Setter for date.
         * @param  date  String value for date.
         * @return Builder
         */
        public Builder date(String date) {
            this.date = date;
            return this;
        }

        /**
         * Setter for exceptionalHours.
         * @param  exceptionalHours  Boolean value for exceptionalHours.
         * @return Builder
         */
        public Builder exceptionalHours(Boolean exceptionalHours) {
            this.exceptionalHours = exceptionalHours;
            return this;
        }

        /**
         * Setter for additional property that are not in model fields.
         * @param name The name of the additional property.
         * @param value The Object value of the additional property.
         * @return Builder.
         */
        public Builder additionalProperty(String name, Object value) {
            this.additionalProperties.setAdditionalProperty(name, value);
            return this;
        }

        /**
         * Builds a new {@link PlaceSpecialDay} object using the set fields.
         * @return {@link PlaceSpecialDay}
         */
        public PlaceSpecialDay build() {
            PlaceSpecialDay model =
                    new PlaceSpecialDay(date, exceptionalHours);
            model.additionalProperties = additionalProperties;
            return model;
        }
    }
}
