/*
 * GoogleMapsPlatformLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.googleapis.maps.models;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.AdditionalProperties;
import io.apimatic.core.utilities.ConversionHelper;
import java.util.List;
import java.util.Map;

/**
 * This is a model class for Place type.
 */
public class Place {
    private List<AddressComponent> addressComponents;
    private String adrAddress;
    private BusinessStatus businessStatus;
    private Boolean curbsidePickup;
    private PlaceOpeningHours currentOpeningHours;
    private Boolean delivery;
    private Boolean dineIn;
    private PlaceEditorialSummary editorialSummary;
    private String formattedAddress;
    private String formattedPhoneNumber;
    private Geometry geometry;
    private String icon;
    private String iconBackgroundColor;
    private String iconMaskBaseUri;
    private String internationalPhoneNumber;
    private String name;
    private PlaceOpeningHours openingHours;
    private Boolean permanentlyClosed;
    private List<PlacePhoto> photos;
    private String placeId;
    private PlusCode plusCode;
    private Double priceLevel;
    private Double rating;
    private String reference;
    private Boolean reservable;
    private List<PlaceReview> reviews;
    private Boolean servesBeer;
    private Boolean servesBreakfast;
    private Boolean servesBrunch;
    private Boolean servesDinner;
    private Boolean servesLunch;
    private Boolean servesVegetarianFood;
    private Boolean servesWine;
    private String scope;
    private List<PlaceOpeningHours> secondaryOpeningHours;
    private Boolean takeout;
    private List<String> types;
    private String url;
    private Double userRatingsTotal;
    private Double utcOffset;
    private String vicinity;
    private String website;
    private Boolean wheelchairAccessibleEntrance;
    private AdditionalProperties<Object> additionalProperties = 
            new AdditionalProperties<Object>(this.getClass());

    /**
     * Default constructor.
     */
    public Place() {
    }

    /**
     * Initialization constructor.
     * @param  addressComponents  List of AddressComponent value for addressComponents.
     * @param  adrAddress  String value for adrAddress.
     * @param  businessStatus  BusinessStatus value for businessStatus.
     * @param  curbsidePickup  Boolean value for curbsidePickup.
     * @param  currentOpeningHours  PlaceOpeningHours value for currentOpeningHours.
     * @param  delivery  Boolean value for delivery.
     * @param  dineIn  Boolean value for dineIn.
     * @param  editorialSummary  PlaceEditorialSummary value for editorialSummary.
     * @param  formattedAddress  String value for formattedAddress.
     * @param  formattedPhoneNumber  String value for formattedPhoneNumber.
     * @param  geometry  Geometry value for geometry.
     * @param  icon  String value for icon.
     * @param  iconBackgroundColor  String value for iconBackgroundColor.
     * @param  iconMaskBaseUri  String value for iconMaskBaseUri.
     * @param  internationalPhoneNumber  String value for internationalPhoneNumber.
     * @param  name  String value for name.
     * @param  openingHours  PlaceOpeningHours value for openingHours.
     * @param  permanentlyClosed  Boolean value for permanentlyClosed.
     * @param  photos  List of PlacePhoto value for photos.
     * @param  placeId  String value for placeId.
     * @param  plusCode  PlusCode value for plusCode.
     * @param  priceLevel  Double value for priceLevel.
     * @param  rating  Double value for rating.
     * @param  reference  String value for reference.
     * @param  reservable  Boolean value for reservable.
     * @param  reviews  List of PlaceReview value for reviews.
     * @param  servesBeer  Boolean value for servesBeer.
     * @param  servesBreakfast  Boolean value for servesBreakfast.
     * @param  servesBrunch  Boolean value for servesBrunch.
     * @param  servesDinner  Boolean value for servesDinner.
     * @param  servesLunch  Boolean value for servesLunch.
     * @param  servesVegetarianFood  Boolean value for servesVegetarianFood.
     * @param  servesWine  Boolean value for servesWine.
     * @param  scope  String value for scope.
     * @param  secondaryOpeningHours  List of PlaceOpeningHours value for secondaryOpeningHours.
     * @param  takeout  Boolean value for takeout.
     * @param  types  List of String value for types.
     * @param  url  String value for url.
     * @param  userRatingsTotal  Double value for userRatingsTotal.
     * @param  utcOffset  Double value for utcOffset.
     * @param  vicinity  String value for vicinity.
     * @param  website  String value for website.
     * @param  wheelchairAccessibleEntrance  Boolean value for wheelchairAccessibleEntrance.
     */
    public Place(
            List<AddressComponent> addressComponents,
            String adrAddress,
            BusinessStatus businessStatus,
            Boolean curbsidePickup,
            PlaceOpeningHours currentOpeningHours,
            Boolean delivery,
            Boolean dineIn,
            PlaceEditorialSummary editorialSummary,
            String formattedAddress,
            String formattedPhoneNumber,
            Geometry geometry,
            String icon,
            String iconBackgroundColor,
            String iconMaskBaseUri,
            String internationalPhoneNumber,
            String name,
            PlaceOpeningHours openingHours,
            Boolean permanentlyClosed,
            List<PlacePhoto> photos,
            String placeId,
            PlusCode plusCode,
            Double priceLevel,
            Double rating,
            String reference,
            Boolean reservable,
            List<PlaceReview> reviews,
            Boolean servesBeer,
            Boolean servesBreakfast,
            Boolean servesBrunch,
            Boolean servesDinner,
            Boolean servesLunch,
            Boolean servesVegetarianFood,
            Boolean servesWine,
            String scope,
            List<PlaceOpeningHours> secondaryOpeningHours,
            Boolean takeout,
            List<String> types,
            String url,
            Double userRatingsTotal,
            Double utcOffset,
            String vicinity,
            String website,
            Boolean wheelchairAccessibleEntrance) {
        this.addressComponents = addressComponents;
        this.adrAddress = adrAddress;
        this.businessStatus = businessStatus;
        this.curbsidePickup = curbsidePickup;
        this.currentOpeningHours = currentOpeningHours;
        this.delivery = delivery;
        this.dineIn = dineIn;
        this.editorialSummary = editorialSummary;
        this.formattedAddress = formattedAddress;
        this.formattedPhoneNumber = formattedPhoneNumber;
        this.geometry = geometry;
        this.icon = icon;
        this.iconBackgroundColor = iconBackgroundColor;
        this.iconMaskBaseUri = iconMaskBaseUri;
        this.internationalPhoneNumber = internationalPhoneNumber;
        this.name = name;
        this.openingHours = openingHours;
        this.permanentlyClosed = permanentlyClosed;
        this.photos = photos;
        this.placeId = placeId;
        this.plusCode = plusCode;
        this.priceLevel = priceLevel;
        this.rating = rating;
        this.reference = reference;
        this.reservable = reservable;
        this.reviews = reviews;
        this.servesBeer = servesBeer;
        this.servesBreakfast = servesBreakfast;
        this.servesBrunch = servesBrunch;
        this.servesDinner = servesDinner;
        this.servesLunch = servesLunch;
        this.servesVegetarianFood = servesVegetarianFood;
        this.servesWine = servesWine;
        this.scope = scope;
        this.secondaryOpeningHours = secondaryOpeningHours;
        this.takeout = takeout;
        this.types = types;
        this.url = url;
        this.userRatingsTotal = userRatingsTotal;
        this.utcOffset = utcOffset;
        this.vicinity = vicinity;
        this.website = website;
        this.wheelchairAccessibleEntrance = wheelchairAccessibleEntrance;
    }

    /**
     * Getter for AddressComponents.
     * An array containing the separate components applicable to this address.
     * @return Returns the List of AddressComponent
     */
    @JsonGetter("address_components")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public List<AddressComponent> getAddressComponents() {
        return addressComponents;
    }

    /**
     * Setter for AddressComponents.
     * An array containing the separate components applicable to this address.
     * @param addressComponents Value for List of AddressComponent
     */
    @JsonSetter("address_components")
    public void setAddressComponents(List<AddressComponent> addressComponents) {
        this.addressComponents = addressComponents;
    }

    /**
     * Getter for AdrAddress.
     * A representation of the place's address in the [adr
     * microformat](http://microformats.org/wiki/adr).
     * @return Returns the String
     */
    @JsonGetter("adr_address")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getAdrAddress() {
        return adrAddress;
    }

    /**
     * Setter for AdrAddress.
     * A representation of the place's address in the [adr
     * microformat](http://microformats.org/wiki/adr).
     * @param adrAddress Value for String
     */
    @JsonSetter("adr_address")
    public void setAdrAddress(String adrAddress) {
        this.adrAddress = adrAddress;
    }

    /**
     * Getter for BusinessStatus.
     * Indicates the operational status of the place, if it is a business. If no data exists,
     * `business_status` is not returned.
     * @return Returns the BusinessStatus
     */
    @JsonGetter("business_status")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public BusinessStatus getBusinessStatus() {
        return businessStatus;
    }

    /**
     * Setter for BusinessStatus.
     * Indicates the operational status of the place, if it is a business. If no data exists,
     * `business_status` is not returned.
     * @param businessStatus Value for BusinessStatus
     */
    @JsonSetter("business_status")
    public void setBusinessStatus(BusinessStatus businessStatus) {
        this.businessStatus = businessStatus;
    }

    /**
     * Getter for CurbsidePickup.
     * Specifies if the business supports curbside pickup.
     * @return Returns the Boolean
     */
    @JsonGetter("curbside_pickup")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Boolean getCurbsidePickup() {
        return curbsidePickup;
    }

    /**
     * Setter for CurbsidePickup.
     * Specifies if the business supports curbside pickup.
     * @param curbsidePickup Value for Boolean
     */
    @JsonSetter("curbside_pickup")
    public void setCurbsidePickup(Boolean curbsidePickup) {
        this.curbsidePickup = curbsidePickup;
    }

    /**
     * Getter for CurrentOpeningHours.
     * An object describing the opening hours of a place.
     * @return Returns the PlaceOpeningHours
     */
    @JsonGetter("current_opening_hours")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public PlaceOpeningHours getCurrentOpeningHours() {
        return currentOpeningHours;
    }

    /**
     * Setter for CurrentOpeningHours.
     * An object describing the opening hours of a place.
     * @param currentOpeningHours Value for PlaceOpeningHours
     */
    @JsonSetter("current_opening_hours")
    public void setCurrentOpeningHours(PlaceOpeningHours currentOpeningHours) {
        this.currentOpeningHours = currentOpeningHours;
    }

    /**
     * Getter for Delivery.
     * Specifies if the business supports delivery.
     * @return Returns the Boolean
     */
    @JsonGetter("delivery")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Boolean getDelivery() {
        return delivery;
    }

    /**
     * Setter for Delivery.
     * Specifies if the business supports delivery.
     * @param delivery Value for Boolean
     */
    @JsonSetter("delivery")
    public void setDelivery(Boolean delivery) {
        this.delivery = delivery;
    }

    /**
     * Getter for DineIn.
     * Specifies if the business supports indoor or outdoor seating options.
     * @return Returns the Boolean
     */
    @JsonGetter("dine_in")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Boolean getDineIn() {
        return dineIn;
    }

    /**
     * Setter for DineIn.
     * Specifies if the business supports indoor or outdoor seating options.
     * @param dineIn Value for Boolean
     */
    @JsonSetter("dine_in")
    public void setDineIn(Boolean dineIn) {
        this.dineIn = dineIn;
    }

    /**
     * Getter for EditorialSummary.
     * Contains a summary of the place. A summary is comprised of a textual overview, and also
     * includes the language code for these if applicable. Summary text must be presented as-is and
     * can not be modified or altered.
     * @return Returns the PlaceEditorialSummary
     */
    @JsonGetter("editorial_summary")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public PlaceEditorialSummary getEditorialSummary() {
        return editorialSummary;
    }

    /**
     * Setter for EditorialSummary.
     * Contains a summary of the place. A summary is comprised of a textual overview, and also
     * includes the language code for these if applicable. Summary text must be presented as-is and
     * can not be modified or altered.
     * @param editorialSummary Value for PlaceEditorialSummary
     */
    @JsonSetter("editorial_summary")
    public void setEditorialSummary(PlaceEditorialSummary editorialSummary) {
        this.editorialSummary = editorialSummary;
    }

    /**
     * Getter for FormattedAddress.
     * A string containing the human-readable address of this place. Often this address is
     * equivalent to the postal address. Note that some countries, such as the United Kingdom, do
     * not allow distribution of true postal addresses due to licensing restrictions. The formatted
     * address is logically composed of one or more address components. For example, the address
     * "111 8th Avenue, New York, NY" consists of the following components: "111" (the street
     * number), "8th Avenue" (the route), "New York" (the city) and "NY" (the US state). Do not
     * parse the formatted address programmatically. Instead you should use the individual address
     * components, which the API response includes in addition to the formatted address field.
     * @return Returns the String
     */
    @JsonGetter("formatted_address")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getFormattedAddress() {
        return formattedAddress;
    }

    /**
     * Setter for FormattedAddress.
     * A string containing the human-readable address of this place. Often this address is
     * equivalent to the postal address. Note that some countries, such as the United Kingdom, do
     * not allow distribution of true postal addresses due to licensing restrictions. The formatted
     * address is logically composed of one or more address components. For example, the address
     * "111 8th Avenue, New York, NY" consists of the following components: "111" (the street
     * number), "8th Avenue" (the route), "New York" (the city) and "NY" (the US state). Do not
     * parse the formatted address programmatically. Instead you should use the individual address
     * components, which the API response includes in addition to the formatted address field.
     * @param formattedAddress Value for String
     */
    @JsonSetter("formatted_address")
    public void setFormattedAddress(String formattedAddress) {
        this.formattedAddress = formattedAddress;
    }

    /**
     * Getter for FormattedPhoneNumber.
     * Contains the place's phone number in its [local
     * format](http://en.wikipedia.org/wiki/Local_conventions_for_writing_telephone_numbers).
     * @return Returns the String
     */
    @JsonGetter("formatted_phone_number")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getFormattedPhoneNumber() {
        return formattedPhoneNumber;
    }

    /**
     * Setter for FormattedPhoneNumber.
     * Contains the place's phone number in its [local
     * format](http://en.wikipedia.org/wiki/Local_conventions_for_writing_telephone_numbers).
     * @param formattedPhoneNumber Value for String
     */
    @JsonSetter("formatted_phone_number")
    public void setFormattedPhoneNumber(String formattedPhoneNumber) {
        this.formattedPhoneNumber = formattedPhoneNumber;
    }

    /**
     * Getter for Geometry.
     * An object describing the location.
     * @return Returns the Geometry
     */
    @JsonGetter("geometry")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Geometry getGeometry() {
        return geometry;
    }

    /**
     * Setter for Geometry.
     * An object describing the location.
     * @param geometry Value for Geometry
     */
    @JsonSetter("geometry")
    public void setGeometry(Geometry geometry) {
        this.geometry = geometry;
    }

    /**
     * Getter for Icon.
     * Contains the URL of a suggested icon which may be displayed to the user when indicating this
     * result on a map.
     * @return Returns the String
     */
    @JsonGetter("icon")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getIcon() {
        return icon;
    }

    /**
     * Setter for Icon.
     * Contains the URL of a suggested icon which may be displayed to the user when indicating this
     * result on a map.
     * @param icon Value for String
     */
    @JsonSetter("icon")
    public void setIcon(String icon) {
        this.icon = icon;
    }

    /**
     * Getter for IconBackgroundColor.
     * Contains the default HEX color code for the place's category.
     * @return Returns the String
     */
    @JsonGetter("icon_background_color")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getIconBackgroundColor() {
        return iconBackgroundColor;
    }

    /**
     * Setter for IconBackgroundColor.
     * Contains the default HEX color code for the place's category.
     * @param iconBackgroundColor Value for String
     */
    @JsonSetter("icon_background_color")
    public void setIconBackgroundColor(String iconBackgroundColor) {
        this.iconBackgroundColor = iconBackgroundColor;
    }

    /**
     * Getter for IconMaskBaseUri.
     * Contains the URL of a recommended icon, minus the `.svg` or `.png` file type extension.
     * @return Returns the String
     */
    @JsonGetter("icon_mask_base_uri")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getIconMaskBaseUri() {
        return iconMaskBaseUri;
    }

    /**
     * Setter for IconMaskBaseUri.
     * Contains the URL of a recommended icon, minus the `.svg` or `.png` file type extension.
     * @param iconMaskBaseUri Value for String
     */
    @JsonSetter("icon_mask_base_uri")
    public void setIconMaskBaseUri(String iconMaskBaseUri) {
        this.iconMaskBaseUri = iconMaskBaseUri;
    }

    /**
     * Getter for InternationalPhoneNumber.
     * Contains the place's phone number in international format. International format includes the
     * country code, and is prefixed with the plus, +, sign. For example, the
     * international_phone_number for Google's Sydney, Australia office is `+61 2 9374 4000`.
     * @return Returns the String
     */
    @JsonGetter("international_phone_number")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getInternationalPhoneNumber() {
        return internationalPhoneNumber;
    }

    /**
     * Setter for InternationalPhoneNumber.
     * Contains the place's phone number in international format. International format includes the
     * country code, and is prefixed with the plus, +, sign. For example, the
     * international_phone_number for Google's Sydney, Australia office is `+61 2 9374 4000`.
     * @param internationalPhoneNumber Value for String
     */
    @JsonSetter("international_phone_number")
    public void setInternationalPhoneNumber(String internationalPhoneNumber) {
        this.internationalPhoneNumber = internationalPhoneNumber;
    }

    /**
     * Getter for Name.
     * Contains the human-readable name for the returned result. For `establishment` results, this
     * is usually the canonicalized business name.
     * @return Returns the String
     */
    @JsonGetter("name")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getName() {
        return name;
    }

    /**
     * Setter for Name.
     * Contains the human-readable name for the returned result. For `establishment` results, this
     * is usually the canonicalized business name.
     * @param name Value for String
     */
    @JsonSetter("name")
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Getter for OpeningHours.
     * An object describing the opening hours of a place.
     * @return Returns the PlaceOpeningHours
     */
    @JsonGetter("opening_hours")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public PlaceOpeningHours getOpeningHours() {
        return openingHours;
    }

    /**
     * Setter for OpeningHours.
     * An object describing the opening hours of a place.
     * @param openingHours Value for PlaceOpeningHours
     */
    @JsonSetter("opening_hours")
    public void setOpeningHours(PlaceOpeningHours openingHours) {
        this.openingHours = openingHours;
    }

    /**
     * Getter for PermanentlyClosed.
     * Use `business_status` to get the operational status of businesses.
     * @return Returns the Boolean
     */
    @JsonGetter("permanently_closed")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Boolean getPermanentlyClosed() {
        return permanentlyClosed;
    }

    /**
     * Setter for PermanentlyClosed.
     * Use `business_status` to get the operational status of businesses.
     * @param permanentlyClosed Value for Boolean
     */
    @JsonSetter("permanently_closed")
    public void setPermanentlyClosed(Boolean permanentlyClosed) {
        this.permanentlyClosed = permanentlyClosed;
    }

    /**
     * Getter for Photos.
     * An array of photo objects, each containing a reference to an image. A request may return up
     * to ten photos. More information about place photos and how you can use the images in your
     * application can be found in the [Place
     * Photos](https://developers.google.com/maps/documentation/places/web-service/photos)
     * documentation.
     * @return Returns the List of PlacePhoto
     */
    @JsonGetter("photos")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public List<PlacePhoto> getPhotos() {
        return photos;
    }

    /**
     * Setter for Photos.
     * An array of photo objects, each containing a reference to an image. A request may return up
     * to ten photos. More information about place photos and how you can use the images in your
     * application can be found in the [Place
     * Photos](https://developers.google.com/maps/documentation/places/web-service/photos)
     * documentation.
     * @param photos Value for List of PlacePhoto
     */
    @JsonSetter("photos")
    public void setPhotos(List<PlacePhoto> photos) {
        this.photos = photos;
    }

    /**
     * Getter for PlaceId.
     * A textual identifier that uniquely identifies a place. To retrieve information about the
     * place, pass this identifier in the `place_id` field of a Places API request. For more
     * information about place IDs, see the [place ID
     * overview](https://developers.google.com/maps/documentation/places/web-service/place-id).
     * @return Returns the String
     */
    @JsonGetter("place_id")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getPlaceId() {
        return placeId;
    }

    /**
     * Setter for PlaceId.
     * A textual identifier that uniquely identifies a place. To retrieve information about the
     * place, pass this identifier in the `place_id` field of a Places API request. For more
     * information about place IDs, see the [place ID
     * overview](https://developers.google.com/maps/documentation/places/web-service/place-id).
     * @param placeId Value for String
     */
    @JsonSetter("place_id")
    public void setPlaceId(String placeId) {
        this.placeId = placeId;
    }

    /**
     * Getter for PlusCode.
     * An encoded location reference, derived from latitude and longitude coordinates, that
     * represents an area, 1/8000th of a degree by 1/8000th of a degree (about 14m x 14m at the
     * equator) or smaller. Plus codes can be used as a replacement for street addresses in places
     * where they do not exist (where buildings are not numbered or streets are not named).
     * @return Returns the PlusCode
     */
    @JsonGetter("plus_code")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public PlusCode getPlusCode() {
        return plusCode;
    }

    /**
     * Setter for PlusCode.
     * An encoded location reference, derived from latitude and longitude coordinates, that
     * represents an area, 1/8000th of a degree by 1/8000th of a degree (about 14m x 14m at the
     * equator) or smaller. Plus codes can be used as a replacement for street addresses in places
     * where they do not exist (where buildings are not numbered or streets are not named).
     * @param plusCode Value for PlusCode
     */
    @JsonSetter("plus_code")
    public void setPlusCode(PlusCode plusCode) {
        this.plusCode = plusCode;
    }

    /**
     * Getter for PriceLevel.
     * The price level of the place, on a scale of 0 to 4. The exact amount indicated by a specific
     * value will vary from region to region. Price levels are interpreted as follows: - 0 Free - 1
     * Inexpensive - 2 Moderate - 3 Expensive - 4 Very Expensive
     * @return Returns the Double
     */
    @JsonGetter("price_level")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Double getPriceLevel() {
        return priceLevel;
    }

    /**
     * Setter for PriceLevel.
     * The price level of the place, on a scale of 0 to 4. The exact amount indicated by a specific
     * value will vary from region to region. Price levels are interpreted as follows: - 0 Free - 1
     * Inexpensive - 2 Moderate - 3 Expensive - 4 Very Expensive
     * @param priceLevel Value for Double
     */
    @JsonSetter("price_level")
    public void setPriceLevel(Double priceLevel) {
        this.priceLevel = priceLevel;
    }

    /**
     * Getter for Rating.
     * Contains the place's rating, from 1.0 to 5.0, based on aggregated user reviews.
     * @return Returns the Double
     */
    @JsonGetter("rating")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Double getRating() {
        return rating;
    }

    /**
     * Setter for Rating.
     * Contains the place's rating, from 1.0 to 5.0, based on aggregated user reviews.
     * @param rating Value for Double
     */
    @JsonSetter("rating")
    public void setRating(Double rating) {
        this.rating = rating;
    }

    /**
     * Getter for Reference.
     * @return Returns the String
     */
    @JsonGetter("reference")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getReference() {
        return reference;
    }

    /**
     * Setter for Reference.
     * @param reference Value for String
     */
    @JsonSetter("reference")
    public void setReference(String reference) {
        this.reference = reference;
    }

    /**
     * Getter for Reservable.
     * Specifies if the place supports reservations.
     * @return Returns the Boolean
     */
    @JsonGetter("reservable")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Boolean getReservable() {
        return reservable;
    }

    /**
     * Setter for Reservable.
     * Specifies if the place supports reservations.
     * @param reservable Value for Boolean
     */
    @JsonSetter("reservable")
    public void setReservable(Boolean reservable) {
        this.reservable = reservable;
    }

    /**
     * Getter for Reviews.
     * A JSON array of up to five reviews. By default, the reviews are sorted in order of relevance.
     * Use the `reviews_sort` request parameter to control sorting. - For `most_relevant` (default),
     * reviews are sorted by relevance; the service will bias the results to return reviews
     * originally written in the preferred language. - For `newest`, reviews are sorted in
     * chronological order; the preferred language does not affect the sort order. Google recommends
     * indicating to users whether results are ordered by `most_relevant` or `newest`.
     * @return Returns the List of PlaceReview
     */
    @JsonGetter("reviews")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public List<PlaceReview> getReviews() {
        return reviews;
    }

    /**
     * Setter for Reviews.
     * A JSON array of up to five reviews. By default, the reviews are sorted in order of relevance.
     * Use the `reviews_sort` request parameter to control sorting. - For `most_relevant` (default),
     * reviews are sorted by relevance; the service will bias the results to return reviews
     * originally written in the preferred language. - For `newest`, reviews are sorted in
     * chronological order; the preferred language does not affect the sort order. Google recommends
     * indicating to users whether results are ordered by `most_relevant` or `newest`.
     * @param reviews Value for List of PlaceReview
     */
    @JsonSetter("reviews")
    public void setReviews(List<PlaceReview> reviews) {
        this.reviews = reviews;
    }

    /**
     * Getter for ServesBeer.
     * Specifies if the place serves beer.
     * @return Returns the Boolean
     */
    @JsonGetter("serves_beer")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Boolean getServesBeer() {
        return servesBeer;
    }

    /**
     * Setter for ServesBeer.
     * Specifies if the place serves beer.
     * @param servesBeer Value for Boolean
     */
    @JsonSetter("serves_beer")
    public void setServesBeer(Boolean servesBeer) {
        this.servesBeer = servesBeer;
    }

    /**
     * Getter for ServesBreakfast.
     * Specifies if the place serves breakfast.
     * @return Returns the Boolean
     */
    @JsonGetter("serves_breakfast")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Boolean getServesBreakfast() {
        return servesBreakfast;
    }

    /**
     * Setter for ServesBreakfast.
     * Specifies if the place serves breakfast.
     * @param servesBreakfast Value for Boolean
     */
    @JsonSetter("serves_breakfast")
    public void setServesBreakfast(Boolean servesBreakfast) {
        this.servesBreakfast = servesBreakfast;
    }

    /**
     * Getter for ServesBrunch.
     * Specifies if the place serves brunch.
     * @return Returns the Boolean
     */
    @JsonGetter("serves_brunch")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Boolean getServesBrunch() {
        return servesBrunch;
    }

    /**
     * Setter for ServesBrunch.
     * Specifies if the place serves brunch.
     * @param servesBrunch Value for Boolean
     */
    @JsonSetter("serves_brunch")
    public void setServesBrunch(Boolean servesBrunch) {
        this.servesBrunch = servesBrunch;
    }

    /**
     * Getter for ServesDinner.
     * Specifies if the place serves dinner.
     * @return Returns the Boolean
     */
    @JsonGetter("serves_dinner")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Boolean getServesDinner() {
        return servesDinner;
    }

    /**
     * Setter for ServesDinner.
     * Specifies if the place serves dinner.
     * @param servesDinner Value for Boolean
     */
    @JsonSetter("serves_dinner")
    public void setServesDinner(Boolean servesDinner) {
        this.servesDinner = servesDinner;
    }

    /**
     * Getter for ServesLunch.
     * Specifies if the place serves lunch.
     * @return Returns the Boolean
     */
    @JsonGetter("serves_lunch")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Boolean getServesLunch() {
        return servesLunch;
    }

    /**
     * Setter for ServesLunch.
     * Specifies if the place serves lunch.
     * @param servesLunch Value for Boolean
     */
    @JsonSetter("serves_lunch")
    public void setServesLunch(Boolean servesLunch) {
        this.servesLunch = servesLunch;
    }

    /**
     * Getter for ServesVegetarianFood.
     * Specifies if the place serves vegetarian food.
     * @return Returns the Boolean
     */
    @JsonGetter("serves_vegetarian_food")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Boolean getServesVegetarianFood() {
        return servesVegetarianFood;
    }

    /**
     * Setter for ServesVegetarianFood.
     * Specifies if the place serves vegetarian food.
     * @param servesVegetarianFood Value for Boolean
     */
    @JsonSetter("serves_vegetarian_food")
    public void setServesVegetarianFood(Boolean servesVegetarianFood) {
        this.servesVegetarianFood = servesVegetarianFood;
    }

    /**
     * Getter for ServesWine.
     * Specifies if the place serves wine.
     * @return Returns the Boolean
     */
    @JsonGetter("serves_wine")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Boolean getServesWine() {
        return servesWine;
    }

    /**
     * Setter for ServesWine.
     * Specifies if the place serves wine.
     * @param servesWine Value for Boolean
     */
    @JsonSetter("serves_wine")
    public void setServesWine(Boolean servesWine) {
        this.servesWine = servesWine;
    }

    /**
     * Getter for Scope.
     * @return Returns the String
     */
    @JsonGetter("scope")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getScope() {
        return scope;
    }

    /**
     * Setter for Scope.
     * @param scope Value for String
     */
    @JsonSetter("scope")
    public void setScope(String scope) {
        this.scope = scope;
    }

    /**
     * Getter for SecondaryOpeningHours.
     * Contains an array of entries for the next seven days including information about secondary
     * hours of a business. Secondary hours are different from a business's main hours. For example,
     * a restaurant can specify drive through hours or delivery hours as its secondary hours. This
     * field populates the `type` subfield, which draws from a predefined list of opening hours
     * types (such as `DRIVE_THROUGH`, `PICKUP`, or `TAKEOUT`) based on the types of the place. This
     * field includes the `special_days` subfield of all hours, set for dates that have exceptional
     * hours.
     * @return Returns the List of PlaceOpeningHours
     */
    @JsonGetter("secondary_opening_hours")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public List<PlaceOpeningHours> getSecondaryOpeningHours() {
        return secondaryOpeningHours;
    }

    /**
     * Setter for SecondaryOpeningHours.
     * Contains an array of entries for the next seven days including information about secondary
     * hours of a business. Secondary hours are different from a business's main hours. For example,
     * a restaurant can specify drive through hours or delivery hours as its secondary hours. This
     * field populates the `type` subfield, which draws from a predefined list of opening hours
     * types (such as `DRIVE_THROUGH`, `PICKUP`, or `TAKEOUT`) based on the types of the place. This
     * field includes the `special_days` subfield of all hours, set for dates that have exceptional
     * hours.
     * @param secondaryOpeningHours Value for List of PlaceOpeningHours
     */
    @JsonSetter("secondary_opening_hours")
    public void setSecondaryOpeningHours(List<PlaceOpeningHours> secondaryOpeningHours) {
        this.secondaryOpeningHours = secondaryOpeningHours;
    }

    /**
     * Getter for Takeout.
     * Specifies if the business supports takeout.
     * @return Returns the Boolean
     */
    @JsonGetter("takeout")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Boolean getTakeout() {
        return takeout;
    }

    /**
     * Setter for Takeout.
     * Specifies if the business supports takeout.
     * @param takeout Value for Boolean
     */
    @JsonSetter("takeout")
    public void setTakeout(Boolean takeout) {
        this.takeout = takeout;
    }

    /**
     * Getter for Types.
     * Contains an array of feature types describing the given result. See the list of [supported
     * types](https://developers.google.com/maps/documentation/places/web-service/supported_types#table2).
     * @return Returns the List of String
     */
    @JsonGetter("types")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public List<String> getTypes() {
        return types;
    }

    /**
     * Setter for Types.
     * Contains an array of feature types describing the given result. See the list of [supported
     * types](https://developers.google.com/maps/documentation/places/web-service/supported_types#table2).
     * @param types Value for List of String
     */
    @JsonSetter("types")
    public void setTypes(List<String> types) {
        this.types = types;
    }

    /**
     * Getter for Url.
     * Contains the URL of the official Google page for this place. This will be the Google-owned
     * page that contains the best available information about the place. Applications must link to
     * or embed this page on any screen that shows detailed results about the place to the user.
     * @return Returns the String
     */
    @JsonGetter("url")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getUrl() {
        return url;
    }

    /**
     * Setter for Url.
     * Contains the URL of the official Google page for this place. This will be the Google-owned
     * page that contains the best available information about the place. Applications must link to
     * or embed this page on any screen that shows detailed results about the place to the user.
     * @param url Value for String
     */
    @JsonSetter("url")
    public void setUrl(String url) {
        this.url = url;
    }

    /**
     * Getter for UserRatingsTotal.
     * The total number of reviews, with or without text, for this place.
     * @return Returns the Double
     */
    @JsonGetter("user_ratings_total")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Double getUserRatingsTotal() {
        return userRatingsTotal;
    }

    /**
     * Setter for UserRatingsTotal.
     * The total number of reviews, with or without text, for this place.
     * @param userRatingsTotal Value for Double
     */
    @JsonSetter("user_ratings_total")
    public void setUserRatingsTotal(Double userRatingsTotal) {
        this.userRatingsTotal = userRatingsTotal;
    }

    /**
     * Getter for UtcOffset.
     * Contains the number of minutes this place’s current timezone is offset from UTC. For example,
     * for places in Sydney, Australia during daylight saving time this would be 660 (+11 hours from
     * UTC), and for places in California outside of daylight saving time this would be -480 (-8
     * hours from UTC).
     * @return Returns the Double
     */
    @JsonGetter("utc_offset")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Double getUtcOffset() {
        return utcOffset;
    }

    /**
     * Setter for UtcOffset.
     * Contains the number of minutes this place’s current timezone is offset from UTC. For example,
     * for places in Sydney, Australia during daylight saving time this would be 660 (+11 hours from
     * UTC), and for places in California outside of daylight saving time this would be -480 (-8
     * hours from UTC).
     * @param utcOffset Value for Double
     */
    @JsonSetter("utc_offset")
    public void setUtcOffset(Double utcOffset) {
        this.utcOffset = utcOffset;
    }

    /**
     * Getter for Vicinity.
     * For establishment (`types:["establishment", ...])` results only, the `vicinity` field
     * contains a simplified address for the place, including the street name, street number, and
     * locality, but not the province/state, postal code, or country. For all other results, the
     * `vicinity` field contains the name of the narrowest political (`types:["political", ...]`)
     * feature that is present in the address of the result. This content is meant to be read as-is.
     * Do not programmatically parse the formatted address.
     * @return Returns the String
     */
    @JsonGetter("vicinity")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getVicinity() {
        return vicinity;
    }

    /**
     * Setter for Vicinity.
     * For establishment (`types:["establishment", ...])` results only, the `vicinity` field
     * contains a simplified address for the place, including the street name, street number, and
     * locality, but not the province/state, postal code, or country. For all other results, the
     * `vicinity` field contains the name of the narrowest political (`types:["political", ...]`)
     * feature that is present in the address of the result. This content is meant to be read as-is.
     * Do not programmatically parse the formatted address.
     * @param vicinity Value for String
     */
    @JsonSetter("vicinity")
    public void setVicinity(String vicinity) {
        this.vicinity = vicinity;
    }

    /**
     * Getter for Website.
     * The authoritative website for this place, such as a business' homepage.
     * @return Returns the String
     */
    @JsonGetter("website")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getWebsite() {
        return website;
    }

    /**
     * Setter for Website.
     * The authoritative website for this place, such as a business' homepage.
     * @param website Value for String
     */
    @JsonSetter("website")
    public void setWebsite(String website) {
        this.website = website;
    }

    /**
     * Getter for WheelchairAccessibleEntrance.
     * Specifies if the place has an entrance that is wheelchair-accessible.
     * @return Returns the Boolean
     */
    @JsonGetter("wheelchair_accessible_entrance")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Boolean getWheelchairAccessibleEntrance() {
        return wheelchairAccessibleEntrance;
    }

    /**
     * Setter for WheelchairAccessibleEntrance.
     * Specifies if the place has an entrance that is wheelchair-accessible.
     * @param wheelchairAccessibleEntrance Value for Boolean
     */
    @JsonSetter("wheelchair_accessible_entrance")
    public void setWheelchairAccessibleEntrance(Boolean wheelchairAccessibleEntrance) {
        this.wheelchairAccessibleEntrance = wheelchairAccessibleEntrance;
    }

    /**
     * Hidden method for the serialization of additional properties.
     * @return The map of additionally set properties.
     */
    @JsonAnyGetter
    private Map<String, Object> getAdditionalProperties() {
        return additionalProperties.getAdditionalProperties();
    }

    /**
     * Hidden method for the de-serialization of additional properties.
     * @param name The name of the additional property.
     * @param value The Object value of the additional property.
     */
    @JsonAnySetter
    private void setAdditionalProperties(String name, Object value) {
        additionalProperties.setAdditionalProperty(name,
                ConversionHelper.convertToSimpleType(value,
                        x -> x),
                true);
    }

    /**
     * Getter for the value of additional properties based on provided property name.
     * @param name The name of the additional property.
     * @return Either the Object property value or null if not exist.
     */
    
    public Object getAdditionalProperty(String name) {
        return additionalProperties.getAdditionalProperty(name);
    }

    /**
     * Converts this Place into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "Place [" + "addressComponents=" + addressComponents + ", adrAddress=" + adrAddress
                + ", businessStatus=" + businessStatus + ", curbsidePickup=" + curbsidePickup
                + ", currentOpeningHours=" + currentOpeningHours + ", delivery=" + delivery
                + ", dineIn=" + dineIn + ", editorialSummary=" + editorialSummary
                + ", formattedAddress=" + formattedAddress + ", formattedPhoneNumber="
                + formattedPhoneNumber + ", geometry=" + geometry + ", icon=" + icon
                + ", iconBackgroundColor=" + iconBackgroundColor + ", iconMaskBaseUri="
                + iconMaskBaseUri + ", internationalPhoneNumber=" + internationalPhoneNumber
                + ", name=" + name + ", openingHours=" + openingHours + ", permanentlyClosed="
                + permanentlyClosed + ", photos=" + photos + ", placeId=" + placeId + ", plusCode="
                + plusCode + ", priceLevel=" + priceLevel + ", rating=" + rating + ", reference="
                + reference + ", reservable=" + reservable + ", reviews=" + reviews
                + ", servesBeer=" + servesBeer + ", servesBreakfast=" + servesBreakfast
                + ", servesBrunch=" + servesBrunch + ", servesDinner=" + servesDinner
                + ", servesLunch=" + servesLunch + ", servesVegetarianFood=" + servesVegetarianFood
                + ", servesWine=" + servesWine + ", scope=" + scope + ", secondaryOpeningHours="
                + secondaryOpeningHours + ", takeout=" + takeout + ", types=" + types + ", url="
                + url + ", userRatingsTotal=" + userRatingsTotal + ", utcOffset=" + utcOffset
                + ", vicinity=" + vicinity + ", website=" + website
                + ", wheelchairAccessibleEntrance=" + wheelchairAccessibleEntrance
                + ", additionalProperties=" + additionalProperties + "]";
    }

    /**
     * Builds a new {@link Place.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link Place.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .addressComponents(getAddressComponents())
                .adrAddress(getAdrAddress())
                .businessStatus(getBusinessStatus())
                .curbsidePickup(getCurbsidePickup())
                .currentOpeningHours(getCurrentOpeningHours())
                .delivery(getDelivery())
                .dineIn(getDineIn())
                .editorialSummary(getEditorialSummary())
                .formattedAddress(getFormattedAddress())
                .formattedPhoneNumber(getFormattedPhoneNumber())
                .geometry(getGeometry())
                .icon(getIcon())
                .iconBackgroundColor(getIconBackgroundColor())
                .iconMaskBaseUri(getIconMaskBaseUri())
                .internationalPhoneNumber(getInternationalPhoneNumber())
                .name(getName())
                .openingHours(getOpeningHours())
                .permanentlyClosed(getPermanentlyClosed())
                .photos(getPhotos())
                .placeId(getPlaceId())
                .plusCode(getPlusCode())
                .priceLevel(getPriceLevel())
                .rating(getRating())
                .reference(getReference())
                .reservable(getReservable())
                .reviews(getReviews())
                .servesBeer(getServesBeer())
                .servesBreakfast(getServesBreakfast())
                .servesBrunch(getServesBrunch())
                .servesDinner(getServesDinner())
                .servesLunch(getServesLunch())
                .servesVegetarianFood(getServesVegetarianFood())
                .servesWine(getServesWine())
                .scope(getScope())
                .secondaryOpeningHours(getSecondaryOpeningHours())
                .takeout(getTakeout())
                .types(getTypes())
                .url(getUrl())
                .userRatingsTotal(getUserRatingsTotal())
                .utcOffset(getUtcOffset())
                .vicinity(getVicinity())
                .website(getWebsite())
                .wheelchairAccessibleEntrance(getWheelchairAccessibleEntrance());
        builder.additionalProperties = additionalProperties;
        return builder;
    }

    /**
     * Class to build instances of {@link Place}.
     */
    public static class Builder {
        private List<AddressComponent> addressComponents;
        private String adrAddress;
        private BusinessStatus businessStatus;
        private Boolean curbsidePickup;
        private PlaceOpeningHours currentOpeningHours;
        private Boolean delivery;
        private Boolean dineIn;
        private PlaceEditorialSummary editorialSummary;
        private String formattedAddress;
        private String formattedPhoneNumber;
        private Geometry geometry;
        private String icon;
        private String iconBackgroundColor;
        private String iconMaskBaseUri;
        private String internationalPhoneNumber;
        private String name;
        private PlaceOpeningHours openingHours;
        private Boolean permanentlyClosed;
        private List<PlacePhoto> photos;
        private String placeId;
        private PlusCode plusCode;
        private Double priceLevel;
        private Double rating;
        private String reference;
        private Boolean reservable;
        private List<PlaceReview> reviews;
        private Boolean servesBeer;
        private Boolean servesBreakfast;
        private Boolean servesBrunch;
        private Boolean servesDinner;
        private Boolean servesLunch;
        private Boolean servesVegetarianFood;
        private Boolean servesWine;
        private String scope;
        private List<PlaceOpeningHours> secondaryOpeningHours;
        private Boolean takeout;
        private List<String> types;
        private String url;
        private Double userRatingsTotal;
        private Double utcOffset;
        private String vicinity;
        private String website;
        private Boolean wheelchairAccessibleEntrance;
        private AdditionalProperties<Object> additionalProperties =
                new AdditionalProperties<Object>();



        /**
         * Setter for addressComponents.
         * @param  addressComponents  List of AddressComponent value for addressComponents.
         * @return Builder
         */
        public Builder addressComponents(List<AddressComponent> addressComponents) {
            this.addressComponents = addressComponents;
            return this;
        }

        /**
         * Setter for adrAddress.
         * @param  adrAddress  String value for adrAddress.
         * @return Builder
         */
        public Builder adrAddress(String adrAddress) {
            this.adrAddress = adrAddress;
            return this;
        }

        /**
         * Setter for businessStatus.
         * @param  businessStatus  BusinessStatus value for businessStatus.
         * @return Builder
         */
        public Builder businessStatus(BusinessStatus businessStatus) {
            this.businessStatus = businessStatus;
            return this;
        }

        /**
         * Setter for curbsidePickup.
         * @param  curbsidePickup  Boolean value for curbsidePickup.
         * @return Builder
         */
        public Builder curbsidePickup(Boolean curbsidePickup) {
            this.curbsidePickup = curbsidePickup;
            return this;
        }

        /**
         * Setter for currentOpeningHours.
         * @param  currentOpeningHours  PlaceOpeningHours value for currentOpeningHours.
         * @return Builder
         */
        public Builder currentOpeningHours(PlaceOpeningHours currentOpeningHours) {
            this.currentOpeningHours = currentOpeningHours;
            return this;
        }

        /**
         * Setter for delivery.
         * @param  delivery  Boolean value for delivery.
         * @return Builder
         */
        public Builder delivery(Boolean delivery) {
            this.delivery = delivery;
            return this;
        }

        /**
         * Setter for dineIn.
         * @param  dineIn  Boolean value for dineIn.
         * @return Builder
         */
        public Builder dineIn(Boolean dineIn) {
            this.dineIn = dineIn;
            return this;
        }

        /**
         * Setter for editorialSummary.
         * @param  editorialSummary  PlaceEditorialSummary value for editorialSummary.
         * @return Builder
         */
        public Builder editorialSummary(PlaceEditorialSummary editorialSummary) {
            this.editorialSummary = editorialSummary;
            return this;
        }

        /**
         * Setter for formattedAddress.
         * @param  formattedAddress  String value for formattedAddress.
         * @return Builder
         */
        public Builder formattedAddress(String formattedAddress) {
            this.formattedAddress = formattedAddress;
            return this;
        }

        /**
         * Setter for formattedPhoneNumber.
         * @param  formattedPhoneNumber  String value for formattedPhoneNumber.
         * @return Builder
         */
        public Builder formattedPhoneNumber(String formattedPhoneNumber) {
            this.formattedPhoneNumber = formattedPhoneNumber;
            return this;
        }

        /**
         * Setter for geometry.
         * @param  geometry  Geometry value for geometry.
         * @return Builder
         */
        public Builder geometry(Geometry geometry) {
            this.geometry = geometry;
            return this;
        }

        /**
         * Setter for icon.
         * @param  icon  String value for icon.
         * @return Builder
         */
        public Builder icon(String icon) {
            this.icon = icon;
            return this;
        }

        /**
         * Setter for iconBackgroundColor.
         * @param  iconBackgroundColor  String value for iconBackgroundColor.
         * @return Builder
         */
        public Builder iconBackgroundColor(String iconBackgroundColor) {
            this.iconBackgroundColor = iconBackgroundColor;
            return this;
        }

        /**
         * Setter for iconMaskBaseUri.
         * @param  iconMaskBaseUri  String value for iconMaskBaseUri.
         * @return Builder
         */
        public Builder iconMaskBaseUri(String iconMaskBaseUri) {
            this.iconMaskBaseUri = iconMaskBaseUri;
            return this;
        }

        /**
         * Setter for internationalPhoneNumber.
         * @param  internationalPhoneNumber  String value for internationalPhoneNumber.
         * @return Builder
         */
        public Builder internationalPhoneNumber(String internationalPhoneNumber) {
            this.internationalPhoneNumber = internationalPhoneNumber;
            return this;
        }

        /**
         * Setter for name.
         * @param  name  String value for name.
         * @return Builder
         */
        public Builder name(String name) {
            this.name = name;
            return this;
        }

        /**
         * Setter for openingHours.
         * @param  openingHours  PlaceOpeningHours value for openingHours.
         * @return Builder
         */
        public Builder openingHours(PlaceOpeningHours openingHours) {
            this.openingHours = openingHours;
            return this;
        }

        /**
         * Setter for permanentlyClosed.
         * @param  permanentlyClosed  Boolean value for permanentlyClosed.
         * @return Builder
         */
        public Builder permanentlyClosed(Boolean permanentlyClosed) {
            this.permanentlyClosed = permanentlyClosed;
            return this;
        }

        /**
         * Setter for photos.
         * @param  photos  List of PlacePhoto value for photos.
         * @return Builder
         */
        public Builder photos(List<PlacePhoto> photos) {
            this.photos = photos;
            return this;
        }

        /**
         * Setter for placeId.
         * @param  placeId  String value for placeId.
         * @return Builder
         */
        public Builder placeId(String placeId) {
            this.placeId = placeId;
            return this;
        }

        /**
         * Setter for plusCode.
         * @param  plusCode  PlusCode value for plusCode.
         * @return Builder
         */
        public Builder plusCode(PlusCode plusCode) {
            this.plusCode = plusCode;
            return this;
        }

        /**
         * Setter for priceLevel.
         * @param  priceLevel  Double value for priceLevel.
         * @return Builder
         */
        public Builder priceLevel(Double priceLevel) {
            this.priceLevel = priceLevel;
            return this;
        }

        /**
         * Setter for rating.
         * @param  rating  Double value for rating.
         * @return Builder
         */
        public Builder rating(Double rating) {
            this.rating = rating;
            return this;
        }

        /**
         * Setter for reference.
         * @param  reference  String value for reference.
         * @return Builder
         */
        public Builder reference(String reference) {
            this.reference = reference;
            return this;
        }

        /**
         * Setter for reservable.
         * @param  reservable  Boolean value for reservable.
         * @return Builder
         */
        public Builder reservable(Boolean reservable) {
            this.reservable = reservable;
            return this;
        }

        /**
         * Setter for reviews.
         * @param  reviews  List of PlaceReview value for reviews.
         * @return Builder
         */
        public Builder reviews(List<PlaceReview> reviews) {
            this.reviews = reviews;
            return this;
        }

        /**
         * Setter for servesBeer.
         * @param  servesBeer  Boolean value for servesBeer.
         * @return Builder
         */
        public Builder servesBeer(Boolean servesBeer) {
            this.servesBeer = servesBeer;
            return this;
        }

        /**
         * Setter for servesBreakfast.
         * @param  servesBreakfast  Boolean value for servesBreakfast.
         * @return Builder
         */
        public Builder servesBreakfast(Boolean servesBreakfast) {
            this.servesBreakfast = servesBreakfast;
            return this;
        }

        /**
         * Setter for servesBrunch.
         * @param  servesBrunch  Boolean value for servesBrunch.
         * @return Builder
         */
        public Builder servesBrunch(Boolean servesBrunch) {
            this.servesBrunch = servesBrunch;
            return this;
        }

        /**
         * Setter for servesDinner.
         * @param  servesDinner  Boolean value for servesDinner.
         * @return Builder
         */
        public Builder servesDinner(Boolean servesDinner) {
            this.servesDinner = servesDinner;
            return this;
        }

        /**
         * Setter for servesLunch.
         * @param  servesLunch  Boolean value for servesLunch.
         * @return Builder
         */
        public Builder servesLunch(Boolean servesLunch) {
            this.servesLunch = servesLunch;
            return this;
        }

        /**
         * Setter for servesVegetarianFood.
         * @param  servesVegetarianFood  Boolean value for servesVegetarianFood.
         * @return Builder
         */
        public Builder servesVegetarianFood(Boolean servesVegetarianFood) {
            this.servesVegetarianFood = servesVegetarianFood;
            return this;
        }

        /**
         * Setter for servesWine.
         * @param  servesWine  Boolean value for servesWine.
         * @return Builder
         */
        public Builder servesWine(Boolean servesWine) {
            this.servesWine = servesWine;
            return this;
        }

        /**
         * Setter for scope.
         * @param  scope  String value for scope.
         * @return Builder
         */
        public Builder scope(String scope) {
            this.scope = scope;
            return this;
        }

        /**
         * Setter for secondaryOpeningHours.
         * @param  secondaryOpeningHours  List of PlaceOpeningHours value for secondaryOpeningHours.
         * @return Builder
         */
        public Builder secondaryOpeningHours(List<PlaceOpeningHours> secondaryOpeningHours) {
            this.secondaryOpeningHours = secondaryOpeningHours;
            return this;
        }

        /**
         * Setter for takeout.
         * @param  takeout  Boolean value for takeout.
         * @return Builder
         */
        public Builder takeout(Boolean takeout) {
            this.takeout = takeout;
            return this;
        }

        /**
         * Setter for types.
         * @param  types  List of String value for types.
         * @return Builder
         */
        public Builder types(List<String> types) {
            this.types = types;
            return this;
        }

        /**
         * Setter for url.
         * @param  url  String value for url.
         * @return Builder
         */
        public Builder url(String url) {
            this.url = url;
            return this;
        }

        /**
         * Setter for userRatingsTotal.
         * @param  userRatingsTotal  Double value for userRatingsTotal.
         * @return Builder
         */
        public Builder userRatingsTotal(Double userRatingsTotal) {
            this.userRatingsTotal = userRatingsTotal;
            return this;
        }

        /**
         * Setter for utcOffset.
         * @param  utcOffset  Double value for utcOffset.
         * @return Builder
         */
        public Builder utcOffset(Double utcOffset) {
            this.utcOffset = utcOffset;
            return this;
        }

        /**
         * Setter for vicinity.
         * @param  vicinity  String value for vicinity.
         * @return Builder
         */
        public Builder vicinity(String vicinity) {
            this.vicinity = vicinity;
            return this;
        }

        /**
         * Setter for website.
         * @param  website  String value for website.
         * @return Builder
         */
        public Builder website(String website) {
            this.website = website;
            return this;
        }

        /**
         * Setter for wheelchairAccessibleEntrance.
         * @param  wheelchairAccessibleEntrance  Boolean value for wheelchairAccessibleEntrance.
         * @return Builder
         */
        public Builder wheelchairAccessibleEntrance(Boolean wheelchairAccessibleEntrance) {
            this.wheelchairAccessibleEntrance = wheelchairAccessibleEntrance;
            return this;
        }

        /**
         * Setter for additional property that are not in model fields.
         * @param name The name of the additional property.
         * @param value The Object value of the additional property.
         * @return Builder.
         */
        public Builder additionalProperty(String name, Object value) {
            this.additionalProperties.setAdditionalProperty(name, value);
            return this;
        }

        /**
         * Builds a new {@link Place} object using the set fields.
         * @return {@link Place}
         */
        public Place build() {
            Place model =
                    new Place(addressComponents, adrAddress, businessStatus, curbsidePickup,
                            currentOpeningHours, delivery, dineIn, editorialSummary,
                            formattedAddress, formattedPhoneNumber, geometry, icon,
                            iconBackgroundColor, iconMaskBaseUri, internationalPhoneNumber, name,
                            openingHours, permanentlyClosed, photos, placeId, plusCode, priceLevel,
                            rating, reference, reservable, reviews, servesBeer, servesBreakfast,
                            servesBrunch, servesDinner, servesLunch, servesVegetarianFood,
                            servesWine, scope, secondaryOpeningHours, takeout, types, url,
                            userRatingsTotal, utcOffset, vicinity, website,
                            wheelchairAccessibleEntrance);
            model.additionalProperties = additionalProperties;
            return model;
        }
    }
}
