/*
 * GoogleMapsPlatformLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.googleapis.maps.models;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.AdditionalProperties;
import io.apimatic.core.utilities.ConversionHelper;
import java.util.List;
import java.util.Map;

/**
 * This is a model class for PlaceAutocompleteStructuredFormat type.
 */
public class PlaceAutocompleteStructuredFormat {
    private String mainText;
    private List<PlaceAutocompleteMatchedSubstring> mainTextMatchedSubstrings;
    private String secondaryText;
    private List<PlaceAutocompleteMatchedSubstring> secondaryTextMatchedSubstrings;
    private AdditionalProperties<Object> additionalProperties = 
            new AdditionalProperties<Object>(this.getClass());

    /**
     * Default constructor.
     */
    public PlaceAutocompleteStructuredFormat() {
    }

    /**
     * Initialization constructor.
     * @param  mainText  String value for mainText.
     * @param  mainTextMatchedSubstrings  List of PlaceAutocompleteMatchedSubstring value for
     *         mainTextMatchedSubstrings.
     * @param  secondaryText  String value for secondaryText.
     * @param  secondaryTextMatchedSubstrings  List of PlaceAutocompleteMatchedSubstring value for
     *         secondaryTextMatchedSubstrings.
     */
    public PlaceAutocompleteStructuredFormat(
            String mainText,
            List<PlaceAutocompleteMatchedSubstring> mainTextMatchedSubstrings,
            String secondaryText,
            List<PlaceAutocompleteMatchedSubstring> secondaryTextMatchedSubstrings) {
        this.mainText = mainText;
        this.mainTextMatchedSubstrings = mainTextMatchedSubstrings;
        this.secondaryText = secondaryText;
        this.secondaryTextMatchedSubstrings = secondaryTextMatchedSubstrings;
    }

    /**
     * Getter for MainText.
     * Contains the main text of a prediction, usually the name of the place.
     * @return Returns the String
     */
    @JsonGetter("main_text")
    public String getMainText() {
        return mainText;
    }

    /**
     * Setter for MainText.
     * Contains the main text of a prediction, usually the name of the place.
     * @param mainText Value for String
     */
    @JsonSetter("main_text")
    public void setMainText(String mainText) {
        this.mainText = mainText;
    }

    /**
     * Getter for MainTextMatchedSubstrings.
     * Contains an array with `offset` value and `length`. These describe the location of the
     * entered term in the prediction result text, so that the term can be highlighted if desired.
     * @return Returns the List of PlaceAutocompleteMatchedSubstring
     */
    @JsonGetter("main_text_matched_substrings")
    public List<PlaceAutocompleteMatchedSubstring> getMainTextMatchedSubstrings() {
        return mainTextMatchedSubstrings;
    }

    /**
     * Setter for MainTextMatchedSubstrings.
     * Contains an array with `offset` value and `length`. These describe the location of the
     * entered term in the prediction result text, so that the term can be highlighted if desired.
     * @param mainTextMatchedSubstrings Value for List of PlaceAutocompleteMatchedSubstring
     */
    @JsonSetter("main_text_matched_substrings")
    public void setMainTextMatchedSubstrings(List<PlaceAutocompleteMatchedSubstring> mainTextMatchedSubstrings) {
        this.mainTextMatchedSubstrings = mainTextMatchedSubstrings;
    }

    /**
     * Getter for SecondaryText.
     * Contains the secondary text of a prediction, usually the location of the place.
     * @return Returns the String
     */
    @JsonGetter("secondary_text")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getSecondaryText() {
        return secondaryText;
    }

    /**
     * Setter for SecondaryText.
     * Contains the secondary text of a prediction, usually the location of the place.
     * @param secondaryText Value for String
     */
    @JsonSetter("secondary_text")
    public void setSecondaryText(String secondaryText) {
        this.secondaryText = secondaryText;
    }

    /**
     * Getter for SecondaryTextMatchedSubstrings.
     * Contains an array with `offset` value and `length`. These describe the location of the
     * entered term in the prediction result text, so that the term can be highlighted if desired.
     * @return Returns the List of PlaceAutocompleteMatchedSubstring
     */
    @JsonGetter("secondary_text_matched_substrings")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public List<PlaceAutocompleteMatchedSubstring> getSecondaryTextMatchedSubstrings() {
        return secondaryTextMatchedSubstrings;
    }

    /**
     * Setter for SecondaryTextMatchedSubstrings.
     * Contains an array with `offset` value and `length`. These describe the location of the
     * entered term in the prediction result text, so that the term can be highlighted if desired.
     * @param secondaryTextMatchedSubstrings Value for List of PlaceAutocompleteMatchedSubstring
     */
    @JsonSetter("secondary_text_matched_substrings")
    public void setSecondaryTextMatchedSubstrings(List<PlaceAutocompleteMatchedSubstring> secondaryTextMatchedSubstrings) {
        this.secondaryTextMatchedSubstrings = secondaryTextMatchedSubstrings;
    }

    /**
     * Hidden method for the serialization of additional properties.
     * @return The map of additionally set properties.
     */
    @JsonAnyGetter
    private Map<String, Object> getAdditionalProperties() {
        return additionalProperties.getAdditionalProperties();
    }

    /**
     * Hidden method for the de-serialization of additional properties.
     * @param name The name of the additional property.
     * @param value The Object value of the additional property.
     */
    @JsonAnySetter
    private void setAdditionalProperties(String name, Object value) {
        additionalProperties.setAdditionalProperty(name,
                ConversionHelper.convertToSimpleType(value,
                        x -> x),
                true);
    }

    /**
     * Getter for the value of additional properties based on provided property name.
     * @param name The name of the additional property.
     * @return Either the Object property value or null if not exist.
     */
    
    public Object getAdditionalProperty(String name) {
        return additionalProperties.getAdditionalProperty(name);
    }

    /**
     * Converts this PlaceAutocompleteStructuredFormat into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "PlaceAutocompleteStructuredFormat [" + "mainText=" + mainText
                + ", mainTextMatchedSubstrings=" + mainTextMatchedSubstrings + ", secondaryText="
                + secondaryText + ", secondaryTextMatchedSubstrings="
                + secondaryTextMatchedSubstrings + ", additionalProperties=" + additionalProperties
                + "]";
    }

    /**
     * Builds a new {@link PlaceAutocompleteStructuredFormat.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link PlaceAutocompleteStructuredFormat.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(mainText, mainTextMatchedSubstrings)
                .secondaryText(getSecondaryText())
                .secondaryTextMatchedSubstrings(getSecondaryTextMatchedSubstrings());
        builder.additionalProperties = additionalProperties;
        return builder;
    }

    /**
     * Class to build instances of {@link PlaceAutocompleteStructuredFormat}.
     */
    public static class Builder {
        private String mainText;
        private List<PlaceAutocompleteMatchedSubstring> mainTextMatchedSubstrings;
        private String secondaryText;
        private List<PlaceAutocompleteMatchedSubstring> secondaryTextMatchedSubstrings;
        private AdditionalProperties<Object> additionalProperties =
                new AdditionalProperties<Object>();

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  mainText  String value for mainText.
         * @param  mainTextMatchedSubstrings  List of PlaceAutocompleteMatchedSubstring value for
         *         mainTextMatchedSubstrings.
         */
        public Builder(String mainText,
                List<PlaceAutocompleteMatchedSubstring> mainTextMatchedSubstrings) {
            this.mainText = mainText;
            this.mainTextMatchedSubstrings = mainTextMatchedSubstrings;
        }

        /**
         * Setter for mainText.
         * @param  mainText  String value for mainText.
         * @return Builder
         */
        public Builder mainText(String mainText) {
            this.mainText = mainText;
            return this;
        }

        /**
         * Setter for mainTextMatchedSubstrings.
         * @param  mainTextMatchedSubstrings  List of PlaceAutocompleteMatchedSubstring value for
         *         mainTextMatchedSubstrings.
         * @return Builder
         */
        public Builder mainTextMatchedSubstrings(
                List<PlaceAutocompleteMatchedSubstring> mainTextMatchedSubstrings) {
            this.mainTextMatchedSubstrings = mainTextMatchedSubstrings;
            return this;
        }

        /**
         * Setter for secondaryText.
         * @param  secondaryText  String value for secondaryText.
         * @return Builder
         */
        public Builder secondaryText(String secondaryText) {
            this.secondaryText = secondaryText;
            return this;
        }

        /**
         * Setter for secondaryTextMatchedSubstrings.
         * @param  secondaryTextMatchedSubstrings  List of PlaceAutocompleteMatchedSubstring value
         *         for secondaryTextMatchedSubstrings.
         * @return Builder
         */
        public Builder secondaryTextMatchedSubstrings(
                List<PlaceAutocompleteMatchedSubstring> secondaryTextMatchedSubstrings) {
            this.secondaryTextMatchedSubstrings = secondaryTextMatchedSubstrings;
            return this;
        }

        /**
         * Setter for additional property that are not in model fields.
         * @param name The name of the additional property.
         * @param value The Object value of the additional property.
         * @return Builder.
         */
        public Builder additionalProperty(String name, Object value) {
            this.additionalProperties.setAdditionalProperty(name, value);
            return this;
        }

        /**
         * Builds a new {@link PlaceAutocompleteStructuredFormat} object using the set fields.
         * @return {@link PlaceAutocompleteStructuredFormat}
         */
        public PlaceAutocompleteStructuredFormat build() {
            PlaceAutocompleteStructuredFormat model =
                    new PlaceAutocompleteStructuredFormat(mainText, mainTextMatchedSubstrings,
                            secondaryText, secondaryTextMatchedSubstrings);
            model.additionalProperties = additionalProperties;
            return model;
        }
    }
}
