/*
 * GoogleMapsPlatformLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.googleapis.maps.models;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.AdditionalProperties;
import io.apimatic.core.utilities.ConversionHelper;
import java.util.Map;

/**
 * This is a model class for PlaceEditorialSummary type.
 */
public class PlaceEditorialSummary {
    private String overview;
    private String language;
    private AdditionalProperties<Object> additionalProperties = 
            new AdditionalProperties<Object>(this.getClass());

    /**
     * Default constructor.
     */
    public PlaceEditorialSummary() {
    }

    /**
     * Initialization constructor.
     * @param  overview  String value for overview.
     * @param  language  String value for language.
     */
    public PlaceEditorialSummary(
            String overview,
            String language) {
        this.overview = overview;
        this.language = language;
    }

    /**
     * Getter for Overview.
     * A medium-length textual summary of the place.
     * @return Returns the String
     */
    @JsonGetter("overview")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getOverview() {
        return overview;
    }

    /**
     * Setter for Overview.
     * A medium-length textual summary of the place.
     * @param overview Value for String
     */
    @JsonSetter("overview")
    public void setOverview(String overview) {
        this.overview = overview;
    }

    /**
     * Getter for Language.
     * The language of the previous fields. May not always be present.
     * @return Returns the String
     */
    @JsonGetter("language")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getLanguage() {
        return language;
    }

    /**
     * Setter for Language.
     * The language of the previous fields. May not always be present.
     * @param language Value for String
     */
    @JsonSetter("language")
    public void setLanguage(String language) {
        this.language = language;
    }

    /**
     * Hidden method for the serialization of additional properties.
     * @return The map of additionally set properties.
     */
    @JsonAnyGetter
    private Map<String, Object> getAdditionalProperties() {
        return additionalProperties.getAdditionalProperties();
    }

    /**
     * Hidden method for the de-serialization of additional properties.
     * @param name The name of the additional property.
     * @param value The Object value of the additional property.
     */
    @JsonAnySetter
    private void setAdditionalProperties(String name, Object value) {
        additionalProperties.setAdditionalProperty(name,
                ConversionHelper.convertToSimpleType(value,
                        x -> x),
                true);
    }

    /**
     * Getter for the value of additional properties based on provided property name.
     * @param name The name of the additional property.
     * @return Either the Object property value or null if not exist.
     */
    
    public Object getAdditionalProperty(String name) {
        return additionalProperties.getAdditionalProperty(name);
    }

    /**
     * Converts this PlaceEditorialSummary into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "PlaceEditorialSummary [" + "overview=" + overview + ", language=" + language
                + ", additionalProperties=" + additionalProperties + "]";
    }

    /**
     * Builds a new {@link PlaceEditorialSummary.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link PlaceEditorialSummary.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .overview(getOverview())
                .language(getLanguage());
        builder.additionalProperties = additionalProperties;
        return builder;
    }

    /**
     * Class to build instances of {@link PlaceEditorialSummary}.
     */
    public static class Builder {
        private String overview;
        private String language;
        private AdditionalProperties<Object> additionalProperties =
                new AdditionalProperties<Object>();



        /**
         * Setter for overview.
         * @param  overview  String value for overview.
         * @return Builder
         */
        public Builder overview(String overview) {
            this.overview = overview;
            return this;
        }

        /**
         * Setter for language.
         * @param  language  String value for language.
         * @return Builder
         */
        public Builder language(String language) {
            this.language = language;
            return this;
        }

        /**
         * Setter for additional property that are not in model fields.
         * @param name The name of the additional property.
         * @param value The Object value of the additional property.
         * @return Builder.
         */
        public Builder additionalProperty(String name, Object value) {
            this.additionalProperties.setAdditionalProperty(name, value);
            return this;
        }

        /**
         * Builds a new {@link PlaceEditorialSummary} object using the set fields.
         * @return {@link PlaceEditorialSummary}
         */
        public PlaceEditorialSummary build() {
            PlaceEditorialSummary model =
                    new PlaceEditorialSummary(overview, language);
            model.additionalProperties = additionalProperties;
            return model;
        }
    }
}
