/*
 * GoogleMapsPlatformLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.googleapis.maps.models;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.TreeMap;


/**
 * TransitRoutingPreference to be used.
 */
public enum TransitRoutingPreference {
    LESS_WALKING,

    FEWER_TRANSFERS;


    private static TreeMap<String, TransitRoutingPreference> valueMap = new TreeMap<>();
    private String value;

    static {
        LESS_WALKING.value = "less_walking";
        FEWER_TRANSFERS.value = "fewer_transfers";

        valueMap.put("less_walking", LESS_WALKING);
        valueMap.put("fewer_transfers", FEWER_TRANSFERS);
    }

    /**
     * Returns the enum member associated with the given string value.
     * @param toConvert String value to get enum member.
     * @return The enum member against the given string value.
     * @throws IOException when provided value is not mapped to any enum member.
     */
    @JsonCreator
    public static TransitRoutingPreference constructFromString(String toConvert) throws IOException {
        TransitRoutingPreference enumValue = fromString(toConvert);
        if (enumValue == null) {
            throw new IOException("Unable to create enum instance with value: " + toConvert);
        }
        return enumValue;
    }

    /**
     * Returns the enum member associated with the given string value.
     * @param toConvert String value to get enum member.
     * @return The enum member against the given string value.
     */
    public static TransitRoutingPreference fromString(String toConvert) {
        return valueMap.get(toConvert);
    }

    /**
     * Returns the string value associated with the enum member.
     * @return The string value against enum member.
     */
    @JsonValue
    public String value() {
        return value;
    }
        
    /**
     * Get string representation of this enum.
     */
    @Override
    public String toString() {
        return value.toString();
    }

    /**
     * Convert list of TransitRoutingPreference values to list of string values.
     * @param toConvert The list of TransitRoutingPreference values to convert.
     * @return List of representative string values.
     */
    public static List<String> toValue(List<TransitRoutingPreference> toConvert) {
        if (toConvert == null) {
            return null;
        }
        List<String> convertedValues = new ArrayList<>();
        for (TransitRoutingPreference enumValue : toConvert) {
            convertedValues.add(enumValue.value);
        }
        return convertedValues;
    }
} 