/*
 * GoogleMapsPlatformLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.googleapis.maps.models;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.TreeMap;


/**
 * Type to be used.
 */
public enum Type {
    ADMINISTRATIVE_AREA_LEVEL_1,

    ADMINISTRATIVE_AREA_LEVEL_2,

    ADMINISTRATIVE_AREA_LEVEL_3,

    ADMINISTRATIVE_AREA_LEVEL_4,

    ADMINISTRATIVE_AREA_LEVEL_5,

    AMUSEMENT_PARK,

    AIRPORT,

    COLLOQUIAL_AREA,

    COUNTRY,

    ESTABLISHMENT,

    INTERSECTION,

    LOCALITY,

    NATURAL_FEATURE,

    NEIGHBORHOOD,

    PARK,

    PLUS_CODE,

    POINT_OF_INTEREST,

    POLITICAL,

    POSTAL_CODE,

    PREMISE,

    ROUTE,

    STREET_ADDRESS,

    SUBLOCALITY,

    SUBLOCALITY_LEVEL_1,

    SUBPREMISE,

    TOURIST_ATTRACTION,

    TRAIN_STATION,

    TRANSIT_STATION;


    private static TreeMap<String, Type> valueMap = new TreeMap<>();
    private String value;

    static {
        ADMINISTRATIVE_AREA_LEVEL_1.value = "administrative_area_level_1";
        ADMINISTRATIVE_AREA_LEVEL_2.value = "administrative_area_level_2";
        ADMINISTRATIVE_AREA_LEVEL_3.value = "administrative_area_level_3";
        ADMINISTRATIVE_AREA_LEVEL_4.value = "administrative_area_level_4";
        ADMINISTRATIVE_AREA_LEVEL_5.value = "administrative_area_level_5";
        AMUSEMENT_PARK.value = "amusement_park";
        AIRPORT.value = "airport";
        COLLOQUIAL_AREA.value = "colloquial_area";
        COUNTRY.value = "country";
        ESTABLISHMENT.value = "establishment";
        INTERSECTION.value = "intersection";
        LOCALITY.value = "locality";
        NATURAL_FEATURE.value = "natural_feature";
        NEIGHBORHOOD.value = "neighborhood";
        PARK.value = "park";
        PLUS_CODE.value = "plus_code";
        POINT_OF_INTEREST.value = "point_of_interest";
        POLITICAL.value = "political";
        POSTAL_CODE.value = "postal_code";
        PREMISE.value = "premise";
        ROUTE.value = "route";
        STREET_ADDRESS.value = "street_address";
        SUBLOCALITY.value = "sublocality";
        SUBLOCALITY_LEVEL_1.value = "sublocality_level_1";
        SUBPREMISE.value = "subpremise";
        TOURIST_ATTRACTION.value = "tourist_attraction";
        TRAIN_STATION.value = "train_station";
        TRANSIT_STATION.value = "transit_station";

        valueMap.put("administrative_area_level_1", ADMINISTRATIVE_AREA_LEVEL_1);
        valueMap.put("administrative_area_level_2", ADMINISTRATIVE_AREA_LEVEL_2);
        valueMap.put("administrative_area_level_3", ADMINISTRATIVE_AREA_LEVEL_3);
        valueMap.put("administrative_area_level_4", ADMINISTRATIVE_AREA_LEVEL_4);
        valueMap.put("administrative_area_level_5", ADMINISTRATIVE_AREA_LEVEL_5);
        valueMap.put("amusement_park", AMUSEMENT_PARK);
        valueMap.put("airport", AIRPORT);
        valueMap.put("colloquial_area", COLLOQUIAL_AREA);
        valueMap.put("country", COUNTRY);
        valueMap.put("establishment", ESTABLISHMENT);
        valueMap.put("intersection", INTERSECTION);
        valueMap.put("locality", LOCALITY);
        valueMap.put("natural_feature", NATURAL_FEATURE);
        valueMap.put("neighborhood", NEIGHBORHOOD);
        valueMap.put("park", PARK);
        valueMap.put("plus_code", PLUS_CODE);
        valueMap.put("point_of_interest", POINT_OF_INTEREST);
        valueMap.put("political", POLITICAL);
        valueMap.put("postal_code", POSTAL_CODE);
        valueMap.put("premise", PREMISE);
        valueMap.put("route", ROUTE);
        valueMap.put("street_address", STREET_ADDRESS);
        valueMap.put("sublocality", SUBLOCALITY);
        valueMap.put("sublocality_level_1", SUBLOCALITY_LEVEL_1);
        valueMap.put("subpremise", SUBPREMISE);
        valueMap.put("tourist_attraction", TOURIST_ATTRACTION);
        valueMap.put("train_station", TRAIN_STATION);
        valueMap.put("transit_station", TRANSIT_STATION);
    }

    /**
     * Returns the enum member associated with the given string value.
     * @param toConvert String value to get enum member.
     * @return The enum member against the given string value.
     * @throws IOException when provided value is not mapped to any enum member.
     */
    @JsonCreator
    public static Type constructFromString(String toConvert) throws IOException {
        Type enumValue = fromString(toConvert);
        if (enumValue == null) {
            throw new IOException("Unable to create enum instance with value: " + toConvert);
        }
        return enumValue;
    }

    /**
     * Returns the enum member associated with the given string value.
     * @param toConvert String value to get enum member.
     * @return The enum member against the given string value.
     */
    public static Type fromString(String toConvert) {
        return valueMap.get(toConvert);
    }

    /**
     * Returns the string value associated with the enum member.
     * @return The string value against enum member.
     */
    @JsonValue
    public String value() {
        return value;
    }
        
    /**
     * Get string representation of this enum.
     */
    @Override
    public String toString() {
        return value.toString();
    }

    /**
     * Convert list of Type values to list of string values.
     * @param toConvert The list of Type values to convert.
     * @return List of representative string values.
     */
    public static List<String> toValue(List<Type> toConvert) {
        if (toConvert == null) {
            return null;
        }
        List<String> convertedValues = new ArrayList<>();
        for (Type enumValue : toConvert) {
            convertedValues.add(enumValue.value);
        }
        return convertedValues;
    }
} 