/*
 * GoogleMapsPlatformLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.googleapis.www;

import com.googleapis.www.apis.DirectionsApi;
import com.googleapis.www.apis.DistanceMatrixApi;
import com.googleapis.www.apis.ElevationApi;
import com.googleapis.www.apis.GeocodingApi;
import com.googleapis.www.apis.GeolocationApi;
import com.googleapis.www.apis.PlacesApi;
import com.googleapis.www.apis.RoadsApi;
import com.googleapis.www.apis.StreetViewApi;
import com.googleapis.www.apis.TimeZoneApi;
import com.googleapis.www.authentication.CustomQueryAuthenticationManager;
import com.googleapis.www.authentication.CustomQueryAuthenticationModel;
import com.googleapis.www.http.client.HttpCallback;
import com.googleapis.www.http.client.HttpClientConfiguration;
import com.googleapis.www.http.client.ReadonlyHttpClientConfiguration;
import com.googleapis.www.logging.configuration.ApiLoggingConfiguration;
import com.googleapis.www.logging.configuration.ReadonlyLoggingConfiguration;
import io.apimatic.core.GlobalConfiguration;
import io.apimatic.coreinterfaces.authentication.Authentication;
import io.apimatic.coreinterfaces.compatibility.CompatibilityFactory;
import io.apimatic.coreinterfaces.http.HttpClient;
import io.apimatic.okhttpclient.adapter.OkClient;
import java.util.AbstractMap.SimpleEntry;
import java.util.HashMap;
import java.util.Map;
import java.util.function.Consumer;
import java.util.function.Supplier;

/**
 * Gateway class for the library.
 * This class acts as a factory for Apis.
 * It holds the state of the SDK.
 */
public final class GoogleMapsPlatformClient implements Configuration {

    /**
     * Private store for controllers.
     */
    private GeolocationApi geolocationApi;
    private DirectionsApi directionsApi;
    private ElevationApi elevationApi;
    private GeocodingApi geocodingApi;
    private TimeZoneApi timeZoneApi;
    private RoadsApi roadsApi;
    private DistanceMatrixApi distanceMatrixApi;
    private PlacesApi placesApi;
    private StreetViewApi streetViewApi;

    private static final CompatibilityFactory compatibilityFactory = new CompatibilityFactoryImpl();

    private static String userAgent = "Java-SDK/1.0.0 (OS: {os-info}, Engine: {engine}/{engine-version})";

    /**
     * Current API environment.
     */
    private final Environment environment;

    /**
     * The HTTP Client instance to use for making HTTP requests.
     */
    private final HttpClient httpClient;

    /**
     * Http Client Configuration instance.
     */
    private final ReadonlyHttpClientConfiguration httpClientConfig;

    /**
     * Logging Configuration instance.
     */
    private final ReadonlyLoggingConfiguration loggingConfig;

    /**
     * CustomQueryAuthenticationManager.
     */
    private CustomQueryAuthenticationManager customQueryAuthenticationManager;

    /**
     * The instance of CustomQueryAuthenticationModel.
     */
    private CustomQueryAuthenticationModel customQueryAuthenticationModel;

    /**
     * Map of authentication Managers.
     */
    private Map<String, Authentication> authentications = new HashMap<String, Authentication>();

    /**
     * Callback to be called before and after the HTTP call for an endpoint is made.
     */
    private final HttpCallback httpCallback;

    private GoogleMapsPlatformClient(Environment environment, HttpClient httpClient,
            ReadonlyHttpClientConfiguration httpClientConfig,
            ReadonlyLoggingConfiguration loggingConfig,
            CustomQueryAuthenticationModel customQueryAuthenticationModel,
            HttpCallback httpCallback) {
        this.environment = environment;
        this.httpClient = httpClient;
        this.httpClientConfig = httpClientConfig;
        this.loggingConfig = loggingConfig;
        this.httpCallback = httpCallback;

        this.customQueryAuthenticationModel = customQueryAuthenticationModel;

        this.customQueryAuthenticationManager = new CustomQueryAuthenticationManager(
                customQueryAuthenticationModel);
        this.authentications.put("ApiKeyAuth", customQueryAuthenticationManager);

        GlobalConfiguration globalConfig = new GlobalConfiguration.Builder()
                .httpClient(httpClient).baseUri(server -> getBaseUri(server))
                .compatibilityFactory(compatibilityFactory)
                .authentication(this.authentications)
                .callback(httpCallback)
                .userAgent(userAgent)
                .loggingConfiguration(((ApiLoggingConfiguration) loggingConfig).getConfiguration())
                .build();
        geolocationApi = new GeolocationApi(globalConfig);
        directionsApi = new DirectionsApi(globalConfig);
        elevationApi = new ElevationApi(globalConfig);
        geocodingApi = new GeocodingApi(globalConfig);
        timeZoneApi = new TimeZoneApi(globalConfig);
        roadsApi = new RoadsApi(globalConfig);
        distanceMatrixApi = new DistanceMatrixApi(globalConfig);
        placesApi = new PlacesApi(globalConfig);
        streetViewApi = new StreetViewApi(globalConfig);
    }

    /**
     * Shutdown the underlying HttpClient instance.
     */
    public static void shutdown() {
        OkClient.shutdown();
    }

    /**
     * Get the instance of GeolocationApi.
     * @return geolocationApi
     */
    public GeolocationApi getGeolocationApi() {
        return geolocationApi;
    }

    /**
     * Get the instance of DirectionsApi.
     * @return directionsApi
     */
    public DirectionsApi getDirectionsApi() {
        return directionsApi;
    }

    /**
     * Get the instance of ElevationApi.
     * @return elevationApi
     */
    public ElevationApi getElevationApi() {
        return elevationApi;
    }

    /**
     * Get the instance of GeocodingApi.
     * @return geocodingApi
     */
    public GeocodingApi getGeocodingApi() {
        return geocodingApi;
    }

    /**
     * Get the instance of TimeZoneApi.
     * @return timeZoneApi
     */
    public TimeZoneApi getTimeZoneApi() {
        return timeZoneApi;
    }

    /**
     * Get the instance of RoadsApi.
     * @return roadsApi
     */
    public RoadsApi getRoadsApi() {
        return roadsApi;
    }

    /**
     * Get the instance of DistanceMatrixApi.
     * @return distanceMatrixApi
     */
    public DistanceMatrixApi getDistanceMatrixApi() {
        return distanceMatrixApi;
    }

    /**
     * Get the instance of PlacesApi.
     * @return placesApi
     */
    public PlacesApi getPlacesApi() {
        return placesApi;
    }

    /**
     * Get the instance of StreetViewApi.
     * @return streetViewApi
     */
    public StreetViewApi getStreetViewApi() {
        return streetViewApi;
    }

    /**
     * Current API environment.
     * @return environment
     */
    public Environment getEnvironment() {
        return environment;
    }

    /**
     * The HTTP Client instance to use for making HTTP requests.
     * @return httpClient
     */
    private HttpClient getHttpClient() {
        return httpClient;
    }

    /**
     * Http Client Configuration instance.
     * @return httpClientConfig
     */
    public ReadonlyHttpClientConfiguration getHttpClientConfig() {
        return httpClientConfig;
    }

    /**
     * Logging Configuration instance.
     * @return loggingConfig
     */
    public ReadonlyLoggingConfiguration getLoggingConfig() {
        return loggingConfig;
    }

    /**
     * The credentials to use with CustomQueryAuthentication.
     * @return customQueryAuthenticationCredentials
     */
    public CustomQueryAuthenticationCredentials getCustomQueryAuthenticationCredentials() {
        return customQueryAuthenticationManager;
    }

    /**
     * The auth credential model for CustomQueryAuthentication.
     * @return the instance of CustomQueryAuthenticationModel
     */
    public CustomQueryAuthenticationModel getCustomQueryAuthenticationModel() {
        return customQueryAuthenticationModel;
    }
    /**
     * The timeout to use for making HTTP requests.
     * @deprecated This method will be removed in a future version. Use
     *             {@link #getHttpClientConfig()} instead.
     *
     * @return timeout
     */
    @Deprecated
    public long timeout() {
        return httpClientConfig.getTimeout();
    }

    /**
     * Get base URI by current environment.
     * @param server Server for which to get the base URI
     * @return Processed base URI
     */
    public String getBaseUri(Server server) {
        Map<String, SimpleEntry<Object, Boolean>> parameters = new HashMap<>();
        StringBuilder baseUrl = new StringBuilder(environmentMapper(environment, server));
        ApiHelper.appendUrlWithTemplateParameters(baseUrl, parameters);
        return baseUrl.toString();
    }

    /**
     * Get base URI by current environment.
     * @return Processed base URI
     */
    public String getBaseUri() {
        return getBaseUri(Server.ENUM_DEFAULT);
    }


    /**
     * Get base URI by current environment.
     * 
     * @param server string for which to get the base URI
     * @return Processed base URI
     */
    public String getBaseUri(String server) {
        return getBaseUri(Server.fromString(server));
    }


    /**
     * Base URLs by environment and server aliases.
     * @param environment Environment for which to get the base URI
     * @param server Server for which to get the base URI
     * @return base URL
     */
    private static String environmentMapper(Environment environment, Server server) {
        if (environment.equals(Environment.PRODUCTION)) {
            if (server.equals(Server.ENUM_DEFAULT)) {
                return "https://www.googleapis.com";
            }
        }
        if (environment.equals(Environment.ENVIRONMENT2)) {
            if (server.equals(Server.ENUM_DEFAULT)) {
                return "https://maps.googleapis.com";
            }
        }
        if (environment.equals(Environment.ENVIRONMENT3)) {
            if (server.equals(Server.ENUM_DEFAULT)) {
                return "https://roads.googleapis.com";
            }
        }
        return "https://www.googleapis.com";
    }

    /**
     * Converts this GoogleMapsPlatformClient into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "GoogleMapsPlatformClient [" + "environment=" + environment + ", httpClientConfig="
                + httpClientConfig + ", loggingConfig=" + loggingConfig + ", authentications="
                + authentications + "]";
    }

    /**
     * Builds a new {@link GoogleMapsPlatformClient.Builder} object.
     * Creates the instance with the state of the current client.
     * @return a new {@link GoogleMapsPlatformClient.Builder} object
     */
    public Builder newBuilder() {
        Builder builder = new Builder();
        builder.environment = getEnvironment();
        builder.httpClient = getHttpClient();
        builder.customQueryAuthenticationCredentials(getCustomQueryAuthenticationModel()
                .toBuilder().build());
        builder.httpCallback = httpCallback;
        builder.httpClientConfig(() -> ((HttpClientConfiguration) httpClientConfig).newBuilder());
        builder.loggingConfig(() -> ((ApiLoggingConfiguration) loggingConfig).newBuilder());
        return builder;
    }

    /**
     * Class to build instances of {@link GoogleMapsPlatformClient}.
     */
    public static class Builder {

        private Environment environment = Environment.PRODUCTION;
        private HttpClient httpClient;
        private CustomQueryAuthenticationModel customQueryAuthenticationModel =
                new CustomQueryAuthenticationModel.Builder("").build();
        private HttpCallback httpCallback = null;
        private HttpClientConfiguration.Builder httpClientConfigBuilder =
                new HttpClientConfiguration.Builder();
        private ApiLoggingConfiguration.Builder loggingConfigBuilder = null;


        /**
         * Credentials setter for CustomQueryAuthenticationCredentials.
         * @param customQueryAuthenticationModel The instance of CustomQueryAuthenticationModel.
         * @return The current instance of builder.
         */
        public Builder customQueryAuthenticationCredentials(
                CustomQueryAuthenticationModel customQueryAuthenticationModel) {
            this.customQueryAuthenticationModel = customQueryAuthenticationModel;
            return this;
        }

        /**
         * Current API environment.
         * @param environment The environment for client.
         * @return Builder
         */
        public Builder environment(Environment environment) {
            this.environment = environment;
            return this;
        }

        /**
         * The timeout to use for making HTTP requests.
         * @deprecated This method will be removed in a future version. Use
         *             {@link #httpClientConfig(Consumer) httpClientConfig} instead.
         * @param timeout must be greater then 0.
         * @return Builder
         */
        @Deprecated
        public Builder timeout(long timeout) {
            this.httpClientConfigBuilder.timeout(timeout);
            return this;
        }

        /**
         * Setter for the Builder of LoggingConfiguration, takes in an operation to be
         * performed on the builder instance of logging configuration.
         * @param action Consumer for the builder of LoggingConfiguration.
         * @return Builder
         */
        public Builder loggingConfig(Consumer<ApiLoggingConfiguration.Builder> action) {
            if (loggingConfigBuilder == null) {
                loggingConfigBuilder = new ApiLoggingConfiguration.Builder();
            }

            if (loggingConfigBuilder.build().getLogger() == null) {
                loggingConfigBuilder.useDefaultLogger();
            }

            action.accept(loggingConfigBuilder);
            return this;
        }

        /**
         * Setter for the Builder of LoggingConfiguration with Console Logging.
         *
         * @return Builder
         */
        public Builder loggingConfig() {
            loggingConfigBuilder = new ApiLoggingConfiguration.Builder();
            loggingConfigBuilder.useDefaultLogger();
            return this;
        }

		/**
		 * Private setter for the Builder of LoggingConfiguration, takes in an operation to be
		 * performed on the builder instance of logging configuration.
		 * 
		 * @param supplier Supplier for the builder of LoggingConfiguration.
		 * @return Builder
		 */
		private Builder loggingConfig(Supplier<ApiLoggingConfiguration.Builder> supplier) {
			loggingConfigBuilder = supplier.get();
			return this;
		}

        /**
         * HttpCallback.
         * @param httpCallback Callback to be called before and after the HTTP call.
         * @return Builder
         */
        public Builder httpCallback(HttpCallback httpCallback) {
            this.httpCallback = httpCallback;
            return this;
        }

        /**
         * Setter for the Builder of httpClientConfiguration, takes in an operation to be performed
         * on the builder instance of HTTP client configuration.
         * 
         * @param action Consumer for the builder of httpClientConfiguration.
         * @return Builder
         */
        public Builder httpClientConfig(Consumer<HttpClientConfiguration.Builder> action) {
            action.accept(httpClientConfigBuilder);
            return this;
        }

        /**
         * Private Setter for the Builder of httpClientConfiguration, takes in an operation to be performed
         * on the builder instance of HTTP client configuration.
         * 
         * @param supplier Supplier for the builder of httpClientConfiguration.
         * @return Builder
         */
        private Builder httpClientConfig(Supplier<HttpClientConfiguration.Builder> supplier) {
            httpClientConfigBuilder = supplier.get();
            return this;
        }

        /**
         * Builds a new GoogleMapsPlatformClient object using the set fields.
         * @return GoogleMapsPlatformClient
         */
        public GoogleMapsPlatformClient build() {
            HttpClientConfiguration httpClientConfig = httpClientConfigBuilder.build();
            ReadonlyLoggingConfiguration loggingConfig = loggingConfigBuilder != null ? loggingConfigBuilder.build() 
                    : new ApiLoggingConfiguration.Builder().build();
            httpClient = new OkClient(httpClientConfig.getConfiguration(), compatibilityFactory);

            return new GoogleMapsPlatformClient(environment, httpClient, httpClientConfig,
                    loggingConfig, customQueryAuthenticationModel, httpCallback);
        }
    }
}