/*
 * GoogleMapsPlatformLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.googleapis.maps;

import com.googleapis.maps.authentication.CustomQueryAuthenticationModel;
import com.googleapis.maps.http.client.ReadonlyHttpClientConfiguration;
import com.googleapis.maps.logging.configuration.ReadonlyLoggingConfiguration;

/**
 * Configuration Interface for the library.
 */
public interface Configuration {

    /**
     * Current API environment.
     * @return a copy of environment
     */
    Environment getEnvironment();

    /**
     * Http Client Configuration instance.
     * @return a copy of httpClientConfig
     */
    ReadonlyHttpClientConfiguration getHttpClientConfig();

    /**
     * Logging Configuration instance.
     * @return a copy of loggingConfig
     */
    ReadonlyLoggingConfiguration getLoggingConfig();

    /**
     * The timeout to use for making HTTP requests. The timeout to use for making HTTP requests.
     * @return a copy of timeout
     */
    long timeout();

    /**
     * The credentials to use with CustomQueryAuthentication.
     * @return customQueryAuthenticationCredentials
     */
    CustomQueryAuthenticationCredentials getCustomQueryAuthenticationCredentials();

    /**
     * The auth credential model for CustomQueryAuthentication.
     * @return the instance of CustomQueryAuthenticationModel
     */
    CustomQueryAuthenticationModel getCustomQueryAuthenticationModel();

    /**
     * Get base URI by current environment.
     * @param server Server for which to get the base URI
     * @return Processed base URI
     */
    String getBaseUri(Server server);

    /**
     * Get base URI by current environment.
     * @return Processed base URI
     */
    String getBaseUri();
}
