/*
 * GoogleMapsPlatformLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.googleapis.maps;

/**
 * Interface for defining the behavior of CustomQuery Authentication.
 */
public interface CustomQueryAuthenticationCredentials {

    /**
     * String value for key.
     * @return key
     */
    String getKey();

    /**
     * Checks if provided credentials matched with existing ones.
     * @param key String value for credentials.
     * @return true if credentials matched.
     */
    boolean equals(String key);
}
