/*
 * GoogleMapsPlatformLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.googleapis.maps.exceptions;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.googleapis.maps.models.ErrorObject;
import io.apimatic.coreinterfaces.http.Context;

/**
 * This is a model class for ErrorResponseException type.
 */
public class ErrorResponseException extends ApiException {
    private static final long serialVersionUID = 108367321322501184L;
    private ErrorObject error;

    /**
     * Initialization constructor.
     * @param   reason  The reason for throwing exception
     * @param   context The context of the API exception
     */
    public ErrorResponseException(String reason, Context context) {
        super(reason, context);
    }


    /**
     * Getter for Error.
     * @return Returns the ErrorObject
     */
    @JsonGetter("error")
    public ErrorObject getError() {
        return this.error;
    }

    /**
     * Setter for Error.
     * @param error Value for ErrorObject
     */
    @JsonSetter("error")
    private void setError(ErrorObject error) {
        this.error = error;
    }

    /**
     * Converts this ErrorResponseException into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "ErrorResponseException [" + "statusCode=" + getResponseCode() + ", message="
                + getMessage() + ", error=" + error + "]";
    }
}
